// Types
export type {
  ConfigApplyLifecycle,
  ConfigApplyRecord,
  ConfigApplyRecordsResponse,
  ConfigApplyRecordStatus,
  SettingsApplyNextAction,
  SettingsApplyRecordsFilter,
  SettingsApplyResponse,
  SettingsAutomationSection,
  SettingsCollectionName,
  SettingsSandboxCollection,
  SettingsSandboxDetail,
  SettingsSandboxEntry,
  SettingsSandboxRequest,
  SettingsGeneralSection,
  SettingsHookCollection,
  SettingsHookEntry,
  SettingsHookRequest,
  SettingsHooksExtensionsHook,
  SettingsHooksExtensionsInstalled,
  SettingsHooksExtensionsSection,
  SettingsMCPAuthBeginResponse,
  SettingsMCPAuthExchangeRequest,
  SettingsMCPAuthFilter,
  SettingsMCPAuthStatusResponse,
  SettingsMCPServerCollection,
  SettingsMCPServerDeleteFilter,
  SettingsMCPServerEntry,
  SettingsMCPServerListFilter,
  SettingsMCPServerPutFilter,
  SettingsMCPServerRequest,
  SettingsMCPServerTarget,
  SettingsMemorySection,
  SettingsMutationResult,
  SettingsNetworkSection,
  SettingsObservabilitySection,
  ProviderDraft,
  SettingsProviderCollection,
  SettingsProviderCredentialSlotRequest,
  SettingsProviderDetail,
  SettingsProviderEntry,
  SettingsProviderModelRequest,
  SettingsProviderModelsRequest,
  SettingsProviderRequest,
  SettingsRestartResponse,
  SettingsRestartStatus,
  SettingsRestartStatusName,
  SettingsScope,
  SettingsSectionDescriptor,
  SettingsSectionName,
  SettingsSectionSlug,
  SettingsSkillsFilter,
  SettingsSkillsSection,
  SettingsSource,
  SettingsSourceKind,
  SettingsUpdateStatus,
  SettingsCreateNotificationPresetRequest,
  SettingsNotificationPresetCollection,
  SettingsNotificationPresetEntry,
  SettingsNotificationPresetFilter,
  SettingsNotificationPresetTarget,
  SettingsUpdateAutomationRequest,
  SettingsUpdateGeneralRequest,
  SettingsUpdateHooksExtensionsRequest,
  SettingsUpdateNotificationPresetRequest,
  SettingsUpdateMemoryRequest,
  SettingsUpdateNetworkRequest,
  SettingsUpdateObservabilityRequest,
  SettingsUpdateSkillsRequest,
  SettingsUpdateSkillsFilter,
  SettingsWriteTarget,
} from "./types";

// Section metadata
export {
  findSettingsSection,
  SETTINGS_ROOT_PATH,
  SETTINGS_SECTIONS,
  SETTINGS_SECTION_SLUGS,
  settingsSectionPath,
} from "./lib/sections";

// MCP page models (status matrix + editor draft)
export {
  authorizeLabel,
  composeMCPRowStatus,
  formatStatusLabel,
  isOAuthCapable,
  isOAuthRepairable,
  MCP_AUTH_STATUSES,
  MCP_PROBE_STATES,
  MCP_RUNTIME_STATES,
  probeToolLabel,
} from "./lib/mcp-status-view-model";
export type {
  MCPAuthorizeLabel,
  MCPAuthStatus,
  MCPProbeState,
  MCPRowStatus,
  MCPRuntimeState,
  MCPStatusCell,
} from "./lib/mcp-status-view-model";
export { emptyDraft, toDraft, toRequest, validateDraft } from "./lib/mcp-editor-model";
export type {
  MCPDraft,
  MCPDraftErrors,
  MCPDraftValidation,
  MCPEnvPair,
  MCPOAuthDiscovery,
  MCPOAuthDraft,
  MCPSecretBinding,
  MCPSecretEnvEntry,
  MCPSecretMode,
  MCPTransport,
} from "./lib/mcp-editor-model";

// Adapters
export {
  deleteSettingsSandbox,
  deleteSettingsHook,
  deleteSettingsMCPServer,
  deleteSettingsProvider,
  getSettingsAutomation,
  getSettingsSandbox,
  getSettingsGeneral,
  getSettingsHooksExtensions,
  getSettingsMemory,
  getSettingsNetwork,
  getSettingsObservability,
  getSettingsProvider,
  getSettingsRestartStatus,
  getSettingsSkills,
  getSettingsUpdate,
  listSettingsApplyRecords,
  listSettingsSandboxes,
  listSettingsHooks,
  listSettingsMCPServers,
  listSettingsProviders,
  OBSERVABILITY_LOG_TAIL_PATH,
  listSettingsNotificationPresets,
  createSettingsNotificationPreset,
  updateSettingsNotificationPreset,
  deleteSettingsNotificationPreset,
  putSettingsSandbox,
  putSettingsHook,
  putSettingsMCPServer,
  putSettingsProvider,
  reloadSettings,
  SettingsApiError,
  settingsObservabilityLogTailPath,
  triggerSettingsRestart,
  updateSettingsAutomation,
  updateSettingsGeneral,
  updateSettingsHooksExtensions,
  updateSettingsMemory,
  updateSettingsNetwork,
  updateSettingsObservability,
  updateSettingsSkills,
} from "./adapters/settings-api";
export {
  beginSettingsMCPAuth,
  exchangeSettingsMCPAuth,
  logoutSettingsMCPAuth,
} from "./adapters/settings-mcp-auth-api";

// Query infrastructure
export { settingsKeys } from "./lib/query-keys";
export {
  SETTINGS_QUERY_INTERVALS,
  settingsAutomationOptions,
  settingsApplyRecordsOptions,
  settingsSandboxDetailOptions,
  settingsSandboxesListOptions,
  settingsGeneralOptions,
  settingsHooksExtensionsOptions,
  settingsHooksListOptions,
  settingsNotificationPresetsOptions,
  settingsMCPServersListOptions,
  settingsMemoryOptions,
  settingsNetworkOptions,
  settingsObservabilityOptions,
  settingsProviderDetailOptions,
  settingsProvidersListOptions,
  settingsRestartStatusOptions,
  settingsSkillsOptions,
  settingsUpdateOptions,
} from "./lib/query-options";
export {
  isFailedRestart,
  isSuccessfulRestart,
  isTerminalRestartStatus,
  RESTART_TERMINAL_STATUSES,
} from "./lib/restart-status";
export { restartBannerPropsFor } from "./lib/restart-banner-mapper";

// Components
export {
  MCPActionResultBanner,
  MCPAuthorizeDialog,
  MCPSelectionStrip,
  MCPServerDeleteDialog,
  MCPServerEditor,
  MCPServersTable,
  ProviderCard,
  ProviderEditForm,
  ProviderInspectorSheet,
  ProviderInspectView,
  ProviderLogo,
  ProviderModelCatalogStatus,
  ProvidersGrid,
  ProvidersListFilters,
  SettingsApplyRecordsPanel,
  SettingsDecimalInput,
  SettingsDisabledSkillsSection,
  SettingsEditorDialog,
  SettingsFieldRow,
  SettingsNumberInput,
  SettingsSaveBar,
  SettingsSourceBadge,
} from "./components";

// Stores
export { useSettingsRestartStore } from "./stores/use-settings-restart-store";
export type {
  PendingSettingsMutation,
  SettingsRestartActions,
  SettingsRestartState,
  SettingsRestartStore,
} from "./stores/settings-restart-store";

// Hooks -- reads
export {
  useSettingsAutomation,
  useSettingsApplyRecords,
  useSettingsGeneral,
  useSettingsHooksExtensions,
  useSettingsMemory,
  useSettingsNetwork,
  useSettingsObservability,
  useSettingsSkills,
  useSettingsUpdate,
} from "./hooks/use-settings-sections";
export {
  useSettingsSandbox,
  useSettingsSandboxes,
  useSettingsNotificationPresets,
  useSettingsHooks,
  useSettingsMCPServers,
  useSettingsProvider,
  useSettingsProviders,
} from "./hooks/use-settings-collections";

// Hooks -- mutations
export {
  useBeginMCPAuth,
  useDeleteSettingsSandbox,
  useDeleteSettingsHook,
  useDeleteSettingsMCPServer,
  useExchangeMCPAuth,
  useLogoutMCPAuth,
  useDeleteSettingsProvider,
  useCreateSettingsNotificationPreset,
  useUpdateSettingsNotificationPreset,
  useDeleteSettingsNotificationPreset,
  usePutSettingsSandbox,
  usePutSettingsHook,
  usePutSettingsMCPServer,
  usePutSettingsProvider,
  useReloadSettings,
  useUpdateSettingsAutomation,
  useUpdateSettingsGeneral,
  useUpdateSettingsHooksExtensions,
  useUpdateSettingsMemory,
  useUpdateSettingsNetwork,
  useUpdateSettingsObservability,
  useUpdateSettingsSkills,
} from "./hooks/use-settings-mutations";

// Hooks -- restart
export { useSettingsRestart } from "./hooks/use-settings-restart";
