package sdkts

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
	"time"

	extensioncontract "github.com/pedronauck/agh/internal/extension/contract"
	extensionprotocol "github.com/pedronauck/agh/internal/extension/protocol"
	"github.com/pedronauck/agh/internal/hooks"
	"github.com/pedronauck/agh/internal/memory"
	"github.com/pedronauck/agh/internal/session"
	"github.com/pedronauck/agh/internal/store"
	"github.com/pedronauck/agh/internal/tools"
)

var (
	rawMessageType = reflect.TypeOf(json.RawMessage{})
	timeType       = reflect.TypeOf(time.Time{})
	durationType   = reflect.TypeOf(time.Duration(0))
)

// Generate renders the canonical SDK contracts TypeScript module.
func Generate() (string, error) {
	gen := newGenerator()
	if err := gen.prepare(); err != nil {
		return "", err
	}
	if err := gen.emitAllNamedTypes(); err != nil {
		return "", err
	}
	gen.emitHookMaps()
	gen.emitHostMethodMap()

	var out bytes.Buffer
	out.WriteString("// Code generated by go run ./cmd/agh-codegen sdk-contracts. DO NOT EDIT.\n")
	out.WriteString("import type { ISODateTime, JSONValue } from \"../base-types.js\";\n\n")
	for _, block := range gen.blocks {
		out.WriteString(block)
		if !strings.HasSuffix(block, "\n") {
			out.WriteByte('\n')
		}
		out.WriteByte('\n')
	}

	return strings.TrimRight(out.String(), "\n") + "\n", nil
}

type generator struct {
	hostSpecs  []extensioncontract.HostAPIMethodSpec
	hookSpecs  []extensioncontract.HookContractSpec
	rootTypes  []extensioncontract.NamedType
	typeNames  map[reflect.Type]string
	queued     map[string]reflect.Type
	emitted    map[string]bool
	processing map[string]bool
	blocks     []string
}

func newGenerator() *generator {
	hostSpecs := extensioncontract.HostAPIMethodSpecs()
	hookSpecs := extensioncontract.HookContracts()

	rootTypes := make([]extensioncontract.NamedType, 0)
	rootTypes = append(rootTypes, extensioncontract.SDKRootTypes()...)
	for _, spec := range hostSpecs {
		rootTypes = append(rootTypes, spec.Params, spec.Result)
	}
	for _, spec := range hookSpecs {
		rootTypes = append(rootTypes, spec.Payload, spec.Patch)
	}

	return &generator{
		hostSpecs:  hostSpecs,
		hookSpecs:  hookSpecs,
		rootTypes:  rootTypes,
		typeNames:  map[reflect.Type]string{},
		queued:     map[string]reflect.Type{},
		emitted:    map[string]bool{},
		processing: map[string]bool{},
	}
}

func (g *generator) prepare() error {
	for _, root := range g.rootTypes {
		t := namedBaseType(root.Value)
		if t == nil {
			continue
		}
		if existing, ok := g.typeNames[t]; !ok {
			g.typeNames[t] = root.Name
		} else if existing == root.Name {
			continue
		}
		g.queued[root.Name] = t
	}
	return nil
}

func namedBaseType(value any) reflect.Type {
	if value == nil {
		return nil
	}
	t := reflect.TypeOf(value)
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t.Kind() == reflect.Slice || t.Kind() == reflect.Array {
		t = t.Elem()
	}
	return t
}

func (g *generator) emitAllNamedTypes() error {
	names := make([]string, 0, len(g.queued))
	for name := range g.queued {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if err := g.ensureNamed(name, g.queued[name]); err != nil {
			return err
		}
	}
	return nil
}

func (g *generator) ensureNamed(name string, t reflect.Type) error {
	if name == "" || t == nil || g.emitted[name] {
		return nil
	}
	if g.processing[name] {
		return nil
	}
	g.processing[name] = true
	defer delete(g.processing, name)

	switch {
	case isEnumType(t):
		g.blocks = append(g.blocks, fmt.Sprintf("export type %s = %s;\n", name, strings.Join(enumValuesForType(t), " | ")))
	case isPrimitiveAliasType(t):
		g.blocks = append(g.blocks, fmt.Sprintf("export type %s = %s;\n", name, g.primitiveAliasForType(t)))
	case t.Kind() == reflect.Struct:
		fields, err := g.structFields(t)
		if err != nil {
			return err
		}
		if len(fields) == 0 {
			g.blocks = append(g.blocks, fmt.Sprintf("export type %s = Record<string, never>;\n", name))
			break
		}
		var out strings.Builder
		out.WriteString("export interface ")
		out.WriteString(name)
		out.WriteString(" {\n")
		for _, field := range fields {
			out.WriteString("  ")
			out.WriteString(field.Name)
			if field.Optional {
				out.WriteByte('?')
			}
			out.WriteString(": ")
			out.WriteString(field.Type)
			out.WriteString(";\n")
		}
		out.WriteString("}\n")
		g.blocks = append(g.blocks, out.String())
	default:
		tsType, err := g.tsType(t)
		if err != nil {
			return err
		}
		g.blocks = append(g.blocks, fmt.Sprintf("export type %s = %s;\n", name, tsType))
	}

	g.emitted[name] = true
	return nil
}

type fieldSpec struct {
	Name     string
	Type     string
	Optional bool
}

func (g *generator) structFields(t reflect.Type) ([]fieldSpec, error) {
	fields := make([]fieldSpec, 0)
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		if !field.IsExported() {
			continue
		}
		if field.Anonymous && field.Tag.Get("json") == "" {
			embedded := field.Type
			for embedded.Kind() == reflect.Pointer {
				embedded = embedded.Elem()
			}
			if embedded.Kind() == reflect.Struct {
				embeddedFields, err := g.structFields(embedded)
				if err != nil {
					return nil, err
				}
				fields = append(fields, embeddedFields...)
				continue
			}
		}

		jsonName, omitempty := jsonFieldName(field)
		if jsonName == "" {
			continue
		}
		tsType, err := g.tsType(field.Type)
		if err != nil {
			return nil, fmt.Errorf("resolve field %s.%s: %w", t.Name(), field.Name, err)
		}
		fields = append(fields, fieldSpec{
			Name:     jsonName,
			Type:     tsType,
			Optional: omitempty || field.Type.Kind() == reflect.Pointer,
		})
	}
	return fields, nil
}

func jsonFieldName(field reflect.StructField) (string, bool) {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", false
	}
	if tag == "" {
		return field.Name, false
	}
	parts := strings.Split(tag, ",")
	name := strings.TrimSpace(parts[0])
	if name == "" {
		name = field.Name
	}
	omitempty := false
	for _, part := range parts[1:] {
		if strings.TrimSpace(part) == "omitempty" {
			omitempty = true
		}
	}
	return name, omitempty
}

func (g *generator) tsType(t reflect.Type) (string, error) {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}

	switch {
	case t == rawMessageType:
		return "JSONValue", nil
	case t == timeType:
		return "ISODateTime", nil
	case t == durationType:
		return "number", nil
	case t.Kind() == reflect.Interface:
		return "JSONValue", nil
	}

	if name, ok := g.typeNames[t]; ok {
		if err := g.ensureNamed(name, t); err != nil {
			return "", err
		}
		return name, nil
	}
	if shouldAutoEmitNamedType(t) {
		name := t.Name()
		g.typeNames[t] = name
		g.queued[name] = t
		if err := g.ensureNamed(name, t); err != nil {
			return "", err
		}
		return name, nil
	}

	if isEnumType(t) {
		name := t.Name()
		g.typeNames[t] = name
		if err := g.ensureNamed(name, t); err != nil {
			return "", err
		}
		return name, nil
	}

	switch t.Kind() {
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.String:
		return "string", nil
	case reflect.Slice, reflect.Array:
		elemType, err := g.tsType(t.Elem())
		if err != nil {
			return "", err
		}
		return parenthesizeIfNeeded(elemType) + "[]", nil
	case reflect.Map:
		elemType, err := g.tsType(t.Elem())
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("Record<string, %s>", elemType), nil
	case reflect.Struct:
		fields, err := g.structFields(t)
		if err != nil {
			return "", err
		}
		if len(fields) == 0 {
			return "Record<string, never>", nil
		}
		var out strings.Builder
		out.WriteString("{ ")
		for idx, field := range fields {
			if idx > 0 {
				out.WriteString("; ")
			}
			out.WriteString(field.Name)
			if field.Optional {
				out.WriteByte('?')
			}
			out.WriteString(": ")
			out.WriteString(field.Type)
		}
		out.WriteString(" }")
		return out.String(), nil
	default:
		return "JSONValue", nil
	}
}

func (g *generator) primitiveAliasForType(t reflect.Type) string {
	switch t {
	case rawMessageType:
		return "JSONValue"
	case timeType:
		return "ISODateTime"
	case durationType:
		return "number"
	}
	switch t.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	default:
		return "string"
	}
}

func parenthesizeIfNeeded(value string) string {
	if strings.Contains(value, " | ") {
		return "(" + value + ")"
	}
	return value
}

func isPrimitiveAliasType(t reflect.Type) bool {
	if t == rawMessageType || t == timeType || t == durationType {
		return true
	}
	switch t.Kind() {
	case reflect.Bool,
		reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64,
		reflect.String:
		return true
	default:
		return false
	}
}

func isEnumType(t reflect.Type) bool {
	_, ok := enumValuesRegistry[t]
	return ok
}

var enumValuesRegistry = map[reflect.Type][]string{
	reflect.TypeOf(extensionprotocol.HostAPIMethod("")): hostAPIMethodValues(),
	reflect.TypeOf(hooks.HookEvent("")):                 hookEventValues(),
	reflect.TypeOf(hooks.HookEventFamily("")):           hookEventFamilyValues(),
	reflect.TypeOf(hooks.HookMode("")):                  hookModeValues(),
	reflect.TypeOf(hooks.HookRunOutcome("")):            hookOutcomeValues(),
	reflect.TypeOf(hooks.HookSkillSource("")):           hookSkillSourceValues(),
	reflect.TypeOf(hooks.HookExecutorKind("")):          hookExecutorKindValues(),
	reflect.TypeOf(hooks.HookSource(0)):                 hookSourceValues(),
	reflect.TypeOf(memory.MemoryType("")):               memoryTypeValues(),
	reflect.TypeOf(memory.Scope("")):                    memoryScopeValues(),
	reflect.TypeOf(session.SessionState("")):            sessionStateValues(),
	reflect.TypeOf(store.StopReason("")):                stopReasonValues(),
	reflect.TypeOf(tools.ToolSource(0)):                 toolSourceValues(),
}

func enumValuesForType(t reflect.Type) []string {
	values := enumValuesRegistry[t]
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return quoted
}

func (g *generator) emitHookMaps() {
	var payload strings.Builder
	payload.WriteString("export interface HookPayloadByEvent {\n")
	for _, spec := range g.hookSpecs {
		fmt.Fprintf(&payload, "  %q: %s;\n", spec.Event, spec.Payload.Name)
	}
	payload.WriteString("}\n")
	g.blocks = append(g.blocks, payload.String())

	var patch strings.Builder
	patch.WriteString("export interface HookPatchByEvent {\n")
	for _, spec := range g.hookSpecs {
		fmt.Fprintf(&patch, "  %q: %s;\n", spec.Event, spec.Patch.Name)
	}
	patch.WriteString("}\n")
	g.blocks = append(g.blocks, patch.String())
}

func (g *generator) emitHostMethodMap() {
	var out strings.Builder
	out.WriteString("export interface HostAPIMethodMap {\n")
	for _, spec := range g.hostSpecs {
		paramsType := spec.Params.Name
		if spec.OptionalParams {
			if spec.Params.Name == "EmptyResult" {
				paramsType = "undefined"
			} else {
				paramsType = paramsType + " | undefined"
			}
		}
		resultType := spec.Result.Name
		if resultIsList(spec.Result.Value) {
			resultType += "[]"
		}
		fmt.Fprintf(&out, "  %q: {\n", spec.Method)
		fmt.Fprintf(&out, "    params: %s;\n", paramsType)
		fmt.Fprintf(&out, "    result: %s;\n", resultType)
		out.WriteString("  };\n")
	}
	out.WriteString("}\n")
	g.blocks = append(g.blocks, out.String())
}

func resultIsList(value any) bool {
	if value == nil {
		return false
	}
	t := reflect.TypeOf(value)
	return t.Kind() == reflect.Slice || t.Kind() == reflect.Array
}

func hostAPIMethodValues() []string {
	specs := extensioncontract.HostAPIMethodSpecs()
	values := make([]string, 0, len(specs))
	for _, spec := range specs {
		values = append(values, string(spec.Method))
	}
	sort.Strings(values)
	return values
}

func hookEventValues() []string {
	values := make([]string, 0, len(hooks.AllHookEvents()))
	for _, event := range hooks.AllHookEvents() {
		values = append(values, string(event))
	}
	return values
}

func hookEventFamilyValues() []string {
	return []string{
		string(hooks.HookEventFamilySession),
		string(hooks.HookEventFamilyInput),
		string(hooks.HookEventFamilyPrompt),
		string(hooks.HookEventFamilyEvent),
		string(hooks.HookEventFamilyAgent),
		string(hooks.HookEventFamilyTurn),
		string(hooks.HookEventFamilyMessage),
		string(hooks.HookEventFamilyTool),
		string(hooks.HookEventFamilyPermission),
		string(hooks.HookEventFamilyContext),
	}
}

func hookModeValues() []string {
	return []string{string(hooks.HookModeSync), string(hooks.HookModeAsync)}
}

func hookOutcomeValues() []string {
	return []string{
		string(hooks.HookRunOutcomeApplied),
		string(hooks.HookRunOutcomeDenied),
		string(hooks.HookRunOutcomeFailed),
		string(hooks.HookRunOutcomeSkipped),
		string(hooks.HookRunOutcomeDropped),
		string(hooks.HookRunOutcomeRejected),
	}
}

func hookSkillSourceValues() []string {
	return []string{
		string(hooks.HookSkillSourceBundled),
		string(hooks.HookSkillSourceMarketplace),
		string(hooks.HookSkillSourceUser),
		string(hooks.HookSkillSourceAdditional),
		string(hooks.HookSkillSourceWorkspace),
	}
}

func hookExecutorKindValues() []string {
	return []string{
		string(hooks.HookExecutorNative),
		string(hooks.HookExecutorSubprocess),
		string(hooks.HookExecutorWASM),
	}
}

func hookSourceValues() []string {
	return []string{"native", "config", "agent_definition", "skill"}
}

func memoryTypeValues() []string {
	return []string{
		string(memory.MemoryTypeUser),
		string(memory.MemoryTypeFeedback),
		string(memory.MemoryTypeProject),
		string(memory.MemoryTypeReference),
	}
}

func memoryScopeValues() []string {
	return []string{string(memory.ScopeGlobal), string(memory.ScopeWorkspace)}
}

func sessionStateValues() []string {
	return []string{
		string(session.StateStarting),
		string(session.StateActive),
		string(session.StateStopping),
		string(session.StateStopped),
	}
}

func stopReasonValues() []string {
	return []string{
		string(store.StopCompleted),
		string(store.StopUserCanceled),
		string(store.StopMaxIterations),
		string(store.StopLoopDetected),
		string(store.StopTimeout),
		string(store.StopBudgetExceeded),
		string(store.StopError),
		string(store.StopAgentCrashed),
		string(store.StopHookStopped),
		string(store.StopShutdown),
	}
}

func toolSourceValues() []string {
	return []string{"builtin", "mcp", "extension", "dynamic"}
}

func shouldAutoEmitNamedType(t reflect.Type) bool {
	if t == nil || t.Name() == "" {
		return false
	}
	if !strings.HasPrefix(t.PkgPath(), "github.com/pedronauck/agh/internal/") {
		return false
	}
	return t.Kind() == reflect.Struct || isEnumType(t) || isPrimitiveAliasType(t)
}
