package sdkts

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	apicontract "github.com/pedronauck/agh/internal/api/contract"
	extensioncontract "github.com/pedronauck/agh/internal/extension/contract"
	extensionprotocol "github.com/pedronauck/agh/internal/extension/protocol"
	"github.com/pedronauck/agh/internal/hooks"
	memcontract "github.com/pedronauck/agh/internal/memory/contract"
	"github.com/pedronauck/agh/internal/session"
	"github.com/pedronauck/agh/internal/store"
	"github.com/pedronauck/agh/internal/tools"
)

const (
	generateStringKey = "string"
)

var (
	rawMessageType = reflect.TypeFor[json.RawMessage]()
	timeType       = reflect.TypeFor[time.Time]()
	durationType   = reflect.TypeFor[time.Duration]()
)

const (
	jsonValueTypeName = "JSONValue"
	numberTypeName    = "number"
	generatedHeader   = "// Code generated by go run ./cmd/agh-codegen sdk-contracts. DO NOT EDIT.\n"
	generatedImport   = "import type { ISODateTime, JSONValue } from \"../base-types.js\";\n\n"
)

// Generate renders the canonical SDK contracts TypeScript module.
func Generate() (string, error) {
	gen, err := newGenerator()
	if err != nil {
		return "", err
	}
	gen.prepare()
	if err := gen.emitAllNamedTypes(); err != nil {
		return "", err
	}
	gen.emitHookMaps()
	gen.emitHostMethodMap()

	var out strings.Builder
	out.Grow(estimatedOutputSize(gen.blocks))
	out.WriteString(generatedHeader)
	out.WriteString(generatedImport)
	for idx, block := range gen.blocks {
		out.WriteString(block)
		if !strings.HasSuffix(block, "\n") {
			out.WriteByte('\n')
		}
		if idx < len(gen.blocks)-1 {
			out.WriteByte('\n')
		}
	}

	return out.String(), nil
}

type generator struct {
	hostSpecs  []extensioncontract.HostAPIMethodSpec
	hookSpecs  []extensioncontract.HookContractSpec
	rootTypes  []extensioncontract.NamedType
	typeNames  map[reflect.Type]string
	queued     map[string]reflect.Type
	emitted    map[string]bool
	processing map[string]bool
	fieldSpecs map[reflect.Type][]fieldSpec
	blocks     []string
}

func newGenerator() (*generator, error) {
	hostSpecs := extensioncontract.HostAPIMethodSpecs()
	hookSpecs, err := extensioncontract.BuildHookContracts()
	if err != nil {
		return nil, fmt.Errorf("build hook contracts: %w", err)
	}
	sdkRootTypes := extensioncontract.SDKRootTypes()

	rootTypes := make(
		[]extensioncontract.NamedType,
		0,
		len(sdkRootTypes)+(len(hostSpecs)*2)+(len(hookSpecs)*2),
	)
	rootTypes = append(rootTypes, sdkRootTypes...)
	for _, spec := range hostSpecs {
		rootTypes = append(rootTypes, spec.Params, spec.Result)
	}
	for _, spec := range hookSpecs {
		rootTypes = append(rootTypes, spec.Payload, spec.Patch)
	}

	return &generator{
		hostSpecs:  hostSpecs,
		hookSpecs:  hookSpecs,
		rootTypes:  rootTypes,
		typeNames:  map[reflect.Type]string{},
		queued:     map[string]reflect.Type{},
		emitted:    map[string]bool{},
		processing: map[string]bool{},
		fieldSpecs: map[reflect.Type][]fieldSpec{},
		blocks:     make([]string, 0, len(rootTypes)+3),
	}, nil
}

func (g *generator) prepare() {
	for _, root := range g.rootTypes {
		t := namedBaseType(root.Value)
		if t == nil {
			continue
		}
		if existing, ok := g.typeNames[t]; !ok {
			g.typeNames[t] = root.Name
		} else if existing == root.Name {
			continue
		}
		g.queued[root.Name] = t
	}
}

func namedBaseType(value any) reflect.Type {
	if value == nil {
		return nil
	}
	t := reflect.TypeOf(value)
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t.Kind() == reflect.Slice || t.Kind() == reflect.Array {
		t = t.Elem()
	}
	return t
}

func (g *generator) emitAllNamedTypes() error {
	names := make([]string, 0, len(g.queued))
	for name := range g.queued {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if err := g.ensureNamed(name, g.queued[name]); err != nil {
			return err
		}
	}
	return nil
}

func (g *generator) ensureNamed(name string, t reflect.Type) error {
	if name == "" || t == nil || g.emitted[name] {
		return nil
	}
	if g.processing[name] {
		return nil
	}
	g.processing[name] = true
	defer delete(g.processing, name)

	switch {
	case isEnumType(t):
		g.blocks = append(g.blocks, renderTypeAlias(name, enumUnionForType(t)))
	case isPrimitiveAliasType(t):
		g.blocks = append(g.blocks, renderTypeAlias(name, g.primitiveAliasForType(t)))
	case t.Kind() == reflect.Struct:
		fields, err := g.structFields(t)
		if err != nil {
			return err
		}
		if len(fields) == 0 {
			g.blocks = append(g.blocks, renderTypeAlias(name, "Record<string, never>"))
			break
		}
		g.blocks = append(g.blocks, renderInterface(name, fields))
	default:
		tsType, err := g.tsType(t)
		if err != nil {
			return err
		}
		g.blocks = append(g.blocks, renderTypeAlias(name, tsType))
	}

	g.emitted[name] = true
	return nil
}

type fieldSpec struct {
	Name     string
	Type     string
	Optional bool
}

func (g *generator) structFields(t reflect.Type) ([]fieldSpec, error) {
	if cached, ok := g.fieldSpecs[t]; ok {
		return cached, nil
	}
	fields := make([]fieldSpec, 0, t.NumField())
	for field := range t.Fields() {
		if !field.IsExported() {
			continue
		}
		if field.Anonymous && field.Tag.Get("json") == "" {
			embedded := field.Type
			for embedded.Kind() == reflect.Pointer {
				embedded = embedded.Elem()
			}
			if embedded.Kind() == reflect.Struct {
				embeddedFields, err := g.structFields(embedded)
				if err != nil {
					return nil, err
				}
				fields = append(fields, embeddedFields...)
				continue
			}
		}

		jsonName, optionalJSON := jsonFieldName(field)
		if jsonName == "" {
			continue
		}
		tsType, err := g.tsType(field.Type)
		if err != nil {
			return nil, fmt.Errorf("resolve field %s.%s: %w", t.Name(), field.Name, err)
		}
		fields = append(fields, fieldSpec{
			Name:     jsonName,
			Type:     tsType,
			Optional: optionalJSON || field.Type.Kind() == reflect.Pointer,
		})
	}
	g.fieldSpecs[t] = fields
	return fields, nil
}

func jsonFieldName(field reflect.StructField) (string, bool) {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", false
	}
	if tag == "" {
		return field.Name, false
	}
	name, opts, _ := strings.Cut(tag, ",")
	if name == "" {
		name = field.Name
	}
	optional := false
	for opts != "" {
		part := opts
		if next, rest, found := strings.Cut(opts, ","); found {
			part = next
			opts = rest
		} else {
			opts = ""
		}
		if part == "omitempty" || part == "omitzero" {
			optional = true
			break
		}
	}
	return name, optional
}

func (g *generator) tsType(t reflect.Type) (string, error) {
	base := dereferenceType(t)

	if primitive, ok := tsPrimitiveType(base); ok {
		return primitive, nil
	}
	if name, ok, err := g.resolveNamedTSType(base); ok || err != nil {
		return name, err
	}
	return g.tsTypeByKind(base)
}

func dereferenceType(t reflect.Type) reflect.Type {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	return t
}

func tsPrimitiveType(t reflect.Type) (string, bool) {
	switch {
	case t == rawMessageType:
		return jsonValueTypeName, true
	case t == timeType:
		return "ISODateTime", true
	case t == durationType:
		return numberTypeName, true
	case t.Kind() == reflect.Interface:
		return jsonValueTypeName, true
	default:
		return "", false
	}
}

func (g *generator) resolveNamedTSType(t reflect.Type) (string, bool, error) {
	if name, ok := g.typeNames[t]; ok {
		if err := g.ensureNamed(name, t); err != nil {
			return "", true, err
		}
		return name, true, nil
	}
	if shouldAutoEmitNamedType(t) || isEnumType(t) {
		name := t.Name()
		g.typeNames[t] = name
		if shouldAutoEmitNamedType(t) {
			g.queued[name] = t
		}
		if err := g.ensureNamed(name, t); err != nil {
			return "", true, err
		}
		return name, true, nil
	}
	return "", false, nil
}

func (g *generator) tsTypeByKind(t reflect.Type) (string, error) {
	if primitive, ok := primitiveKindTSType(t.Kind()); ok {
		return primitive, nil
	}
	switch t.Kind() {
	case reflect.Slice, reflect.Array:
		elemType, err := g.tsType(t.Elem())
		if err != nil {
			return "", err
		}
		return parenthesizeIfNeeded(elemType) + "[]", nil
	case reflect.Map:
		elemType, err := g.tsType(t.Elem())
		if err != nil {
			return "", err
		}
		return "Record<string, " + elemType + ">", nil
	case reflect.Struct:
		fields, err := g.structFields(t)
		if err != nil {
			return "", err
		}
		if len(fields) == 0 {
			return "Record<string, never>", nil
		}
		return renderInlineObject(fields), nil
	default:
		return jsonValueTypeName, nil
	}
}

func (g *generator) primitiveAliasForType(t reflect.Type) string {
	switch t {
	case rawMessageType:
		return "JSONValue"
	case timeType:
		return "ISODateTime"
	case durationType:
		return "number"
	}
	if primitive, ok := primitiveKindTSType(t.Kind()); ok {
		return primitive
	}
	return generateStringKey
}

func parenthesizeIfNeeded(value string) string {
	if strings.Contains(value, " | ") {
		return "(" + value + ")"
	}
	return value
}

func isPrimitiveAliasType(t reflect.Type) bool {
	if t == rawMessageType || t == timeType || t == durationType {
		return true
	}
	_, ok := primitiveKindTSType(t.Kind())
	return ok
}

func primitiveKindTSType(kind reflect.Kind) (string, bool) {
	switch kind {
	case reflect.Bool:
		return "boolean", true
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return numberTypeName, true
	case reflect.String:
		return generateStringKey, true
	default:
		return "", false
	}
}

func isEnumType(t reflect.Type) bool {
	_, ok := enumValuesRegistry[t]
	return ok
}

var enumValuesRegistry = map[reflect.Type][]string{
	reflect.TypeFor[apicontract.AuthoredValidationStatus]():         apicontract.AuthoredValidationStatusValues(),
	reflect.TypeFor[apicontract.AuthoredDiagnosticSeverity]():       apicontract.AuthoredDiagnosticSeverityValues(),
	reflect.TypeFor[apicontract.AgentSoulRevisionAction]():          apicontract.AgentSoulRevisionActionValues(),
	reflect.TypeFor[apicontract.HeartbeatRevisionOperation]():       apicontract.HeartbeatRevisionOperationValues(),
	reflect.TypeFor[apicontract.HeartbeatActorKind]():               apicontract.HeartbeatActorKindValues(),
	reflect.TypeFor[apicontract.SessionHealthState]():               apicontract.SessionHealthStateValues(),
	reflect.TypeFor[apicontract.SessionHealthStatus]():              apicontract.SessionHealthStatusValues(),
	reflect.TypeFor[apicontract.SessionHealthIneligibilityReason](): apicontract.SessionHealthIneligibilityReasonValues(),
	reflect.TypeFor[apicontract.HeartbeatWakeSource]():              apicontract.HeartbeatWakeSourceValues(),
	reflect.TypeFor[apicontract.HeartbeatWakeResult]():              apicontract.HeartbeatWakeResultValues(),
	reflect.TypeFor[apicontract.HeartbeatWakeReason]():              apicontract.HeartbeatWakeReasonValues(),
	reflect.TypeFor[extensionprotocol.HostAPIMethod]():              hostAPIMethodValues(),
	reflect.TypeFor[hooks.HookEvent]():                              hookEventValues(),
	reflect.TypeFor[hooks.HookEventFamily]():                        hookEventFamilyValues(),
	reflect.TypeFor[hooks.HookMode]():                               hookModeValues(),
	reflect.TypeFor[hooks.HookRunOutcome]():                         hookOutcomeValues(),
	reflect.TypeFor[hooks.HookSkillSource]():                        hookSkillSourceValues(),
	reflect.TypeFor[hooks.HookExecutorKind]():                       hookExecutorKindValues(),
	reflect.TypeFor[hooks.HookSource]():                             hookSourceValues(),
	reflect.TypeFor[memcontract.Type]():                             memoryTypeValues(),
	reflect.TypeFor[memcontract.Scope]():                            memoryScopeValues(),
	reflect.TypeFor[session.State]():                                sessionStateValues(),
	reflect.TypeFor[store.StopReason]():                             stopReasonValues(),
	reflect.TypeFor[tools.ToolSource]():                             toolSourceValues(),
}

func enumUnionForType(t reflect.Type) string {
	values := enumValuesRegistry[t]
	var out strings.Builder
	out.Grow(estimatedEnumUnionSize(values))
	for idx, value := range values {
		if idx > 0 {
			out.WriteString(" | ")
		}
		writeQuotedString(&out, value)
	}
	return out.String()
}

func (g *generator) emitHookMaps() {
	var payload strings.Builder
	payload.Grow(estimatedHookMapSize("export interface HookPayloadByEvent {\n", g.hookSpecs, true))
	payload.WriteString("export interface HookPayloadByEvent {\n")
	for _, spec := range g.hookSpecs {
		payload.WriteString("  ")
		writeQuotedString(&payload, string(spec.Event))
		payload.WriteString(": ")
		payload.WriteString(spec.Payload.Name)
		payload.WriteString(";\n")
	}
	payload.WriteString("}\n")
	g.blocks = append(g.blocks, payload.String())

	var patch strings.Builder
	patch.Grow(estimatedHookMapSize("export interface HookPatchByEvent {\n", g.hookSpecs, false))
	patch.WriteString("export interface HookPatchByEvent {\n")
	for _, spec := range g.hookSpecs {
		patch.WriteString("  ")
		writeQuotedString(&patch, string(spec.Event))
		patch.WriteString(": ")
		patch.WriteString(spec.Patch.Name)
		patch.WriteString(";\n")
	}
	patch.WriteString("}\n")
	g.blocks = append(g.blocks, patch.String())
}

func (g *generator) emitHostMethodMap() {
	var out strings.Builder
	out.Grow(estimatedHostMethodMapSize(g.hostSpecs))
	out.WriteString("export interface HostAPIMethodMap {\n")
	for _, spec := range g.hostSpecs {
		paramsType := spec.Params.Name
		if spec.OptionalParams {
			if spec.Params.Name == "EmptyResult" {
				paramsType = "undefined"
			} else {
				paramsType += " | undefined"
			}
		}
		resultType := spec.Result.Name
		if resultIsList(spec.Result.Value) {
			resultType += "[]"
		}
		out.WriteString("  ")
		writeQuotedString(&out, string(spec.Method))
		out.WriteString(": {\n")
		out.WriteString("    params: ")
		out.WriteString(paramsType)
		out.WriteString(";\n")
		out.WriteString("    result: ")
		out.WriteString(resultType)
		out.WriteString(";\n")
		out.WriteString("  };\n")
	}
	out.WriteString("}\n")
	g.blocks = append(g.blocks, out.String())
}

func resultIsList(value any) bool {
	if value == nil {
		return false
	}
	t := reflect.TypeOf(value)
	return t.Kind() == reflect.Slice || t.Kind() == reflect.Array
}

func hostAPIMethodValues() []string {
	specs := extensioncontract.HostAPIMethodSpecs()
	values := make([]string, 0, len(specs))
	for _, spec := range specs {
		values = append(values, string(spec.Method))
	}
	sort.Strings(values)
	return values
}

func hookEventValues() []string {
	events := hooks.AllHookEvents()
	values := make([]string, 0, len(events))
	for _, event := range events {
		values = append(values, string(event))
	}
	return values
}

func hookEventFamilyValues() []string {
	return hookEventFamilyValuesFromEvents(hooks.AllHookEvents())
}

func hookEventFamilyValuesFromEvents(events []hooks.HookEvent) []string {
	values := make([]string, 0, len(events))
	seen := map[hooks.HookEventFamily]struct{}{}
	for _, event := range events {
		family := event.Family()
		if family == "" {
			continue
		}
		if _, ok := seen[family]; ok {
			continue
		}
		seen[family] = struct{}{}
		values = append(values, string(family))
	}
	return values
}

func hookModeValues() []string {
	return []string{string(hooks.HookModeSync), string(hooks.HookModeAsync)}
}

func hookOutcomeValues() []string {
	return []string{
		string(hooks.HookRunOutcomeApplied),
		string(hooks.HookRunOutcomeDenied),
		string(hooks.HookRunOutcomeFailed),
		string(hooks.HookRunOutcomeSkipped),
		string(hooks.HookRunOutcomeDropped),
		string(hooks.HookRunOutcomeRejected),
	}
}

func hookSkillSourceValues() []string {
	return []string{
		string(hooks.HookSkillSourceBundled),
		string(hooks.HookSkillSourceMarketplace),
		string(hooks.HookSkillSourceUser),
		string(hooks.HookSkillSourceAdditional),
		string(hooks.HookSkillSourceWorkspace),
	}
}

func hookExecutorKindValues() []string {
	return []string{
		string(hooks.HookExecutorNative),
		string(hooks.HookExecutorSubprocess),
		string(hooks.HookExecutorWASM),
	}
}

func hookSourceValues() []string {
	return []string{"native", "config", "agent_definition", "skill"}
}

func memoryTypeValues() []string {
	return []string{
		string(memcontract.TypeUser),
		string(memcontract.TypeFeedback),
		string(memcontract.TypeProject),
		string(memcontract.TypeReference),
	}
}

func memoryScopeValues() []string {
	return []string{string(memcontract.ScopeGlobal), string(memcontract.ScopeWorkspace), string(memcontract.ScopeAgent)}
}

func sessionStateValues() []string {
	return []string{
		string(session.StateStarting),
		string(session.StateActive),
		string(session.StateStopping),
		string(session.StateStopped),
	}
}

func stopReasonValues() []string {
	return []string{
		string(store.StopCompleted),
		string(store.StopUserCanceled),
		string(store.StopMaxIterations),
		string(store.StopLoopDetected),
		string(store.StopTimeout),
		string(store.StopBudgetExceeded),
		string(store.StopError),
		string(store.StopAgentCrashed),
		string(store.StopHookStopped),
		string(store.StopShutdown),
	}
}

func toolSourceValues() []string {
	return []string{"builtin", "mcp", "extension", "dynamic"}
}

func shouldAutoEmitNamedType(t reflect.Type) bool {
	if t == nil || t.Name() == "" {
		return false
	}
	if !strings.HasPrefix(t.PkgPath(), "github.com/pedronauck/agh/internal/") {
		return false
	}
	return t.Kind() == reflect.Struct || isEnumType(t) || isPrimitiveAliasType(t)
}

func estimatedOutputSize(blocks []string) int {
	size := len(generatedHeader) + len(generatedImport)
	for idx, block := range blocks {
		size += len(block)
		if !strings.HasSuffix(block, "\n") {
			size++
		}
		if idx < len(blocks)-1 {
			size++
		}
	}
	return size
}

func renderTypeAlias(name string, value string) string {
	var out strings.Builder
	out.Grow(len("export type  = ;\n") + len(name) + len(value))
	out.WriteString("export type ")
	out.WriteString(name)
	out.WriteString(" = ")
	out.WriteString(value)
	out.WriteString(";\n")
	return out.String()
}

func renderInterface(name string, fields []fieldSpec) string {
	var out strings.Builder
	out.Grow(estimatedInterfaceSize(name, fields))
	out.WriteString("export interface ")
	out.WriteString(name)
	out.WriteString(" {\n")
	for _, field := range fields {
		writeFieldSpec(&out, "  ", field, ";\n")
	}
	out.WriteString("}\n")
	return out.String()
}

func renderInlineObject(fields []fieldSpec) string {
	var out strings.Builder
	out.Grow(estimatedInlineObjectSize(fields))
	out.WriteString("{ ")
	for idx, field := range fields {
		if idx > 0 {
			out.WriteString("; ")
		}
		writeFieldSpec(&out, "", field, "")
	}
	out.WriteString(" }")
	return out.String()
}

func writeFieldSpec(out *strings.Builder, prefix string, field fieldSpec, suffix string) {
	out.WriteString(prefix)
	out.WriteString(field.Name)
	if field.Optional {
		out.WriteByte('?')
	}
	out.WriteString(": ")
	out.WriteString(field.Type)
	out.WriteString(suffix)
}

func writeQuotedString(out *strings.Builder, value string) {
	if isSimpleQuotedString(value) {
		out.WriteByte('"')
		out.WriteString(value)
		out.WriteByte('"')
		return
	}
	out.WriteString(strconv.Quote(value))
}

func isSimpleQuotedString(value string) bool {
	if !utf8.ValidString(value) {
		return false
	}
	for _, char := range value {
		if char < ' ' || char == '"' || char == '\\' {
			return false
		}
	}
	return true
}

func estimatedInterfaceSize(name string, fields []fieldSpec) int {
	size := len("export interface  {\n}\n") + len(name)
	for _, field := range fields {
		size += fieldSpecSize("  ", field, ";\n")
	}
	return size
}

func estimatedInlineObjectSize(fields []fieldSpec) int {
	size := len("{  }")
	for idx, field := range fields {
		if idx > 0 {
			size += len("; ")
		}
		size += fieldSpecSize("", field, "")
	}
	return size
}

func fieldSpecSize(prefix string, field fieldSpec, suffix string) int {
	size := len(prefix) + len(field.Name) + len(": ") + len(field.Type) + len(suffix)
	if field.Optional {
		size++
	}
	return size
}

func estimatedEnumUnionSize(values []string) int {
	size := 0
	for idx, value := range values {
		if idx > 0 {
			size += len(" | ")
		}
		size += estimatedQuotedStringSize(value)
	}
	return size
}

func estimatedHookMapSize(header string, specs []extensioncontract.HookContractSpec, payload bool) int {
	size := len(header) + len("}\n")
	for _, spec := range specs {
		typeName := spec.Patch.Name
		if payload {
			typeName = spec.Payload.Name
		}
		size += len("  : ;\n") + estimatedQuotedStringSize(string(spec.Event)) + len(typeName)
	}
	return size
}

func estimatedHostMethodMapSize(specs []extensioncontract.HostAPIMethodSpec) int {
	size := len("export interface HostAPIMethodMap {\n}\n")
	for _, spec := range specs {
		size += len("  : {\n    params: ;\n    result: ;\n  };\n") +
			estimatedQuotedStringSize(string(spec.Method)) +
			estimatedHostParamsTypeSize(spec) +
			estimatedHostResultTypeSize(spec)
	}
	return size
}

func estimatedQuotedStringSize(value string) int {
	return len(value) + len(`""`)
}

func estimatedHostParamsTypeSize(spec extensioncontract.HostAPIMethodSpec) int {
	if !spec.OptionalParams {
		return len(spec.Params.Name)
	}
	if spec.Params.Name == "EmptyResult" {
		return len("undefined")
	}
	return len(spec.Params.Name) + len(" | undefined")
}

func estimatedHostResultTypeSize(spec extensioncontract.HostAPIMethodSpec) int {
	size := len(spec.Result.Name)
	if resultIsList(spec.Result.Value) {
		size += len("[]")
	}
	return size
}
