package sdkts

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
	"time"

	apicontract "github.com/pedronauck/agh/internal/api/contract"
	extensioncontract "github.com/pedronauck/agh/internal/extension/contract"
	extensionprotocol "github.com/pedronauck/agh/internal/extension/protocol"
	"github.com/pedronauck/agh/internal/hooks"
	memcontract "github.com/pedronauck/agh/internal/memory/contract"
	"github.com/pedronauck/agh/internal/session"
	"github.com/pedronauck/agh/internal/store"
	"github.com/pedronauck/agh/internal/tools"
)

var (
	rawMessageType = reflect.TypeFor[json.RawMessage]()
	timeType       = reflect.TypeFor[time.Time]()
	durationType   = reflect.TypeFor[time.Duration]()
)

const (
	jsonValueTypeName = "JSONValue"
	numberTypeName    = "number"
	generatedHeader   = "// Code generated by go run ./cmd/agh-codegen sdk-contracts. DO NOT EDIT.\n"
	generatedImport   = "import type { ISODateTime, JSONValue } from \"../base-types.js\";\n\n"
)

// Generate renders the canonical SDK contracts TypeScript module.
func Generate() (string, error) {
	gen := newGenerator()
	gen.prepare()
	if err := gen.emitAllNamedTypes(); err != nil {
		return "", err
	}
	gen.emitHookMaps()
	gen.emitHostMethodMap()

	var out strings.Builder
	out.Grow(estimatedOutputSize(gen.blocks))
	out.WriteString(generatedHeader)
	out.WriteString(generatedImport)
	for idx, block := range gen.blocks {
		out.WriteString(block)
		if !strings.HasSuffix(block, "\n") {
			out.WriteByte('\n')
		}
		if idx < len(gen.blocks)-1 {
			out.WriteByte('\n')
		}
	}

	return out.String(), nil
}

type generator struct {
	hostSpecs  []extensioncontract.HostAPIMethodSpec
	hookSpecs  []extensioncontract.HookContractSpec
	rootTypes  []extensioncontract.NamedType
	typeNames  map[reflect.Type]string
	queued     map[string]reflect.Type
	emitted    map[string]bool
	processing map[string]bool
	blocks     []string
}

func newGenerator() *generator {
	hostSpecs := extensioncontract.HostAPIMethodSpecs()
	hookSpecs := extensioncontract.HookContracts()
	sdkRootTypes := extensioncontract.SDKRootTypes()

	rootTypes := make(
		[]extensioncontract.NamedType,
		0,
		len(sdkRootTypes)+(len(hostSpecs)*2)+(len(hookSpecs)*2),
	)
	rootTypes = append(rootTypes, sdkRootTypes...)
	for _, spec := range hostSpecs {
		rootTypes = append(rootTypes, spec.Params, spec.Result)
	}
	for _, spec := range hookSpecs {
		rootTypes = append(rootTypes, spec.Payload, spec.Patch)
	}

	return &generator{
		hostSpecs:  hostSpecs,
		hookSpecs:  hookSpecs,
		rootTypes:  rootTypes,
		typeNames:  map[reflect.Type]string{},
		queued:     map[string]reflect.Type{},
		emitted:    map[string]bool{},
		processing: map[string]bool{},
		blocks:     make([]string, 0, len(rootTypes)+3),
	}
}

func (g *generator) prepare() {
	for _, root := range g.rootTypes {
		t := namedBaseType(root.Value)
		if t == nil {
			continue
		}
		if existing, ok := g.typeNames[t]; !ok {
			g.typeNames[t] = root.Name
		} else if existing == root.Name {
			continue
		}
		g.queued[root.Name] = t
	}
}

func namedBaseType(value any) reflect.Type {
	if value == nil {
		return nil
	}
	t := reflect.TypeOf(value)
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t.Kind() == reflect.Slice || t.Kind() == reflect.Array {
		t = t.Elem()
	}
	return t
}

func (g *generator) emitAllNamedTypes() error {
	names := make([]string, 0, len(g.queued))
	for name := range g.queued {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if err := g.ensureNamed(name, g.queued[name]); err != nil {
			return err
		}
	}
	return nil
}

func (g *generator) ensureNamed(name string, t reflect.Type) error {
	if name == "" || t == nil || g.emitted[name] {
		return nil
	}
	if g.processing[name] {
		return nil
	}
	g.processing[name] = true
	defer delete(g.processing, name)

	switch {
	case isEnumType(t):
		g.blocks = append(
			g.blocks,
			fmt.Sprintf("export type %s = %s;\n", name, strings.Join(enumValuesForType(t), " | ")),
		)
	case isPrimitiveAliasType(t):
		g.blocks = append(g.blocks, fmt.Sprintf("export type %s = %s;\n", name, g.primitiveAliasForType(t)))
	case t.Kind() == reflect.Struct:
		fields, err := g.structFields(t)
		if err != nil {
			return err
		}
		if len(fields) == 0 {
			g.blocks = append(g.blocks, fmt.Sprintf("export type %s = Record<string, never>;\n", name))
			break
		}
		var out strings.Builder
		out.WriteString("export interface ")
		out.WriteString(name)
		out.WriteString(" {\n")
		for _, field := range fields {
			out.WriteString("  ")
			out.WriteString(field.Name)
			if field.Optional {
				out.WriteByte('?')
			}
			out.WriteString(": ")
			out.WriteString(field.Type)
			out.WriteString(";\n")
		}
		out.WriteString("}\n")
		g.blocks = append(g.blocks, out.String())
	default:
		tsType, err := g.tsType(t)
		if err != nil {
			return err
		}
		g.blocks = append(g.blocks, fmt.Sprintf("export type %s = %s;\n", name, tsType))
	}

	g.emitted[name] = true
	return nil
}

type fieldSpec struct {
	Name     string
	Type     string
	Optional bool
}

func (g *generator) structFields(t reflect.Type) ([]fieldSpec, error) {
	fields := make([]fieldSpec, 0, t.NumField())
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		if !field.IsExported() {
			continue
		}
		if field.Anonymous && field.Tag.Get("json") == "" {
			embedded := field.Type
			for embedded.Kind() == reflect.Pointer {
				embedded = embedded.Elem()
			}
			if embedded.Kind() == reflect.Struct {
				embeddedFields, err := g.structFields(embedded)
				if err != nil {
					return nil, err
				}
				fields = append(fields, embeddedFields...)
				continue
			}
		}

		jsonName, omitempty := jsonFieldName(field)
		if jsonName == "" {
			continue
		}
		tsType, err := g.tsType(field.Type)
		if err != nil {
			return nil, fmt.Errorf("resolve field %s.%s: %w", t.Name(), field.Name, err)
		}
		fields = append(fields, fieldSpec{
			Name:     jsonName,
			Type:     tsType,
			Optional: omitempty || field.Type.Kind() == reflect.Pointer,
		})
	}
	return fields, nil
}

func jsonFieldName(field reflect.StructField) (string, bool) {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", false
	}
	if tag == "" {
		return field.Name, false
	}
	name, opts, _ := strings.Cut(tag, ",")
	if name == "" {
		name = field.Name
	}
	omitempty := false
	for opts != "" {
		part := opts
		if next, rest, found := strings.Cut(opts, ","); found {
			part = next
			opts = rest
		} else {
			opts = ""
		}
		if part == "omitempty" {
			omitempty = true
			break
		}
	}
	return name, omitempty
}

func (g *generator) tsType(t reflect.Type) (string, error) {
	base := dereferenceType(t)

	if primitive, ok := tsPrimitiveType(base); ok {
		return primitive, nil
	}
	if name, ok, err := g.resolveNamedTSType(base); ok || err != nil {
		return name, err
	}
	return g.tsTypeByKind(base)
}

func dereferenceType(t reflect.Type) reflect.Type {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	return t
}

func tsPrimitiveType(t reflect.Type) (string, bool) {
	switch {
	case t == rawMessageType:
		return jsonValueTypeName, true
	case t == timeType:
		return "ISODateTime", true
	case t == durationType:
		return numberTypeName, true
	case t.Kind() == reflect.Interface:
		return jsonValueTypeName, true
	default:
		return "", false
	}
}

func (g *generator) resolveNamedTSType(t reflect.Type) (string, bool, error) {
	if name, ok := g.typeNames[t]; ok {
		if err := g.ensureNamed(name, t); err != nil {
			return "", true, err
		}
		return name, true, nil
	}
	if shouldAutoEmitNamedType(t) || isEnumType(t) {
		name := t.Name()
		g.typeNames[t] = name
		if shouldAutoEmitNamedType(t) {
			g.queued[name] = t
		}
		if err := g.ensureNamed(name, t); err != nil {
			return "", true, err
		}
		return name, true, nil
	}
	return "", false, nil
}

func (g *generator) tsTypeByKind(t reflect.Type) (string, error) {
	switch t.Kind() {
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return numberTypeName, nil
	case reflect.String:
		return "string", nil
	case reflect.Slice, reflect.Array:
		elemType, err := g.tsType(t.Elem())
		if err != nil {
			return "", err
		}
		return parenthesizeIfNeeded(elemType) + "[]", nil
	case reflect.Map:
		elemType, err := g.tsType(t.Elem())
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("Record<string, %s>", elemType), nil
	case reflect.Struct:
		fields, err := g.structFields(t)
		if err != nil {
			return "", err
		}
		if len(fields) == 0 {
			return "Record<string, never>", nil
		}
		var out strings.Builder
		out.WriteString("{ ")
		for idx, field := range fields {
			if idx > 0 {
				out.WriteString("; ")
			}
			out.WriteString(field.Name)
			if field.Optional {
				out.WriteByte('?')
			}
			out.WriteString(": ")
			out.WriteString(field.Type)
		}
		out.WriteString(" }")
		return out.String(), nil
	default:
		return jsonValueTypeName, nil
	}
}

func (g *generator) primitiveAliasForType(t reflect.Type) string {
	switch t {
	case rawMessageType:
		return "JSONValue"
	case timeType:
		return "ISODateTime"
	case durationType:
		return "number"
	}
	switch t.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	default:
		return "string"
	}
}

func parenthesizeIfNeeded(value string) string {
	if strings.Contains(value, " | ") {
		return "(" + value + ")"
	}
	return value
}

func isPrimitiveAliasType(t reflect.Type) bool {
	if t == rawMessageType || t == timeType || t == durationType {
		return true
	}
	switch t.Kind() {
	case reflect.Bool,
		reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64,
		reflect.String:
		return true
	default:
		return false
	}
}

func isEnumType(t reflect.Type) bool {
	_, ok := enumValuesRegistry[t]
	return ok
}

var enumValuesRegistry = map[reflect.Type][]string{
	reflect.TypeFor[apicontract.AuthoredValidationStatus]():         apicontract.AuthoredValidationStatusValues(),
	reflect.TypeFor[apicontract.AuthoredDiagnosticSeverity]():       apicontract.AuthoredDiagnosticSeverityValues(),
	reflect.TypeFor[apicontract.AgentSoulRevisionAction]():          apicontract.AgentSoulRevisionActionValues(),
	reflect.TypeFor[apicontract.HeartbeatRevisionOperation]():       apicontract.HeartbeatRevisionOperationValues(),
	reflect.TypeFor[apicontract.HeartbeatActorKind]():               apicontract.HeartbeatActorKindValues(),
	reflect.TypeFor[apicontract.SessionHealthState]():               apicontract.SessionHealthStateValues(),
	reflect.TypeFor[apicontract.SessionHealthStatus]():              apicontract.SessionHealthStatusValues(),
	reflect.TypeFor[apicontract.SessionHealthIneligibilityReason](): apicontract.SessionHealthIneligibilityReasonValues(),
	reflect.TypeFor[apicontract.HeartbeatWakeSource]():              apicontract.HeartbeatWakeSourceValues(),
	reflect.TypeFor[apicontract.HeartbeatWakeResult]():              apicontract.HeartbeatWakeResultValues(),
	reflect.TypeFor[apicontract.HeartbeatWakeReason]():              apicontract.HeartbeatWakeReasonValues(),
	reflect.TypeFor[extensionprotocol.HostAPIMethod]():              hostAPIMethodValues(),
	reflect.TypeFor[hooks.HookEvent]():                              hookEventValues(),
	reflect.TypeFor[hooks.HookEventFamily]():                        hookEventFamilyValues(),
	reflect.TypeFor[hooks.HookMode]():                               hookModeValues(),
	reflect.TypeFor[hooks.HookRunOutcome]():                         hookOutcomeValues(),
	reflect.TypeFor[hooks.HookSkillSource]():                        hookSkillSourceValues(),
	reflect.TypeFor[hooks.HookExecutorKind]():                       hookExecutorKindValues(),
	reflect.TypeFor[hooks.HookSource]():                             hookSourceValues(),
	reflect.TypeFor[memcontract.Type]():                             memoryTypeValues(),
	reflect.TypeFor[memcontract.Scope]():                            memoryScopeValues(),
	reflect.TypeFor[session.State]():                                sessionStateValues(),
	reflect.TypeFor[store.StopReason]():                             stopReasonValues(),
	reflect.TypeFor[tools.ToolSource]():                             toolSourceValues(),
}

func enumValuesForType(t reflect.Type) []string {
	values := enumValuesRegistry[t]
	quoted := make([]string, len(values))
	for idx, value := range values {
		quoted[idx] = fmt.Sprintf("%q", value)
	}
	return quoted
}

func (g *generator) emitHookMaps() {
	var payload strings.Builder
	payload.WriteString("export interface HookPayloadByEvent {\n")
	for _, spec := range g.hookSpecs {
		fmt.Fprintf(&payload, "  %q: %s;\n", spec.Event, spec.Payload.Name)
	}
	payload.WriteString("}\n")
	g.blocks = append(g.blocks, payload.String())

	var patch strings.Builder
	patch.WriteString("export interface HookPatchByEvent {\n")
	for _, spec := range g.hookSpecs {
		fmt.Fprintf(&patch, "  %q: %s;\n", spec.Event, spec.Patch.Name)
	}
	patch.WriteString("}\n")
	g.blocks = append(g.blocks, patch.String())
}

func (g *generator) emitHostMethodMap() {
	var out strings.Builder
	out.WriteString("export interface HostAPIMethodMap {\n")
	for _, spec := range g.hostSpecs {
		paramsType := spec.Params.Name
		if spec.OptionalParams {
			if spec.Params.Name == "EmptyResult" {
				paramsType = "undefined"
			} else {
				paramsType += " | undefined"
			}
		}
		resultType := spec.Result.Name
		if resultIsList(spec.Result.Value) {
			resultType += "[]"
		}
		fmt.Fprintf(&out, "  %q: {\n", spec.Method)
		fmt.Fprintf(&out, "    params: %s;\n", paramsType)
		fmt.Fprintf(&out, "    result: %s;\n", resultType)
		out.WriteString("  };\n")
	}
	out.WriteString("}\n")
	g.blocks = append(g.blocks, out.String())
}

func resultIsList(value any) bool {
	if value == nil {
		return false
	}
	t := reflect.TypeOf(value)
	return t.Kind() == reflect.Slice || t.Kind() == reflect.Array
}

func hostAPIMethodValues() []string {
	specs := extensioncontract.HostAPIMethodSpecs()
	values := make([]string, 0, len(specs))
	for _, spec := range specs {
		values = append(values, string(spec.Method))
	}
	sort.Strings(values)
	return values
}

func hookEventValues() []string {
	events := hooks.AllHookEvents()
	values := make([]string, 0, len(events))
	for _, event := range events {
		values = append(values, string(event))
	}
	return values
}

func hookEventFamilyValues() []string {
	return []string{
		string(hooks.HookEventFamilySession),
		string(hooks.HookEventFamilyInput),
		string(hooks.HookEventFamilyPrompt),
		string(hooks.HookEventFamilyEvent),
		string(hooks.HookEventFamilyAgent),
		string(hooks.HookEventFamilyTurn),
		string(hooks.HookEventFamilyMessage),
		string(hooks.HookEventFamilyTool),
		string(hooks.HookEventFamilyPermission),
		string(hooks.HookEventFamilyContext),
	}
}

func hookModeValues() []string {
	return []string{string(hooks.HookModeSync), string(hooks.HookModeAsync)}
}

func hookOutcomeValues() []string {
	return []string{
		string(hooks.HookRunOutcomeApplied),
		string(hooks.HookRunOutcomeDenied),
		string(hooks.HookRunOutcomeFailed),
		string(hooks.HookRunOutcomeSkipped),
		string(hooks.HookRunOutcomeDropped),
		string(hooks.HookRunOutcomeRejected),
	}
}

func hookSkillSourceValues() []string {
	return []string{
		string(hooks.HookSkillSourceBundled),
		string(hooks.HookSkillSourceMarketplace),
		string(hooks.HookSkillSourceUser),
		string(hooks.HookSkillSourceAdditional),
		string(hooks.HookSkillSourceWorkspace),
	}
}

func hookExecutorKindValues() []string {
	return []string{
		string(hooks.HookExecutorNative),
		string(hooks.HookExecutorSubprocess),
		string(hooks.HookExecutorWASM),
	}
}

func hookSourceValues() []string {
	return []string{"native", "config", "agent_definition", "skill"}
}

func memoryTypeValues() []string {
	return []string{
		string(memcontract.TypeUser),
		string(memcontract.TypeFeedback),
		string(memcontract.TypeProject),
		string(memcontract.TypeReference),
	}
}

func memoryScopeValues() []string {
	return []string{string(memcontract.ScopeGlobal), string(memcontract.ScopeWorkspace), string(memcontract.ScopeAgent)}
}

func sessionStateValues() []string {
	return []string{
		string(session.StateStarting),
		string(session.StateActive),
		string(session.StateStopping),
		string(session.StateStopped),
	}
}

func stopReasonValues() []string {
	return []string{
		string(store.StopCompleted),
		string(store.StopUserCanceled),
		string(store.StopMaxIterations),
		string(store.StopLoopDetected),
		string(store.StopTimeout),
		string(store.StopBudgetExceeded),
		string(store.StopError),
		string(store.StopAgentCrashed),
		string(store.StopHookStopped),
		string(store.StopShutdown),
	}
}

func toolSourceValues() []string {
	return []string{"builtin", "mcp", "extension", "dynamic"}
}

func shouldAutoEmitNamedType(t reflect.Type) bool {
	if t == nil || t.Name() == "" {
		return false
	}
	if !strings.HasPrefix(t.PkgPath(), "github.com/pedronauck/agh/internal/") {
		return false
	}
	return t.Kind() == reflect.Struct || isEnumType(t) || isPrimitiveAliasType(t)
}

func estimatedOutputSize(blocks []string) int {
	size := len(generatedHeader) + len(generatedImport)
	for idx, block := range blocks {
		size += len(block)
		if !strings.HasSuffix(block, "\n") {
			size++
		}
		if idx < len(blocks)-1 {
			size++
		}
	}
	return size
}
