package spec

import "github.com/pedronauck/agh/internal/api/contract"

var authoredContextOperationRegistry = []OperationSpec{
	{
		Method:      "GET",
		Path:        "/api/agent/soul",
		OperationID: "getAgentSoul",
		Summary:     "Inspect the resolved Soul read model for the calling agent",
		Tags:        []string{"agent"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.AgentSoulPayload{}},
			{Status: 401, Description: "Agent caller identity is missing", Body: contract.ErrorPayload{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Caller session or agent not found", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Soul is invalid", Body: contract.ErrorPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "POST",
		Path:        "/api/agent/soul/validate",
		OperationID: "validateAgentSoul",
		Summary:     "Validate a proposed Soul body or the calling agent's current Soul",
		Tags:        []string{"agent"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		RequestBody: contract.AgentSoulValidateRequest{},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.AgentSoulPayload{}},
			{Status: 401, Description: "Agent caller identity is missing", Body: contract.ErrorPayload{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Caller session or agent not found", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Soul validation failed", Body: contract.AgentSoulPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "GET",
		Path:        "/api/agents/{agent_name}/soul",
		OperationID: "getAgentDefinitionSoul",
		Summary:     "Inspect the resolved Soul read model for an agent definition",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
			queryParam("workspace_id", "Workspace id", false),
		},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.AgentSoulPayload{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent or workspace not found", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Soul is invalid", Body: contract.ErrorPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "POST",
		Path:        "/api/agents/{agent_name}/soul/validate",
		OperationID: "validateAgentDefinitionSoul",
		Summary:     "Validate a proposed Soul body for an agent definition",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
		},
		RequestBody: contract.AgentSoulValidateRequest{},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.AgentSoulPayload{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent or workspace not found", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Soul validation failed", Body: contract.AgentSoulPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "PUT",
		Path:        "/api/agents/{agent_name}/soul",
		OperationID: "putAgentSoul",
		Summary:     "Create or replace SOUL.md through managed authoring",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
		},
		RequestBody: contract.AgentSoulPutRequest{},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.AgentSoulMutationResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent or workspace not found", Body: contract.ErrorPayload{}},
			{Status: 409, Description: "Soul authoring conflict", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Soul validation failed", Body: contract.AgentSoulPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "DELETE",
		Path:        "/api/agents/{agent_name}/soul",
		OperationID: "deleteAgentSoul",
		Summary:     "Delete SOUL.md through managed authoring",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
		},
		RequestBody: contract.AgentSoulDeleteRequest{},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.AgentSoulMutationResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent, workspace, or Soul file not found", Body: contract.ErrorPayload{}},
			{Status: 409, Description: "Soul authoring conflict", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Invalid Soul delete request", Body: contract.ErrorPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "GET",
		Path:        "/api/agents/{agent_name}/soul/history",
		OperationID: "listAgentSoulHistory",
		Summary:     "List managed SOUL.md authoring revisions",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
			queryParam("workspace_id", "Workspace id", false),
			intQueryParam("limit", "Maximum number of revisions to return"),
			queryParam("cursor", "Revision cursor", false),
		},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.AgentSoulHistoryResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent or workspace not found", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Invalid Soul history request", Body: contract.ErrorPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "POST",
		Path:        "/api/agents/{agent_name}/soul/rollback",
		OperationID: "rollbackAgentSoul",
		Summary:     "Rollback SOUL.md through managed authoring",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
		},
		RequestBody: contract.AgentSoulRollbackRequest{},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.AgentSoulMutationResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent, workspace, or revision not found", Body: contract.ErrorPayload{}},
			{Status: 409, Description: "Soul authoring conflict", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Soul validation failed", Body: contract.AgentSoulPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "POST",
		Path:        "/api/workspaces/{workspace_id}/sessions/{session_id}/soul/refresh",
		OperationID: "refreshSessionSoul",
		Summary:     "Refresh an idle session's Soul snapshot through body-level CAS",
		Tags:        []string{"sessions"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("workspace_id", "Workspace id"),
			pathParam("session_id", "Session id"),
		},
		RequestBody: contract.SessionSoulRefreshRequest{},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.AgentSoulPayload{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Session not found", Body: contract.ErrorPayload{}},
			{Status: 409, Description: "Session is not idle or Soul digest is stale", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Soul validation failed", Body: contract.AgentSoulPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "GET",
		Path:        "/api/agents/{agent_name}/heartbeat",
		OperationID: "getAgentHeartbeat",
		Summary:     "Inspect the resolved Heartbeat policy for an agent definition",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
			queryParam("workspace_id", "Workspace id", false),
		},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.HeartbeatPolicyPayload{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent or workspace not found", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Heartbeat policy is invalid", Body: contract.HeartbeatPolicyPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "POST",
		Path:        "/api/agents/{agent_name}/heartbeat/validate",
		OperationID: "validateAgentHeartbeat",
		Summary:     "Validate a proposed HEARTBEAT.md body",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
		},
		RequestBody: contract.HeartbeatValidateRequest{},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.HeartbeatPolicyPayload{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent or workspace not found", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Heartbeat validation failed", Body: contract.HeartbeatPolicyPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "PUT",
		Path:        "/api/agents/{agent_name}/heartbeat",
		OperationID: "putAgentHeartbeat",
		Summary:     "Create or replace HEARTBEAT.md through managed authoring",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
		},
		RequestBody: contract.HeartbeatPutRequest{},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.HeartbeatMutationResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent or workspace not found", Body: contract.ErrorPayload{}},
			{Status: 409, Description: "Heartbeat authoring conflict", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Heartbeat validation failed", Body: contract.HeartbeatPolicyPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "DELETE",
		Path:        "/api/agents/{agent_name}/heartbeat",
		OperationID: "deleteAgentHeartbeat",
		Summary:     "Delete HEARTBEAT.md through managed authoring",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
		},
		RequestBody: contract.HeartbeatDeleteRequest{},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.HeartbeatMutationResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent, workspace, or policy not found", Body: contract.ErrorPayload{}},
			{Status: 409, Description: "Heartbeat authoring conflict", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Invalid Heartbeat delete request", Body: contract.ErrorPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "GET",
		Path:        "/api/agents/{agent_name}/heartbeat/history",
		OperationID: "listAgentHeartbeatHistory",
		Summary:     "List managed HEARTBEAT.md authoring revisions",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
			queryParam("workspace_id", "Workspace id", false),
			intQueryParam("limit", "Maximum number of revisions to return"),
			queryParam("cursor", "Revision cursor", false),
		},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.HeartbeatHistoryResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent or workspace not found", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Invalid Heartbeat history request", Body: contract.ErrorPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "POST",
		Path:        "/api/agents/{agent_name}/heartbeat/rollback",
		OperationID: "rollbackAgentHeartbeat",
		Summary:     "Rollback HEARTBEAT.md through managed authoring",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
		},
		RequestBody: contract.HeartbeatRollbackRequest{},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.HeartbeatMutationResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{
				Status:      404,
				Description: "Agent, workspace, revision, or snapshot not found",
				Body:        contract.ErrorPayload{},
			},
			{Status: 409, Description: "Heartbeat authoring conflict", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Heartbeat validation failed", Body: contract.HeartbeatPolicyPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "GET",
		Path:        "/api/agents/{agent_name}/heartbeat/status",
		OperationID: "getAgentHeartbeatStatus",
		Summary:     "Read Heartbeat policy status, wake state, and optional session health",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
			queryParam("workspace_id", "Workspace id", false),
			queryParam("session_id", "Session id for wake state and health", false),
			boolQueryParam("include_session_health", "Include session health when a session id is supplied"),
			boolQueryParam("include_recent_wake_events", "Include recent wake audit rows"),
		},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.HeartbeatStatusResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent, workspace, or session not found", Body: contract.ErrorPayload{}},
			{Status: 422, Description: "Heartbeat status request is invalid", Body: contract.ErrorPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "POST",
		Path:        "/api/agents/{agent_name}/heartbeat/wake",
		OperationID: "wakeAgentHeartbeat",
		Summary:     "Request one advisory Heartbeat wake for an eligible session",
		Tags:        []string{"agents"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("agent_name", "Agent name"),
		},
		RequestBody: contract.HeartbeatWakeRequest{},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.HeartbeatWakeResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Agent, workspace, policy, or session not found", Body: contract.ErrorPayload{}},
			{
				Status:      409,
				Description: "Wake skipped or coalesced by policy and health gates",
				Body:        contract.HeartbeatWakeResponse{},
			},
			{Status: 422, Description: "Invalid Heartbeat wake request", Body: contract.ErrorPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "GET",
		Path:        "/api/workspaces/{workspace_id}/sessions/{session_id}/health",
		OperationID: "getSessionHealth",
		Summary:     "Read metadata-only session health and wake eligibility",
		Tags:        []string{"sessions"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("workspace_id", "Workspace id"),
			pathParam("session_id", "Session id"),
		},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.SessionHealthResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Session not found", Body: contract.ErrorPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "GET",
		Path:        "/api/workspaces/{workspace_id}/sessions/{session_id}/status",
		OperationID: "getSessionStatus",
		Summary:     "Read compact session status and wake eligibility",
		Tags:        []string{"sessions"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("workspace_id", "Workspace id"),
			pathParam("session_id", "Session id"),
		},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.SessionStatusResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Session not found", Body: contract.ErrorPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
	{
		Method:      "GET",
		Path:        "/api/workspaces/{workspace_id}/sessions/{session_id}/inspect",
		OperationID: "inspectSession",
		Summary:     "Inspect session health, wake audit, and policy correlation metadata",
		Tags:        []string{"sessions"},
		Transports:  []Transport{TransportHTTP, TransportUDS},
		Parameters: []ParameterSpec{
			pathParam("workspace_id", "Workspace id"),
			pathParam("session_id", "Session id"),
			boolQueryParam("include_recent_wake_events", "Include recent wake audit rows"),
		},
		Responses: []ResponseSpec{
			{Status: 200, Description: "OK", Body: contract.SessionInspectResponse{}},
			{Status: 403, Description: "Forbidden - workspace or permission mismatch", Body: contract.ErrorPayload{}},
			{Status: 404, Description: "Session not found", Body: contract.ErrorPayload{}},
			{Status: 500, Description: "Internal server error", Body: contract.ErrorPayload{}},
		},
	},
}

func authoredContextOperations() []OperationSpec {
	return cloneOperationSpecs(authoredContextOperationRegistry)
}
