package docpost

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestFilenameToCommand(t *testing.T) {
	t.Parallel()

	tests := []struct {
		filename string
		want     string
	}{
		{"agh.md", "agh"},
		{"agh_session.md", "agh session"},
		{"agh_session_list.md", "agh session list"},
		{"agh_daemon_start.md", "agh daemon start"},
	}

	for _, tt := range tests {
		t.Run(tt.filename, func(t *testing.T) {
			t.Parallel()
			got := filenameToCommand(tt.filename)
			if got != tt.want {
				t.Errorf("filenameToCommand(%q) = %q, want %q", tt.filename, got, tt.want)
			}
		})
	}
}

func TestExtractDescription(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		raw  string
		want string
	}{
		{
			name: "standard cobra output",
			raw:  "## agh session list\n\nList all active sessions\n\n### Synopsis\n",
			want: "List all active sessions",
		},
		{
			name: "no description",
			raw:  "## agh\n\n### Synopsis\n",
			want: "",
		},
		{
			name: "multiline before synopsis",
			raw:  "## agh session\n\nManage agent sessions\n\nMore details here\n\n### Synopsis\n",
			want: "Manage agent sessions",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := extractDescription(tt.raw)
			if got != tt.want {
				t.Errorf("extractDescription() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestStripBoilerplate(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		raw  string
		want string
	}{
		{
			name: "removes auto generated footer",
			raw:  "content here\n\n###### Auto generated by spf13/cobra on 1-Jan-2024\n",
			want: "content here\n\n",
		},
		{
			name: "removes SEE ALSO section",
			raw:  "content here\n\n### SEE ALSO\n\n* [agh](agh.md) - parent\n* [agh session list](agh_session_list.md) - child\n",
			want: "content here\n\n",
		},
		{
			name: "removes both",
			raw:  "content here\n\n### SEE ALSO\n\n* [agh](agh.md)\n\n###### Auto generated by spf13/cobra\n",
			want: "content here\n\n",
		},
		{
			name: "no boilerplate",
			raw:  "clean content\n",
			want: "clean content\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := stripBoilerplate(tt.raw)
			if got != tt.want {
				t.Errorf("stripBoilerplate() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestRewriteLinks(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		raw  string
		want string
	}{
		{
			name: "rewrites md link",
			raw:  "* [agh session](agh_session.md) - manage sessions",
			want: "* [agh session](agh_session) - manage sessions",
		},
		{
			name: "rewrites multiple links",
			raw:  "[agh](agh.md) and [agh session](agh_session.md)",
			want: "[agh](agh) and [agh session](agh_session)",
		},
		{
			name: "no links",
			raw:  "plain text here",
			want: "plain text here",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := rewriteLinks(tt.raw)
			if got != tt.want {
				t.Errorf("rewriteLinks() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestTransformMarkdown(t *testing.T) {
	t.Parallel()

	raw := `## agh session list

List all active sessions

### Synopsis

List all sessions currently tracked by the AGH daemon.

` + "```" + `
agh session list [flags]
` + "```" + `

### Options

` + "```" + `
  -h, --help   help for session list
` + "```" + `

### SEE ALSO

* [agh session](agh_session.md) - Manage sessions

###### Auto generated by spf13/cobra on 15-Apr-2026
`

	result := TransformMarkdown(raw, "agh session list")

	// Verify frontmatter is present.
	if !strings.HasPrefix(result, "---\n") {
		t.Error("result should start with YAML frontmatter delimiter")
	}
	if !strings.Contains(result, `title: "agh session list"`) {
		t.Error("frontmatter should contain title")
	}
	if !strings.Contains(result, `description: "List all active sessions"`) {
		t.Error("frontmatter should contain description")
	}

	// Verify boilerplate is stripped.
	if strings.Contains(result, "Auto generated") {
		t.Error("auto-generated footer should be stripped")
	}
	if strings.Contains(result, "### SEE ALSO") {
		t.Error("SEE ALSO section should be stripped")
	}

	// Verify .md links are rewritten.
	if strings.Contains(result, ".md)") {
		t.Error("should not contain .md links")
	}

	// Verify content is preserved.
	if !strings.Contains(result, "### Synopsis") {
		t.Error("synopsis section should be preserved")
	}
	if !strings.Contains(result, "### Options") {
		t.Error("options section should be preserved")
	}
}

func TestEscapeJSX(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		raw  string
		want string
	}{
		{
			name: "escapes angle brackets in text",
			raw:  "Use backoff:<max_retries>:<base_delay> format",
			want: `Use backoff:\<max_retries>:\<base_delay> format`,
		},
		{
			name: "preserves angle brackets in fenced code",
			raw:  "text\n```\nsource <(cmd)\n```\nmore",
			want: "text\n```\nsource <(cmd)\n```\nmore",
		},
		{
			name: "preserves angle brackets in inline code",
			raw:  "Use `<flag>` in your command",
			want: "Use `<flag>` in your command",
		},
		{
			name: "no angle brackets",
			raw:  "plain text",
			want: "plain text",
		},
		{
			name: "process substitution outside fence",
			raw:  "source <(agh completion bash)",
			want: `source \<(agh completion bash)`,
		},
		{
			name: "escapes curly braces in text",
			raw:  `use "${fpath[1]}/_agh" format`,
			want: `use "$\{fpath[1]}/_agh" format`,
		},
		{
			name: "preserves curly braces in inline code",
			raw:  "Use `${fpath[1]}` in your shell",
			want: "Use `${fpath[1]}` in your shell",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := escapeJSX(tt.raw)
			if got != tt.want {
				t.Errorf("escapeJSX() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestTransformMarkdown_NoAbsolutePaths(t *testing.T) {
	t.Parallel()

	raw := `## agh version

Print the AGH version

### Synopsis

Print version info.
`

	result := TransformMarkdown(raw, "agh version")
	if strings.Contains(result, "/Users/") || strings.Contains(result, "/home/") || strings.Contains(result, "/tmp/") {
		t.Error("output should not contain absolute file paths")
	}
}

func TestProcess(t *testing.T) {
	t.Parallel()

	srcDir := t.TempDir()
	dstDir := filepath.Join(t.TempDir(), "output")

	// Write sample Cobra markdown files.
	files := map[string]string{
		"agh.md": `## agh

AGH agent operating system

### Synopsis

AGH is the agent operating system.

###### Auto generated by spf13/cobra on 15-Apr-2026
`,
		"agh_session.md": `## agh session

Manage agent sessions

### Synopsis

Manage agent sessions in AGH.

### SEE ALSO

* [agh](agh.md) - parent

###### Auto generated by spf13/cobra on 15-Apr-2026
`,
	}

	for name, content := range files {
		if err := os.WriteFile(filepath.Join(srcDir, name), []byte(content), 0o644); err != nil {
			t.Fatalf("write test file %s: %v", name, err)
		}
	}

	if err := Process(srcDir, dstDir); err != nil {
		t.Fatalf("Process() error: %v", err)
	}

	// Verify .mdx files exist (not .md).
	for name := range files {
		mdxName := strings.TrimSuffix(name, ".md") + ".mdx"
		mdPath := filepath.Join(dstDir, name)
		mdxPath := filepath.Join(dstDir, mdxName)

		if _, err := os.Stat(mdPath); err == nil {
			t.Errorf("original .md file should not exist in output: %s", mdPath)
		}
		data, err := os.ReadFile(mdxPath)
		if err != nil {
			t.Fatalf("expected .mdx file %s: %v", mdxPath, err)
		}
		if !strings.HasPrefix(string(data), "---\n") {
			t.Errorf("%s should have YAML frontmatter", mdxName)
		}
	}

	// Verify meta.json exists and has correct structure.
	metaData, err := os.ReadFile(filepath.Join(dstDir, "meta.json"))
	if err != nil {
		t.Fatal("meta.json should be generated")
	}

	var meta struct {
		Title string   `json:"title"`
		Pages []string `json:"pages"`
	}
	if err := json.Unmarshal(metaData, &meta); err != nil {
		t.Fatalf("meta.json should be valid JSON: %v", err)
	}

	if meta.Title != "CLI Reference" {
		t.Errorf("meta.Title = %q, want %q", meta.Title, "CLI Reference")
	}
	if len(meta.Pages) != 2 {
		t.Errorf("meta.Pages should have 2 entries, got %d", len(meta.Pages))
	}
}

func TestProcess_CreatesOutputDir(t *testing.T) {
	t.Parallel()

	srcDir := t.TempDir()
	dstDir := filepath.Join(t.TempDir(), "nested", "deep", "output")

	// Write a minimal .md file so Process has something to work on.
	content := "## agh\n\nAGH agent OS\n"
	if err := os.WriteFile(filepath.Join(srcDir, "agh.md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := Process(srcDir, dstDir); err != nil {
		t.Fatalf("Process() should create output dir: %v", err)
	}

	if _, err := os.Stat(dstDir); os.IsNotExist(err) {
		t.Error("output directory should have been created")
	}
}
