package openapits

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestGenerate(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	artifact := Artifact{
		SpecPath:   filepath.Join(dir, "spec.json"),
		OutputPath: filepath.Join(dir, "generated", "types.d.ts"),
	}
	writeTestSpec(t, artifact.SpecPath)

	if err := Generate(context.Background(), artifact); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content, err := os.ReadFile(artifact.OutputPath)
	if err != nil {
		t.Fatalf("os.ReadFile(%q) error = %v", artifact.OutputPath, err)
	}

	generated := string(content)
	if !strings.Contains(generated, "This file was auto-generated by openapi-typescript.") {
		t.Fatalf("generated output missing openapi-typescript header: %s", generated)
	}
	if !strings.Contains(generated, `"/api/example"`) {
		t.Fatalf("generated output missing expected path entry: %s", generated)
	}
	if !strings.Contains(generated, "getExample") {
		t.Fatalf("generated output missing expected operation id: %s", generated)
	}
}

func TestCheck(t *testing.T) {
	t.Parallel()

	t.Run("accepts matching generated output", func(t *testing.T) {
		t.Parallel()

		dir := t.TempDir()
		artifact := Artifact{
			SpecPath:   filepath.Join(dir, "spec.json"),
			OutputPath: filepath.Join(dir, "types.d.ts"),
		}
		writeTestSpec(t, artifact.SpecPath)

		if err := Generate(context.Background(), artifact); err != nil {
			t.Fatalf("Generate() error = %v", err)
		}

		if err := Check(context.Background(), artifact); err != nil {
			t.Fatalf("Check() error = %v", err)
		}
	})

	t.Run("rejects stale generated output", func(t *testing.T) {
		t.Parallel()

		dir := t.TempDir()
		artifact := Artifact{
			SpecPath:   filepath.Join(dir, "spec.json"),
			OutputPath: filepath.Join(dir, "types.d.ts"),
		}
		writeTestSpec(t, artifact.SpecPath)

		if err := Generate(context.Background(), artifact); err != nil {
			t.Fatalf("Generate() error = %v", err)
		}
		if err := os.WriteFile(artifact.OutputPath, []byte("export type Broken = true;\n"), 0o644); err != nil {
			t.Fatalf("os.WriteFile(%q) error = %v", artifact.OutputPath, err)
		}

		err := Check(context.Background(), artifact)
		if !errors.Is(err, ErrStaleGeneratedFile) {
			t.Fatalf("Check() error = %v, want ErrStaleGeneratedFile", err)
		}
	})

	t.Run("rejects missing generated output", func(t *testing.T) {
		t.Parallel()

		dir := t.TempDir()
		artifact := Artifact{
			SpecPath:   filepath.Join(dir, "spec.json"),
			OutputPath: filepath.Join(dir, "missing.d.ts"),
		}
		writeTestSpec(t, artifact.SpecPath)

		err := Check(context.Background(), artifact)
		if err == nil {
			t.Fatal("Check() error = nil, want missing output error")
		}
		if !strings.Contains(err.Error(), "is missing; run codegen") {
			t.Fatalf("Check() error = %v, want missing output guidance", err)
		}
	})
}

func TestCheckGeneratedFile(t *testing.T) {
	t.Run("accepts matching generated output", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "types.d.ts")
		want := []byte("export interface Status { ready: boolean; }\n")
		if err := os.WriteFile(path, want, 0o644); err != nil {
			t.Fatalf("os.WriteFile(%q) error = %v", path, err)
		}

		if err := checkGeneratedFile(path, want); err != nil {
			t.Fatalf("checkGeneratedFile() error = %v", err)
		}
	})

	t.Run("rejects stale generated output", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "types.d.ts")
		if err := os.WriteFile(path, []byte("export interface Status { ready: false; }\n"), 0o644); err != nil {
			t.Fatalf("os.WriteFile(%q) error = %v", path, err)
		}

		err := checkGeneratedFile(path, []byte("export interface Status { ready: true; }\n"))
		if !errors.Is(err, ErrStaleGeneratedFile) {
			t.Fatalf("checkGeneratedFile() error = %v, want ErrStaleGeneratedFile", err)
		}
	})

	t.Run("rejects missing generated output", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "missing.d.ts")
		err := checkGeneratedFile(path, []byte("export interface Status { ready: true; }\n"))
		if err == nil {
			t.Fatal("checkGeneratedFile() error = nil, want missing output error")
		}
		if !strings.Contains(err.Error(), "is missing; run codegen") {
			t.Fatalf("checkGeneratedFile() error = %v, want missing output guidance", err)
		}
	})
}

func TestRunCommand(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("shell-based command tests differ on windows")
	}

	t.Run("succeeds for zero exit status", func(t *testing.T) {
		t.Parallel()

		script := writeExecutableScript(t, "#!/bin/sh\nexit 0\n")
		if err := runCommand(context.Background(), script); err != nil {
			t.Fatalf("runCommand() error = %v", err)
		}
	})

	t.Run("prefers stderr details", func(t *testing.T) {
		t.Parallel()

		script := writeExecutableScript(t, "#!/bin/sh\necho 'stderr detail' >&2\nexit 1\n")
		err := runCommand(context.Background(), script)
		if err == nil {
			t.Fatal("runCommand() error = nil, want non-nil")
		}
		if !strings.Contains(err.Error(), "stderr detail") {
			t.Fatalf("runCommand() error = %v, want stderr detail", err)
		}
	})

	t.Run("falls back to stdout details", func(t *testing.T) {
		t.Parallel()

		script := writeExecutableScript(t, "#!/bin/sh\necho 'stdout detail'\nexit 1\n")
		err := runCommand(context.Background(), script)
		if err == nil {
			t.Fatal("runCommand() error = nil, want non-nil")
		}
		if !strings.Contains(err.Error(), "stdout detail") {
			t.Fatalf("runCommand() error = %v, want stdout detail", err)
		}
	})

	t.Run("reports raw execution errors when the command cannot start", func(t *testing.T) {
		t.Parallel()

		err := runCommand(context.Background(), filepath.Join(t.TempDir(), "missing-command"))
		if err == nil {
			t.Fatal("runCommand() error = nil, want non-nil")
		}
		if !strings.Contains(err.Error(), "missing-command") {
			t.Fatalf("runCommand() error = %v, want command name in message", err)
		}
	})
}

func writeTestSpec(t *testing.T, path string) {
	t.Helper()

	spec := `{
  "openapi": "3.0.3",
  "info": {
    "title": "OpenAPI TS Test",
    "version": "1.0.0"
  },
  "paths": {
    "/api/example": {
      "get": {
        "operationId": "getExample",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": ["status"],
                  "properties": {
                    "status": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
`

	if err := os.WriteFile(path, []byte(spec), 0o644); err != nil {
		t.Fatalf("os.WriteFile(%q) error = %v", path, err)
	}
}

func writeExecutableScript(t *testing.T, content string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "script.sh")
	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		t.Fatalf("os.WriteFile(%q) error = %v", path, err)
	}
	return path
}
