package openapits

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestGenerate(t *testing.T) {
	t.Parallel()

	t.Run("Should generate formatted type definitions from the spec", func(t *testing.T) {
		t.Parallel()

		dir := t.TempDir()
		artifact := Artifact{
			SpecPath:   filepath.Join(dir, "spec.json"),
			OutputPath: filepath.Join(dir, "generated", "types.d.ts"),
		}
		writeTestSpec(t, artifact.SpecPath)

		if err := Generate(context.Background(), artifact); err != nil {
			t.Fatalf("Generate() error = %v", err)
		}

		content, err := os.ReadFile(artifact.OutputPath)
		if err != nil {
			t.Fatalf("os.ReadFile(%q) error = %v", artifact.OutputPath, err)
		}

		generated := string(content)
		if !strings.Contains(generated, "This file was auto-generated by openapi-typescript.") {
			t.Fatalf("generated output missing openapi-typescript header: %s", generated)
		}
		if !strings.Contains(generated, `"/api/example"`) {
			t.Fatalf("generated output missing expected path entry: %s", generated)
		}
		if !strings.Contains(generated, "getExample") {
			t.Fatalf("generated output missing expected operation id: %s", generated)
		}
	})

	t.Run("Should reject invalid artifacts before running generators", func(t *testing.T) {
		t.Parallel()

		for _, tc := range []struct {
			name     string
			artifact Artifact
		}{
			{
				name:     "Should reject missing spec path",
				artifact: Artifact{OutputPath: filepath.Join(t.TempDir(), "types.d.ts")},
			},
			{
				name:     "Should reject missing output path",
				artifact: Artifact{SpecPath: filepath.Join(t.TempDir(), "spec.json")},
			},
			{
				name: "Should reject matching spec and output paths",
				artifact: func() Artifact {
					path := filepath.Join(t.TempDir(), "spec.json")
					return Artifact{SpecPath: path, OutputPath: path}
				}(),
			},
		} {
			t.Run(tc.name, func(t *testing.T) {
				t.Parallel()

				err := Generate(context.Background(), tc.artifact)
				if !errors.Is(err, ErrInvalidArtifact) {
					t.Fatalf("Generate() error = %v, want ErrInvalidArtifact", err)
				}
			})
		}
	})

	t.Run("Should publish output only after formatting succeeds", func(t *testing.T) {
		t.Parallel()

		dir := t.TempDir()
		artifact := Artifact{
			SpecPath:   filepath.Join(dir, "spec.json"),
			OutputPath: filepath.Join(dir, "types.d.ts"),
		}
		if err := os.WriteFile(artifact.OutputPath, []byte("stable output\n"), 0o600); err != nil {
			t.Fatalf("os.WriteFile(%q) error = %v", artifact.OutputPath, err)
		}
		formatErr := errors.New("format failed")
		runner := commandRunnerFunc(func(_ context.Context, _ string, args ...string) error {
			switch args[0] {
			case "openapi-typescript":
				outputPath := args[len(args)-1]
				if err := os.WriteFile(outputPath, []byte("generated output\n"), 0o600); err != nil {
					return fmt.Errorf("write generated output: %w", err)
				}
				return nil
			case "oxfmt":
				return formatErr
			default:
				return fmt.Errorf("unexpected command args: %v", args)
			}
		})

		err := generateWithRunner(context.Background(), artifact, runner)
		if !errors.Is(err, formatErr) {
			t.Fatalf("generateWithRunner() error = %v, want formatErr", err)
		}
		content, err := os.ReadFile(artifact.OutputPath)
		if err != nil {
			t.Fatalf("os.ReadFile(%q) error = %v", artifact.OutputPath, err)
		}
		if string(content) != "stable output\n" {
			t.Fatalf("output content = %q, want stable output", string(content))
		}
		assertNoTemporaryOutputs(t, dir)
	})

	t.Run("Should publish formatted output after the pipeline succeeds", func(t *testing.T) {
		t.Parallel()

		dir := t.TempDir()
		artifact := Artifact{
			SpecPath:   filepath.Join(dir, "spec.json"),
			OutputPath: filepath.Join(dir, "types.d.ts"),
		}
		runner := commandRunnerFunc(func(_ context.Context, _ string, args ...string) error {
			outputPath := args[len(args)-1]
			switch args[0] {
			case "openapi-typescript":
				if err := os.WriteFile(outputPath, []byte("generated output\n"), 0o600); err != nil {
					return fmt.Errorf("write generated output: %w", err)
				}
				return nil
			case "oxfmt":
				if err := os.WriteFile(outputPath, []byte("formatted output\n"), 0o600); err != nil {
					return fmt.Errorf("write formatted output: %w", err)
				}
				return nil
			default:
				return fmt.Errorf("unexpected command args: %v", args)
			}
		})

		if err := generateWithRunner(context.Background(), artifact, runner); err != nil {
			t.Fatalf("generateWithRunner() error = %v", err)
		}
		content, err := os.ReadFile(artifact.OutputPath)
		if err != nil {
			t.Fatalf("os.ReadFile(%q) error = %v", artifact.OutputPath, err)
		}
		if string(content) != "formatted output\n" {
			t.Fatalf("output content = %q, want formatted output", string(content))
		}
		assertNoTemporaryOutputs(t, dir)
	})
}

func TestCheck(t *testing.T) {
	t.Parallel()

	t.Run("Should reject invalid artifacts before regenerating output", func(t *testing.T) {
		t.Parallel()

		err := Check(context.Background(), Artifact{})
		if !errors.Is(err, ErrInvalidArtifact) {
			t.Fatalf("Check() error = %v, want ErrInvalidArtifact", err)
		}
	})

	t.Run("Should accept matching generated output", func(t *testing.T) {
		t.Parallel()

		dir := t.TempDir()
		artifact := Artifact{
			SpecPath:   filepath.Join(dir, "spec.json"),
			OutputPath: filepath.Join(dir, "types.d.ts"),
		}
		writeTestSpec(t, artifact.SpecPath)

		if err := Generate(context.Background(), artifact); err != nil {
			t.Fatalf("Generate() error = %v", err)
		}

		if err := Check(context.Background(), artifact); err != nil {
			t.Fatalf("Check() error = %v", err)
		}
	})

	t.Run("Should reject stale generated output", func(t *testing.T) {
		t.Parallel()

		dir := t.TempDir()
		artifact := Artifact{
			SpecPath:   filepath.Join(dir, "spec.json"),
			OutputPath: filepath.Join(dir, "types.d.ts"),
		}
		writeTestSpec(t, artifact.SpecPath)

		if err := Generate(context.Background(), artifact); err != nil {
			t.Fatalf("Generate() error = %v", err)
		}
		if err := os.WriteFile(artifact.OutputPath, []byte("export type Broken = true;\n"), 0o644); err != nil {
			t.Fatalf("os.WriteFile(%q) error = %v", artifact.OutputPath, err)
		}

		err := Check(context.Background(), artifact)
		if !errors.Is(err, ErrStaleGeneratedFile) {
			t.Fatalf("Check() error = %v, want ErrStaleGeneratedFile", err)
		}
	})

	t.Run("Should reject missing generated output", func(t *testing.T) {
		t.Parallel()

		dir := t.TempDir()
		artifact := Artifact{
			SpecPath:   filepath.Join(dir, "spec.json"),
			OutputPath: filepath.Join(dir, "missing.d.ts"),
		}
		writeTestSpec(t, artifact.SpecPath)

		err := Check(context.Background(), artifact)
		if err == nil {
			t.Fatal("Check() error = nil, want missing output error")
		}
		if !errors.Is(err, ErrMissingGeneratedFile) {
			t.Fatalf("Check() error = %v, want ErrMissingGeneratedFile", err)
		}
	})
}

func TestCheckGeneratedFile(t *testing.T) {
	t.Run("Should accept matching generated output", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "types.d.ts")
		want := []byte("export interface Status { ready: boolean; }\n")
		if err := os.WriteFile(path, want, 0o644); err != nil {
			t.Fatalf("os.WriteFile(%q) error = %v", path, err)
		}

		if err := checkGeneratedFile(path, want); err != nil {
			t.Fatalf("checkGeneratedFile() error = %v", err)
		}
	})

	t.Run("Should reject stale generated output", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "types.d.ts")
		if err := os.WriteFile(path, []byte("export interface Status { ready: false; }\n"), 0o644); err != nil {
			t.Fatalf("os.WriteFile(%q) error = %v", path, err)
		}

		err := checkGeneratedFile(path, []byte("export interface Status { ready: true; }\n"))
		if !errors.Is(err, ErrStaleGeneratedFile) {
			t.Fatalf("checkGeneratedFile() error = %v, want ErrStaleGeneratedFile", err)
		}
	})

	t.Run("Should reject missing generated output", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "missing.d.ts")
		err := checkGeneratedFile(path, []byte("export interface Status { ready: true; }\n"))
		if err == nil {
			t.Fatal("checkGeneratedFile() error = nil, want missing output error")
		}
		if !errors.Is(err, ErrMissingGeneratedFile) {
			t.Fatalf("checkGeneratedFile() error = %v, want ErrMissingGeneratedFile", err)
		}
	})
}

func TestRunCommand(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("shell-based command tests differ on windows")
	}

	t.Run("Should succeed for zero exit status", func(t *testing.T) {
		t.Parallel()

		script := writeExecutableScript(t, "#!/bin/sh\nexit 0\n")
		if err := runCommand(context.Background(), script); err != nil {
			t.Fatalf("runCommand() error = %v", err)
		}
	})

	t.Run("Should prefer stderr details", func(t *testing.T) {
		t.Parallel()

		script := writeExecutableScript(t, "#!/bin/sh\necho 'stderr detail' >&2\nexit 1\n")
		err := runCommand(context.Background(), script)
		if err == nil {
			t.Fatal("runCommand() error = nil, want non-nil")
		}
		if !strings.Contains(err.Error(), "stderr detail") {
			t.Fatalf("runCommand() error = %v, want stderr detail", err)
		}
	})

	t.Run("Should fall back to stdout details", func(t *testing.T) {
		t.Parallel()

		script := writeExecutableScript(t, "#!/bin/sh\necho 'stdout detail'\nexit 1\n")
		err := runCommand(context.Background(), script)
		if err == nil {
			t.Fatal("runCommand() error = nil, want non-nil")
		}
		if !strings.Contains(err.Error(), "stdout detail") {
			t.Fatalf("runCommand() error = %v, want stdout detail", err)
		}
	})

	t.Run("Should report raw execution errors when the command cannot start", func(t *testing.T) {
		t.Parallel()

		err := runCommand(context.Background(), filepath.Join(t.TempDir(), "missing-command"))
		if err == nil {
			t.Fatal("runCommand() error = nil, want non-nil")
		}
		if !strings.Contains(err.Error(), "missing-command") {
			t.Fatalf("runCommand() error = %v, want command name in message", err)
		}
	})

	t.Run("Should preserve context cancellation", func(t *testing.T) {
		t.Parallel()

		script := writeExecutableScript(t, "#!/bin/sh\nsleep 1\n")
		ctx, cancel := context.WithCancel(context.Background())
		cancel()

		err := runCommand(ctx, script)
		if !errors.Is(err, context.Canceled) {
			t.Fatalf("runCommand() error = %v, want context.Canceled", err)
		}
	})
}

func writeTestSpec(t *testing.T, path string) {
	t.Helper()

	spec := `{
  "openapi": "3.0.3",
  "info": {
    "title": "OpenAPI TS Test",
    "version": "1.0.0"
  },
  "paths": {
    "/api/example": {
      "get": {
        "operationId": "getExample",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": ["status"],
                  "properties": {
                    "status": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
`

	if err := os.WriteFile(path, []byte(spec), 0o644); err != nil {
		t.Fatalf("os.WriteFile(%q) error = %v", path, err)
	}
}

func writeExecutableScript(t *testing.T, content string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "script.sh")
	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		t.Fatalf("os.WriteFile(%q) error = %v", path, err)
	}
	return path
}

type commandRunnerFunc func(context.Context, string, ...string) error

func (fn commandRunnerFunc) Run(ctx context.Context, name string, args ...string) error {
	return fn(ctx, name, args...)
}

func assertNoTemporaryOutputs(t *testing.T, dir string) {
	t.Helper()

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("os.ReadDir(%q) error = %v", dir, err)
	}
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), ".openapi-types-") {
			t.Fatalf("temporary output %q was not removed", entry.Name())
		}
	}
}
