// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: network_preferences.sql

package sqlcgen

import (
	"context"
)

const deleteNetworkSubscription = `-- name: DeleteNetworkSubscription :exec
DELETE FROM network_subscriptions
WHERE workspace_id = ?1
  AND channel = ?2
  AND thread_id = ?3
  AND peer_id = ?4
`

type DeleteNetworkSubscriptionParams struct {
	WorkspaceID string `json:"workspace_id"`
	Channel     string `json:"channel"`
	ThreadID    string `json:"thread_id"`
	PeerID      string `json:"peer_id"`
}

func (q *Queries) DeleteNetworkSubscription(ctx context.Context, arg DeleteNetworkSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteNetworkSubscription,
		arg.WorkspaceID,
		arg.Channel,
		arg.ThreadID,
		arg.PeerID,
	)
	return err
}

const getNetworkDeliveryGuidanceState = `-- name: GetNetworkDeliveryGuidanceState :one
SELECT session_id, reply_guidance_delivered, protocol_guidance_delivered, created_at, updated_at
FROM network_delivery_guidance_state
WHERE session_id = ?1
`

func (q *Queries) GetNetworkDeliveryGuidanceState(ctx context.Context, sessionID string) (NetworkDeliveryGuidanceState, error) {
	row := q.db.QueryRowContext(ctx, getNetworkDeliveryGuidanceState, sessionID)
	var i NetworkDeliveryGuidanceState
	err := row.Scan(
		&i.SessionID,
		&i.ReplyGuidanceDelivered,
		&i.ProtocolGuidanceDelivered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNetworkDeliveryGuidanceState = `-- name: UpsertNetworkDeliveryGuidanceState :exec
INSERT INTO network_delivery_guidance_state (
  session_id, reply_guidance_delivered, protocol_guidance_delivered, created_at, updated_at
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5
)
ON CONFLICT(session_id) DO UPDATE SET
  reply_guidance_delivered = excluded.reply_guidance_delivered,
  protocol_guidance_delivered = excluded.protocol_guidance_delivered,
  updated_at = excluded.updated_at
`

type UpsertNetworkDeliveryGuidanceStateParams struct {
	SessionID                 string `json:"session_id"`
	ReplyGuidanceDelivered    bool   `json:"reply_guidance_delivered"`
	ProtocolGuidanceDelivered bool   `json:"protocol_guidance_delivered"`
	CreatedAt                 string `json:"created_at"`
	UpdatedAt                 string `json:"updated_at"`
}

func (q *Queries) UpsertNetworkDeliveryGuidanceState(ctx context.Context, arg UpsertNetworkDeliveryGuidanceStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertNetworkDeliveryGuidanceState,
		arg.SessionID,
		arg.ReplyGuidanceDelivered,
		arg.ProtocolGuidanceDelivered,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertNetworkSubscription = `-- name: UpsertNetworkSubscription :exec
INSERT INTO network_subscriptions (
  workspace_id, channel, thread_id, peer_id, mode, keyword_filters_json, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8
)
ON CONFLICT(workspace_id, channel, thread_id, peer_id) DO UPDATE SET
  mode = excluded.mode,
  keyword_filters_json = excluded.keyword_filters_json,
  updated_at = excluded.updated_at
`

type UpsertNetworkSubscriptionParams struct {
	WorkspaceID        string `json:"workspace_id"`
	Channel            string `json:"channel"`
	ThreadID           string `json:"thread_id"`
	PeerID             string `json:"peer_id"`
	Mode               string `json:"mode"`
	KeywordFiltersJson string `json:"keyword_filters_json"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
}

func (q *Queries) UpsertNetworkSubscription(ctx context.Context, arg UpsertNetworkSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertNetworkSubscription,
		arg.WorkspaceID,
		arg.Channel,
		arg.ThreadID,
		arg.PeerID,
		arg.Mode,
		arg.KeywordFiltersJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertNetworkTaskThreadOrigin = `-- name: UpsertNetworkTaskThreadOrigin :exec
INSERT INTO network_task_thread_origins (
  task_id, workspace_id, channel, thread_id, origin_message_id, digest,
  source_message_ids_json, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9
)
ON CONFLICT(task_id) DO UPDATE SET
  workspace_id = excluded.workspace_id,
  channel = excluded.channel,
  thread_id = excluded.thread_id,
  origin_message_id = excluded.origin_message_id,
  digest = excluded.digest,
  source_message_ids_json = excluded.source_message_ids_json,
  updated_at = excluded.updated_at
`

type UpsertNetworkTaskThreadOriginParams struct {
	TaskID               string `json:"task_id"`
	WorkspaceID          string `json:"workspace_id"`
	Channel              string `json:"channel"`
	ThreadID             string `json:"thread_id"`
	OriginMessageID      string `json:"origin_message_id"`
	Digest               string `json:"digest"`
	SourceMessageIdsJson string `json:"source_message_ids_json"`
	CreatedAt            string `json:"created_at"`
	UpdatedAt            string `json:"updated_at"`
}

func (q *Queries) UpsertNetworkTaskThreadOrigin(ctx context.Context, arg UpsertNetworkTaskThreadOriginParams) error {
	_, err := q.db.ExecContext(ctx, upsertNetworkTaskThreadOrigin,
		arg.TaskID,
		arg.WorkspaceID,
		arg.Channel,
		arg.ThreadID,
		arg.OriginMessageID,
		arg.Digest,
		arg.SourceMessageIdsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertTaskDesignationRollup = `-- name: UpsertTaskDesignationRollup :exec
INSERT INTO task_designation_rollups (
  designation_group_id, task_id, summary_json, created_at
) VALUES (
  ?1, ?2, ?3, ?4
)
ON CONFLICT(designation_group_id) DO UPDATE SET
  task_id = excluded.task_id,
  summary_json = excluded.summary_json,
  created_at = excluded.created_at
`

type UpsertTaskDesignationRollupParams struct {
	DesignationGroupID string `json:"designation_group_id"`
	TaskID             string `json:"task_id"`
	SummaryJson        string `json:"summary_json"`
	CreatedAt          string `json:"created_at"`
}

func (q *Queries) UpsertTaskDesignationRollup(ctx context.Context, arg UpsertTaskDesignationRollupParams) error {
	_, err := q.db.ExecContext(ctx, upsertTaskDesignationRollup,
		arg.DesignationGroupID,
		arg.TaskID,
		arg.SummaryJson,
		arg.CreatedAt,
	)
	return err
}
