// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: network_coordination_invitations.sql

package sqlcgen

import (
	"context"
)

const deleteNetworkCoordinationInvitation = `-- name: DeleteNetworkCoordinationInvitation :exec
DELETE FROM network_coordination_invitations
WHERE scope_kind = ?1 AND scope_id = ?2
`

type DeleteNetworkCoordinationInvitationParams struct {
	ScopeKind string `json:"scope_kind"`
	ScopeID   string `json:"scope_id"`
}

func (q *Queries) DeleteNetworkCoordinationInvitation(ctx context.Context, arg DeleteNetworkCoordinationInvitationParams) error {
	_, err := q.db.ExecContext(ctx, deleteNetworkCoordinationInvitation, arg.ScopeKind, arg.ScopeID)
	return err
}

const getNetworkCoordinationInvitation = `-- name: GetNetworkCoordinationInvitation :one
SELECT scope_kind, scope_id, dismissed_at, dismissed_by
FROM network_coordination_invitations
WHERE scope_kind = ?1 AND scope_id = ?2
`

type GetNetworkCoordinationInvitationParams struct {
	ScopeKind string `json:"scope_kind"`
	ScopeID   string `json:"scope_id"`
}

func (q *Queries) GetNetworkCoordinationInvitation(ctx context.Context, arg GetNetworkCoordinationInvitationParams) (NetworkCoordinationInvitation, error) {
	row := q.db.QueryRowContext(ctx, getNetworkCoordinationInvitation, arg.ScopeKind, arg.ScopeID)
	var i NetworkCoordinationInvitation
	err := row.Scan(
		&i.ScopeKind,
		&i.ScopeID,
		&i.DismissedAt,
		&i.DismissedBy,
	)
	return i, err
}

const upsertNetworkCoordinationInvitation = `-- name: UpsertNetworkCoordinationInvitation :one
INSERT INTO network_coordination_invitations (
  scope_kind,
  scope_id,
  dismissed_at,
  dismissed_by
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4
)
ON CONFLICT(scope_kind, scope_id) DO UPDATE SET
  dismissed_at = excluded.dismissed_at,
  dismissed_by = excluded.dismissed_by
RETURNING scope_kind, scope_id, dismissed_at, dismissed_by
`

type UpsertNetworkCoordinationInvitationParams struct {
	ScopeKind   string `json:"scope_kind"`
	ScopeID     string `json:"scope_id"`
	DismissedAt string `json:"dismissed_at"`
	DismissedBy string `json:"dismissed_by"`
}

func (q *Queries) UpsertNetworkCoordinationInvitation(ctx context.Context, arg UpsertNetworkCoordinationInvitationParams) (NetworkCoordinationInvitation, error) {
	row := q.db.QueryRowContext(ctx, upsertNetworkCoordinationInvitation,
		arg.ScopeKind,
		arg.ScopeID,
		arg.DismissedAt,
		arg.DismissedBy,
	)
	var i NetworkCoordinationInvitation
	err := row.Scan(
		&i.ScopeKind,
		&i.ScopeID,
		&i.DismissedAt,
		&i.DismissedBy,
	)
	return i, err
}
