// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observe_overview.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countEventSummariesByHourWeekday = `-- name: CountEventSummariesByHourWeekday :many
SELECT CAST(strftime('%w', timestamp, 'localtime') AS INTEGER) AS weekday,
  CAST(strftime('%H', timestamp, 'localtime') AS INTEGER) AS hour,
  COUNT(1) AS events
FROM event_summaries
WHERE timestamp >= ?1
  AND (?2 = '' OR workspace_id = ?2)
GROUP BY weekday, hour
ORDER BY weekday, hour
`

type CountEventSummariesByHourWeekdayParams struct {
	Since       string `json:"since"`
	WorkspaceID any    `json:"workspace_id"`
}

type CountEventSummariesByHourWeekdayRow struct {
	Weekday int64 `json:"weekday"`
	Hour    int64 `json:"hour"`
	Events  int64 `json:"events"`
}

func (q *Queries) CountEventSummariesByHourWeekday(ctx context.Context, arg CountEventSummariesByHourWeekdayParams) ([]CountEventSummariesByHourWeekdayRow, error) {
	rows, err := q.db.QueryContext(ctx, countEventSummariesByHourWeekday, arg.Since, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventSummariesByHourWeekdayRow{}
	for rows.Next() {
		var i CountEventSummariesByHourWeekdayRow
		if err := rows.Scan(&i.Weekday, &i.Hour, &i.Events); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countHookDispatchSince = `-- name: CountHookDispatchSince :one
SELECT COUNT(1) AS runs,
  SUM(CASE WHEN outcome = 'failure' THEN 1 ELSE 0 END) AS failures
FROM event_summaries
WHERE type = 'hook.dispatch.complete'
  AND timestamp >= ?1
  AND (?2 = '' OR workspace_id = ?2)
`

type CountHookDispatchSinceParams struct {
	Since       string `json:"since"`
	WorkspaceID any    `json:"workspace_id"`
}

type CountHookDispatchSinceRow struct {
	Runs     int64           `json:"runs"`
	Failures sql.NullFloat64 `json:"failures"`
}

func (q *Queries) CountHookDispatchSince(ctx context.Context, arg CountHookDispatchSinceParams) (CountHookDispatchSinceRow, error) {
	row := q.db.QueryRowContext(ctx, countHookDispatchSince, arg.Since, arg.WorkspaceID)
	var i CountHookDispatchSinceRow
	err := row.Scan(&i.Runs, &i.Failures)
	return i, err
}

const countNetworkAuditSince = `-- name: CountNetworkAuditSince :one
SELECT COUNT(1) AS messages
FROM network_audit_log
WHERE timestamp >= ?1
  AND (?2 = '' OR workspace_id = ?2)
`

type CountNetworkAuditSinceParams struct {
	Since       string `json:"since"`
	WorkspaceID any    `json:"workspace_id"`
}

func (q *Queries) CountNetworkAuditSince(ctx context.Context, arg CountNetworkAuditSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNetworkAuditSince, arg.Since, arg.WorkspaceID)
	var messages int64
	err := row.Scan(&messages)
	return messages, err
}

const countTaskRunOutcomesByDay = `-- name: CountTaskRunOutcomesByDay :many
SELECT date(ended_at, 'localtime') AS day,
  SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS completed,
  SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) AS failed,
  SUM(CASE WHEN status = 'canceled' THEN 1 ELSE 0 END) AS canceled
FROM task_runs
WHERE ended_at IS NOT NULL
  AND ended_at >= ?1
  AND status IN ('completed', 'failed', 'canceled')
  AND run_kind = 'worker'
  AND (?2 = '' OR COALESCE(workspace_id, '') = ?2)
GROUP BY date(ended_at, 'localtime')
ORDER BY day
`

type CountTaskRunOutcomesByDayParams struct {
	Since       sql.NullString `json:"since"`
	WorkspaceID any            `json:"workspace_id"`
}

type CountTaskRunOutcomesByDayRow struct {
	Day       any             `json:"day"`
	Completed sql.NullFloat64 `json:"completed"`
	Failed    sql.NullFloat64 `json:"failed"`
	Canceled  sql.NullFloat64 `json:"canceled"`
}

func (q *Queries) CountTaskRunOutcomesByDay(ctx context.Context, arg CountTaskRunOutcomesByDayParams) ([]CountTaskRunOutcomesByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, countTaskRunOutcomesByDay, arg.Since, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTaskRunOutcomesByDayRow{}
	for rows.Next() {
		var i CountTaskRunOutcomesByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.Completed,
			&i.Failed,
			&i.Canceled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTasksClosedByDay = `-- name: CountTasksClosedByDay :many
SELECT date(closed_at, 'localtime') AS day, COUNT(1) AS closed
FROM tasks
WHERE closed_at IS NOT NULL
  AND closed_at >= ?1
  AND status = 'completed'
  AND (?2 = '' OR COALESCE(workspace_id, '') = ?2)
GROUP BY date(closed_at, 'localtime')
ORDER BY day
`

type CountTasksClosedByDayParams struct {
	Since       sql.NullString `json:"since"`
	WorkspaceID any            `json:"workspace_id"`
}

type CountTasksClosedByDayRow struct {
	Day    any   `json:"day"`
	Closed int64 `json:"closed"`
}

func (q *Queries) CountTasksClosedByDay(ctx context.Context, arg CountTasksClosedByDayParams) ([]CountTasksClosedByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, countTasksClosedByDay, arg.Since, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTasksClosedByDayRow{}
	for rows.Next() {
		var i CountTasksClosedByDayRow
		if err := rows.Scan(&i.Day, &i.Closed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTokenUsageDailyBefore = `-- name: DeleteTokenUsageDailyBefore :execrows
DELETE FROM token_usage_daily WHERE day < ?1
`

func (q *Queries) DeleteTokenUsageDailyBefore(ctx context.Context, cutoffDay string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTokenUsageDailyBefore, cutoffDay)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTokenUsageDailyByAgent = `-- name: ListTokenUsageDailyByAgent :many
SELECT agent_name,
  SUM(total_tokens) AS total_tokens
FROM token_usage_daily
WHERE day >= ?1
  AND (?2 = '' OR workspace_id = ?2)
GROUP BY agent_name
ORDER BY SUM(total_tokens) DESC, agent_name
`

type ListTokenUsageDailyByAgentParams struct {
	SinceDay    string `json:"since_day"`
	WorkspaceID any    `json:"workspace_id"`
}

type ListTokenUsageDailyByAgentRow struct {
	AgentName   string          `json:"agent_name"`
	TotalTokens sql.NullFloat64 `json:"total_tokens"`
}

func (q *Queries) ListTokenUsageDailyByAgent(ctx context.Context, arg ListTokenUsageDailyByAgentParams) ([]ListTokenUsageDailyByAgentRow, error) {
	rows, err := q.db.QueryContext(ctx, listTokenUsageDailyByAgent, arg.SinceDay, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenUsageDailyByAgentRow{}
	for rows.Next() {
		var i ListTokenUsageDailyByAgentRow
		if err := rows.Scan(&i.AgentName, &i.TotalTokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenUsageDailyByDay = `-- name: ListTokenUsageDailyByDay :many
SELECT day,
  SUM(input_tokens) AS input_tokens,
  SUM(output_tokens) AS output_tokens,
  SUM(total_tokens) AS total_tokens
FROM token_usage_daily
WHERE day >= ?1
  AND (?2 = '' OR workspace_id = ?2)
GROUP BY day
ORDER BY day
`

type ListTokenUsageDailyByDayParams struct {
	SinceDay    string `json:"since_day"`
	WorkspaceID any    `json:"workspace_id"`
}

type ListTokenUsageDailyByDayRow struct {
	Day          string          `json:"day"`
	InputTokens  sql.NullFloat64 `json:"input_tokens"`
	OutputTokens sql.NullFloat64 `json:"output_tokens"`
	TotalTokens  sql.NullFloat64 `json:"total_tokens"`
}

func (q *Queries) ListTokenUsageDailyByDay(ctx context.Context, arg ListTokenUsageDailyByDayParams) ([]ListTokenUsageDailyByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, listTokenUsageDailyByDay, arg.SinceDay, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenUsageDailyByDayRow{}
	for rows.Next() {
		var i ListTokenUsageDailyByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const longestUserSessionSince = `-- name: LongestUserSessionSince :many
SELECT id, agent_name, created_at,
  MAX(0, CAST(strftime('%s', CASE WHEN state = 'active' THEN ?1 ELSE updated_at END) AS INTEGER) -
    CAST(strftime('%s', created_at) AS INTEGER)) AS runtime_seconds
FROM sessions
WHERE session_type = 'user'
  AND created_at >= ?2
  AND (?3 = '' OR workspace_id = ?3)
ORDER BY runtime_seconds DESC, created_at DESC
LIMIT 1
`

type LongestUserSessionSinceParams struct {
	Now         any    `json:"now"`
	Since       string `json:"since"`
	WorkspaceID any    `json:"workspace_id"`
}

type LongestUserSessionSinceRow struct {
	ID             string `json:"id"`
	AgentName      string `json:"agent_name"`
	CreatedAt      string `json:"created_at"`
	RuntimeSeconds any    `json:"runtime_seconds"`
}

func (q *Queries) LongestUserSessionSince(ctx context.Context, arg LongestUserSessionSinceParams) ([]LongestUserSessionSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, longestUserSessionSince, arg.Now, arg.Since, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LongestUserSessionSinceRow{}
	for rows.Next() {
		var i LongestUserSessionSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentName,
			&i.CreatedAt,
			&i.RuntimeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxEventSummaryTimestamp = `-- name: MaxEventSummaryTimestamp :one
SELECT COALESCE(MAX(timestamp), '') AS latest
FROM event_summaries
WHERE (?1 = '' OR workspace_id = ?1)
`

func (q *Queries) MaxEventSummaryTimestamp(ctx context.Context, workspaceID any) (any, error) {
	row := q.db.QueryRowContext(ctx, maxEventSummaryTimestamp, workspaceID)
	var latest any
	err := row.Scan(&latest)
	return latest, err
}

const sumTokenUsageDailyCost = `-- name: SumTokenUsageDailyCost :many
SELECT cost_status, cost_source, COALESCE(cost_currency, '') AS cost_currency,
  SUM(COALESCE(total_cost, 0)) AS total_cost,
  SUM(CASE WHEN total_cost IS NULL THEN 1 ELSE 0 END) AS rows_without_cost,
  COUNT(1) AS rows_total
FROM token_usage_daily
WHERE day >= ?1
  AND (?2 = '' OR workspace_id = ?2)
GROUP BY cost_status, cost_source, COALESCE(cost_currency, '')
`

type SumTokenUsageDailyCostParams struct {
	SinceDay    string `json:"since_day"`
	WorkspaceID any    `json:"workspace_id"`
}

type SumTokenUsageDailyCostRow struct {
	CostStatus      string          `json:"cost_status"`
	CostSource      string          `json:"cost_source"`
	CostCurrency    string          `json:"cost_currency"`
	TotalCost       sql.NullFloat64 `json:"total_cost"`
	RowsWithoutCost sql.NullFloat64 `json:"rows_without_cost"`
	RowsTotal       int64           `json:"rows_total"`
}

func (q *Queries) SumTokenUsageDailyCost(ctx context.Context, arg SumTokenUsageDailyCostParams) ([]SumTokenUsageDailyCostRow, error) {
	rows, err := q.db.QueryContext(ctx, sumTokenUsageDailyCost, arg.SinceDay, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumTokenUsageDailyCostRow{}
	for rows.Next() {
		var i SumTokenUsageDailyCostRow
		if err := rows.Scan(
			&i.CostStatus,
			&i.CostSource,
			&i.CostCurrency,
			&i.TotalCost,
			&i.RowsWithoutCost,
			&i.RowsTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTokenUsageDaily = `-- name: UpsertTokenUsageDaily :exec
INSERT INTO token_usage_daily (
  day, workspace_id, agent_name, input_tokens, output_tokens, total_tokens,
  total_cost, cost_currency, cost_status, cost_source, turn_count, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10,
  ?11, ?12
)
ON CONFLICT(day, workspace_id, agent_name) DO UPDATE SET
  input_tokens = token_usage_daily.input_tokens + excluded.input_tokens,
  output_tokens = token_usage_daily.output_tokens + excluded.output_tokens,
  total_tokens = token_usage_daily.total_tokens + excluded.total_tokens,
  total_cost = CASE
    WHEN token_usage_daily.cost_status != excluded.cost_status
      OR token_usage_daily.cost_source != excluded.cost_source
      OR COALESCE(token_usage_daily.cost_currency, '') != COALESCE(excluded.cost_currency, '')
      THEN NULL
    WHEN excluded.total_cost IS NULL THEN token_usage_daily.total_cost
    WHEN token_usage_daily.total_cost IS NULL THEN excluded.total_cost
    ELSE token_usage_daily.total_cost + excluded.total_cost
  END,
  cost_currency = CASE
    WHEN token_usage_daily.cost_status != excluded.cost_status
      OR token_usage_daily.cost_source != excluded.cost_source
      OR COALESCE(token_usage_daily.cost_currency, '') != COALESCE(excluded.cost_currency, '')
      THEN NULL
    ELSE COALESCE(excluded.cost_currency, token_usage_daily.cost_currency)
  END,
  cost_status = CASE
    WHEN token_usage_daily.cost_status != excluded.cost_status
      OR token_usage_daily.cost_source != excluded.cost_source
      OR COALESCE(token_usage_daily.cost_currency, '') != COALESCE(excluded.cost_currency, '')
      THEN 'unknown'
    ELSE token_usage_daily.cost_status
  END,
  cost_source = CASE
    WHEN token_usage_daily.cost_status != excluded.cost_status
      OR token_usage_daily.cost_source != excluded.cost_source
      OR COALESCE(token_usage_daily.cost_currency, '') != COALESCE(excluded.cost_currency, '')
      THEN 'none'
    ELSE token_usage_daily.cost_source
  END,
  turn_count = token_usage_daily.turn_count + excluded.turn_count,
  updated_at = excluded.updated_at
`

type UpsertTokenUsageDailyParams struct {
	Day          string          `json:"day"`
	WorkspaceID  string          `json:"workspace_id"`
	AgentName    string          `json:"agent_name"`
	InputTokens  int64           `json:"input_tokens"`
	OutputTokens int64           `json:"output_tokens"`
	TotalTokens  int64           `json:"total_tokens"`
	TotalCost    sql.NullFloat64 `json:"total_cost"`
	CostCurrency sql.NullString  `json:"cost_currency"`
	CostStatus   string          `json:"cost_status"`
	CostSource   string          `json:"cost_source"`
	TurnCount    int64           `json:"turn_count"`
	UpdatedAt    string          `json:"updated_at"`
}

func (q *Queries) UpsertTokenUsageDaily(ctx context.Context, arg UpsertTokenUsageDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertTokenUsageDaily,
		arg.Day,
		arg.WorkspaceID,
		arg.AgentName,
		arg.InputTokens,
		arg.OutputTokens,
		arg.TotalTokens,
		arg.TotalCost,
		arg.CostCurrency,
		arg.CostStatus,
		arg.CostSource,
		arg.TurnCount,
		arg.UpdatedAt,
	)
	return err
}
