// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_claim.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const claimTaskRun = `-- name: ClaimTaskRun :execrows
UPDATE task_runs
SET status = ?1,
    claimed_by_kind = ?2,
    claimed_by_ref = ?3,
    session_id = ?4,
    claim_token = ?5,
    claim_token_hash = ?6,
    lease_until = ?7,
    heartbeat_at = ?8,
    claimed_at = ?9,
    started_at = NULL,
    ended_at = NULL,
    error = NULL,
    metadata_json = ?10,
    result_json = NULL
WHERE id = ?11 AND status = ?12
`

type ClaimTaskRunParams struct {
	ClaimedStatus  string         `json:"claimed_status"`
	ClaimedByKind  sql.NullString `json:"claimed_by_kind"`
	ClaimedByRef   sql.NullString `json:"claimed_by_ref"`
	SessionID      sql.NullString `json:"session_id"`
	ClaimToken     sql.NullString `json:"claim_token"`
	ClaimTokenHash sql.NullString `json:"claim_token_hash"`
	LeaseUntil     sql.NullString `json:"lease_until"`
	HeartbeatAt    sql.NullString `json:"heartbeat_at"`
	ClaimedAt      sql.NullString `json:"claimed_at"`
	MetadataJson   sql.NullString `json:"metadata_json"`
	ID             string         `json:"id"`
	QueuedStatus   string         `json:"queued_status"`
}

func (q *Queries) ClaimTaskRun(ctx context.Context, arg ClaimTaskRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimTaskRun,
		arg.ClaimedStatus,
		arg.ClaimedByKind,
		arg.ClaimedByRef,
		arg.SessionID,
		arg.ClaimToken,
		arg.ClaimTokenHash,
		arg.LeaseUntil,
		arg.HeartbeatAt,
		arg.ClaimedAt,
		arg.MetadataJson,
		arg.ID,
		arg.QueuedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeTaskRunLease = `-- name: CompleteTaskRunLease :execrows
UPDATE task_runs
SET status = ?1, lease_until = NULL, heartbeat_at = NULL, claim_token = NULL,
    ended_at = ?2, tokens_used = ?3, error = NULL,
    result_json = ?4
WHERE id = ?5 AND claim_token_hash = ?6
`

type CompleteTaskRunLeaseParams struct {
	Status         string         `json:"status"`
	EndedAt        sql.NullString `json:"ended_at"`
	TokensUsed     int64          `json:"tokens_used"`
	ResultJson     sql.NullString `json:"result_json"`
	ID             string         `json:"id"`
	ClaimTokenHash sql.NullString `json:"claim_token_hash"`
}

func (q *Queries) CompleteTaskRunLease(ctx context.Context, arg CompleteTaskRunLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeTaskRunLease,
		arg.Status,
		arg.EndedAt,
		arg.TokensUsed,
		arg.ResultJson,
		arg.ID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completionCreatedTaskClaimExists = `-- name: CompletionCreatedTaskClaimExists :one
SELECT EXISTS(
  SELECT 1 FROM tasks
  WHERE id = ?1
    AND COALESCE(workspace_id, '') = ?2
    AND created_by_kind = ?3
    AND created_by_ref = ?4
)
`

type CompletionCreatedTaskClaimExistsParams struct {
	ID            string         `json:"id"`
	WorkspaceID   sql.NullString `json:"workspace_id"`
	CreatedByKind string         `json:"created_by_kind"`
	CreatedByRef  string         `json:"created_by_ref"`
}

func (q *Queries) CompletionCreatedTaskClaimExists(ctx context.Context, arg CompletionCreatedTaskClaimExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, completionCreatedTaskClaimExists,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatedByKind,
		arg.CreatedByRef,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countActiveTaskRunLeasesForSession = `-- name: CountActiveTaskRunLeasesForSession :one
SELECT COUNT(1)
FROM task_runs
WHERE session_id = ?1
  AND status IN (?2, ?3, ?4)
  AND (lease_until IS NULL OR lease_until > ?5)
`

type CountActiveTaskRunLeasesForSessionParams struct {
	SessionID      sql.NullString `json:"session_id"`
	ClaimedStatus  string         `json:"claimed_status"`
	StartingStatus string         `json:"starting_status"`
	RunningStatus  string         `json:"running_status"`
	Now            sql.NullString `json:"now"`
}

func (q *Queries) CountActiveTaskRunLeasesForSession(ctx context.Context, arg CountActiveTaskRunLeasesForSessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTaskRunLeasesForSession,
		arg.SessionID,
		arg.ClaimedStatus,
		arg.StartingStatus,
		arg.RunningStatus,
		arg.Now,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failTaskRunLease = `-- name: FailTaskRunLease :execrows
UPDATE task_runs
SET status = ?1, lease_until = NULL, heartbeat_at = NULL, claim_token = NULL,
    ended_at = ?2, tokens_used = ?3, error = ?4,
    result_json = NULL
WHERE id = ?5 AND claim_token_hash = ?6
`

type FailTaskRunLeaseParams struct {
	Status         string         `json:"status"`
	EndedAt        sql.NullString `json:"ended_at"`
	TokensUsed     int64          `json:"tokens_used"`
	Error          sql.NullString `json:"error"`
	ID             string         `json:"id"`
	ClaimTokenHash sql.NullString `json:"claim_token_hash"`
}

func (q *Queries) FailTaskRunLease(ctx context.Context, arg FailTaskRunLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failTaskRunLease,
		arg.Status,
		arg.EndedAt,
		arg.TokensUsed,
		arg.Error,
		arg.ID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLoopRunWorkspaceID = `-- name: GetLoopRunWorkspaceID :one
SELECT workspace_id FROM loop_runs WHERE id = ?1
`

func (q *Queries) GetLoopRunWorkspaceID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLoopRunWorkspaceID, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getNetworkChannelForTask = `-- name: GetNetworkChannelForTask :one
SELECT channel, workspace_id, purpose, fanout_policy,
       COALESCE(coordinator_peer_id, '') AS coordinator_peer_id,
       COALESCE(created_by, '') AS created_by,
       created_at, updated_at
FROM network_channels
WHERE channel = ?1
`

type GetNetworkChannelForTaskRow struct {
	Channel           string `json:"channel"`
	WorkspaceID       string `json:"workspace_id"`
	Purpose           string `json:"purpose"`
	FanoutPolicy      string `json:"fanout_policy"`
	CoordinatorPeerID string `json:"coordinator_peer_id"`
	CreatedBy         string `json:"created_by"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

func (q *Queries) GetNetworkChannelForTask(ctx context.Context, channel string) (GetNetworkChannelForTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getNetworkChannelForTask, channel)
	var i GetNetworkChannelForTaskRow
	err := row.Scan(
		&i.Channel,
		&i.WorkspaceID,
		&i.Purpose,
		&i.FanoutPolicy,
		&i.CoordinatorPeerID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskRunMetadataForClaim = `-- name: GetTaskRunMetadataForClaim :one
SELECT metadata_json FROM task_runs WHERE id = ?1
`

func (q *Queries) GetTaskRunMetadataForClaim(ctx context.Context, id string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTaskRunMetadataForClaim, id)
	var metadata_json sql.NullString
	err := row.Scan(&metadata_json)
	return metadata_json, err
}

const heartbeatTaskRunLease = `-- name: HeartbeatTaskRunLease :execrows
UPDATE task_runs
SET lease_until = ?1,
    heartbeat_at = ?2,
    claim_token = ?3,
    tokens_used = CASE WHEN ?4 > tokens_used THEN ?4 ELSE tokens_used END
WHERE id = ?5
  AND claim_token_hash = ?6
  AND status IN (?7, ?8, ?9)
`

type HeartbeatTaskRunLeaseParams struct {
	LeaseUntil     sql.NullString `json:"lease_until"`
	HeartbeatAt    sql.NullString `json:"heartbeat_at"`
	ClaimToken     sql.NullString `json:"claim_token"`
	TokensUsed     int64          `json:"tokens_used"`
	ID             string         `json:"id"`
	ClaimTokenHash sql.NullString `json:"claim_token_hash"`
	ClaimedStatus  string         `json:"claimed_status"`
	StartingStatus string         `json:"starting_status"`
	RunningStatus  string         `json:"running_status"`
}

func (q *Queries) HeartbeatTaskRunLease(ctx context.Context, arg HeartbeatTaskRunLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatTaskRunLease,
		arg.LeaseUntil,
		arg.HeartbeatAt,
		arg.ClaimToken,
		arg.TokensUsed,
		arg.ID,
		arg.ClaimTokenHash,
		arg.ClaimedStatus,
		arg.StartingStatus,
		arg.RunningStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertNetworkChannelForTask = `-- name: InsertNetworkChannelForTask :exec
INSERT INTO network_channels (
  channel, workspace_id, purpose, created_by, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6
)
`

type InsertNetworkChannelForTaskParams struct {
	Channel     string         `json:"channel"`
	WorkspaceID string         `json:"workspace_id"`
	Purpose     string         `json:"purpose"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) InsertNetworkChannelForTask(ctx context.Context, arg InsertNetworkChannelForTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertNetworkChannelForTask,
		arg.Channel,
		arg.WorkspaceID,
		arg.Purpose,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAutonomyLeaseHandles = `-- name: ListAutonomyLeaseHandles :many
SELECT tr.id, tr.task_id, COALESCE(t.workspace_id, '') AS workspace_id, tr.status,
       COALESCE(tr.session_id, '') AS session_id, tr.claimed_by_kind, tr.claimed_by_ref,
       COALESCE(tr.claim_token, '') AS claim_token, COALESCE(tr.claim_token_hash, '') AS claim_token_hash,
       tr.lease_until, tr.heartbeat_at
FROM task_runs tr
JOIN tasks t ON t.id = tr.task_id
WHERE tr.session_id = ?1
  AND COALESCE(tr.claim_token_hash, '') <> ''
ORDER BY COALESCE(tr.lease_until, '') DESC, tr.id ASC
`

type ListAutonomyLeaseHandlesRow struct {
	ID             string         `json:"id"`
	TaskID         string         `json:"task_id"`
	WorkspaceID    string         `json:"workspace_id"`
	Status         string         `json:"status"`
	SessionID      string         `json:"session_id"`
	ClaimedByKind  sql.NullString `json:"claimed_by_kind"`
	ClaimedByRef   sql.NullString `json:"claimed_by_ref"`
	ClaimToken     string         `json:"claim_token"`
	ClaimTokenHash string         `json:"claim_token_hash"`
	LeaseUntil     sql.NullString `json:"lease_until"`
	HeartbeatAt    sql.NullString `json:"heartbeat_at"`
}

func (q *Queries) ListAutonomyLeaseHandles(ctx context.Context, sessionID sql.NullString) ([]ListAutonomyLeaseHandlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAutonomyLeaseHandles, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAutonomyLeaseHandlesRow{}
	for rows.Next() {
		var i ListAutonomyLeaseHandlesRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.WorkspaceID,
			&i.Status,
			&i.SessionID,
			&i.ClaimedByKind,
			&i.ClaimedByRef,
			&i.ClaimToken,
			&i.ClaimTokenHash,
			&i.LeaseUntil,
			&i.HeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredTaskRunLeaseIDs = `-- name: ListExpiredTaskRunLeaseIDs :many
SELECT id
FROM task_runs
WHERE status IN (?1, ?2, ?3)
  AND lease_until IS NOT NULL
  AND lease_until <= ?4
ORDER BY lease_until ASC, id ASC
LIMIT ?5
`

type ListExpiredTaskRunLeaseIDsParams struct {
	ClaimedStatus  string         `json:"claimed_status"`
	StartingStatus string         `json:"starting_status"`
	RunningStatus  string         `json:"running_status"`
	Now            sql.NullString `json:"now"`
	ResultLimit    int64          `json:"result_limit"`
}

func (q *Queries) ListExpiredTaskRunLeaseIDs(ctx context.Context, arg ListExpiredTaskRunLeaseIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredTaskRunLeaseIDs,
		arg.ClaimedStatus,
		arg.StartingStatus,
		arg.RunningStatus,
		arg.Now,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueExpiredTaskRunLease = `-- name: RequeueExpiredTaskRunLease :execrows
UPDATE task_runs
SET status = ?1, claimed_by_kind = NULL, claimed_by_ref = NULL, session_id = NULL,
    claim_token = NULL, claim_token_hash = NULL, lease_until = NULL, heartbeat_at = NULL,
    claimed_at = NULL, started_at = NULL, ended_at = NULL, error = NULL, result_json = NULL
WHERE id = ?2
  AND status = ?3
  AND COALESCE(session_id, '') = ?4
  AND claim_token_hash = ?5
  AND lease_until = ?6
`

type RequeueExpiredTaskRunLeaseParams struct {
	QueuedStatus   string         `json:"queued_status"`
	ID             string         `json:"id"`
	PreviousStatus string         `json:"previous_status"`
	SessionID      sql.NullString `json:"session_id"`
	ClaimTokenHash sql.NullString `json:"claim_token_hash"`
	LeaseUntil     sql.NullString `json:"lease_until"`
}

func (q *Queries) RequeueExpiredTaskRunLease(ctx context.Context, arg RequeueExpiredTaskRunLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueExpiredTaskRunLease,
		arg.QueuedStatus,
		arg.ID,
		arg.PreviousStatus,
		arg.SessionID,
		arg.ClaimTokenHash,
		arg.LeaseUntil,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueTaskRunLease = `-- name: RequeueTaskRunLease :execrows
UPDATE task_runs
SET status = ?1, claimed_by_kind = NULL, claimed_by_ref = NULL, session_id = NULL,
    claim_token = NULL, claim_token_hash = NULL, lease_until = NULL, heartbeat_at = NULL,
    claimed_at = NULL, started_at = NULL, ended_at = NULL, error = NULL, result_json = NULL
WHERE id = ?2
`

type RequeueTaskRunLeaseParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) RequeueTaskRunLease(ctx context.Context, arg RequeueTaskRunLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueTaskRunLease, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLoopGenerationOutputForTaskRun = `-- name: UpdateLoopGenerationOutputForTaskRun :execrows
UPDATE loop_generation_outputs
SET status = ?1,
    output_ref = CASE
      WHEN CAST(?2 AS TEXT) = '' THEN output_ref
      ELSE CAST(?2 AS TEXT)
    END,
    task_run_id = ?3
WHERE loop_run_id = ?4 AND task_run_id = ?3
`

type UpdateLoopGenerationOutputForTaskRunParams struct {
	Status    string         `json:"status"`
	OutputRef string         `json:"output_ref"`
	TaskRunID sql.NullString `json:"task_run_id"`
	LoopRunID string         `json:"loop_run_id"`
}

func (q *Queries) UpdateLoopGenerationOutputForTaskRun(ctx context.Context, arg UpdateLoopGenerationOutputForTaskRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLoopGenerationOutputForTaskRun,
		arg.Status,
		arg.OutputRef,
		arg.TaskRunID,
		arg.LoopRunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLoopRunNodeTerminal = `-- name: UpdateLoopRunNodeTerminal :execrows
UPDATE loop_runs
SET last_progress_at = CASE
      WHEN last_progress_at < CAST(?1 AS TEXT) THEN CAST(?1 AS TEXT)
      ELSE last_progress_at
    END,
    consecutive_failures = CASE
      WHEN CAST(?2 AS INTEGER) = 1 THEN consecutive_failures + 1
      ELSE 0
    END
WHERE id = ?3
`

type UpdateLoopRunNodeTerminalParams struct {
	TerminalAt   string `json:"terminal_at"`
	FailureDelta int64  `json:"failure_delta"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateLoopRunNodeTerminal(ctx context.Context, arg UpdateLoopRunNodeTerminalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLoopRunNodeTerminal, arg.TerminalAt, arg.FailureDelta, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertLoopGenerationOutputForTaskRun = `-- name: UpsertLoopGenerationOutputForTaskRun :exec
INSERT INTO loop_generation_outputs (
  loop_run_id, generation, node_id, item_index, status, output_ref, task_run_id
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7
)
ON CONFLICT(loop_run_id, generation, node_id, item_index) DO UPDATE SET
  status = excluded.status,
  output_ref = excluded.output_ref,
  task_run_id = excluded.task_run_id
`

type UpsertLoopGenerationOutputForTaskRunParams struct {
	LoopRunID  string         `json:"loop_run_id"`
	Generation int64          `json:"generation"`
	NodeID     string         `json:"node_id"`
	ItemIndex  int64          `json:"item_index"`
	Status     string         `json:"status"`
	OutputRef  sql.NullString `json:"output_ref"`
	TaskRunID  sql.NullString `json:"task_run_id"`
}

func (q *Queries) UpsertLoopGenerationOutputForTaskRun(ctx context.Context, arg UpsertLoopGenerationOutputForTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, upsertLoopGenerationOutputForTaskRun,
		arg.LoopRunID,
		arg.Generation,
		arg.NodeID,
		arg.ItemIndex,
		arg.Status,
		arg.OutputRef,
		arg.TaskRunID,
	)
	return err
}
