// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_force.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const forceUpdateTaskRunSnapshot = `-- name: ForceUpdateTaskRunSnapshot :execrows
UPDATE task_runs
SET task_id = ?1,
    status = ?2,
    attempt = ?3,
    previous_run_id = ?4,
    failure_kind = ?5,
    claimed_by_kind = ?6,
    claimed_by_ref = ?7,
    session_id = ?8,
    origin_kind = ?9,
    origin_ref = ?10,
    idempotency_key = ?11,
    network_channel = ?12,
    claim_token = NULL,
    claim_token_hash = ?13,
    lease_until = ?14,
    heartbeat_at = ?15,
    coordination_channel_id = ?16,
    queued_at = ?17,
    claimed_at = ?18,
    started_at = ?19,
    ended_at = ?20,
    error = ?21,
    metadata_json = ?22,
    result_json = ?23,
    review_required = ?24,
    review_request_round = ?25,
    review_policy_snapshot = ?26,
    review_request_id = ?27,
    parent_run_id = ?28,
    review_id = ?29,
    review_round = ?30,
    continuation_reason = ?31,
    missing_work_json = ?32,
    next_round_guidance = ?33
WHERE id = ?34
  AND status = ?35
  AND COALESCE(session_id, '') = ?36
  AND COALESCE(claim_token_hash, '') = ?37
  AND COALESCE(lease_until, '') = ?38
`

type ForceUpdateTaskRunSnapshotParams struct {
	TaskID                 string         `json:"task_id"`
	Status                 string         `json:"status"`
	Attempt                int64          `json:"attempt"`
	PreviousRunID          sql.NullString `json:"previous_run_id"`
	FailureKind            string         `json:"failure_kind"`
	ClaimedByKind          sql.NullString `json:"claimed_by_kind"`
	ClaimedByRef           sql.NullString `json:"claimed_by_ref"`
	SessionID              sql.NullString `json:"session_id"`
	OriginKind             string         `json:"origin_kind"`
	OriginRef              string         `json:"origin_ref"`
	IdempotencyKey         sql.NullString `json:"idempotency_key"`
	NetworkChannel         sql.NullString `json:"network_channel"`
	ClaimTokenHash         sql.NullString `json:"claim_token_hash"`
	LeaseUntil             sql.NullString `json:"lease_until"`
	HeartbeatAt            sql.NullString `json:"heartbeat_at"`
	CoordinationChannelID  sql.NullString `json:"coordination_channel_id"`
	QueuedAt               string         `json:"queued_at"`
	ClaimedAt              sql.NullString `json:"claimed_at"`
	StartedAt              sql.NullString `json:"started_at"`
	EndedAt                sql.NullString `json:"ended_at"`
	Error                  sql.NullString `json:"error"`
	MetadataJson           sql.NullString `json:"metadata_json"`
	ResultJson             sql.NullString `json:"result_json"`
	ReviewRequired         bool           `json:"review_required"`
	ReviewRequestRound     int64          `json:"review_request_round"`
	ReviewPolicySnapshot   string         `json:"review_policy_snapshot"`
	ReviewRequestID        sql.NullString `json:"review_request_id"`
	ParentRunID            sql.NullString `json:"parent_run_id"`
	ReviewID               sql.NullString `json:"review_id"`
	ReviewRound            int64          `json:"review_round"`
	ContinuationReason     string         `json:"continuation_reason"`
	MissingWorkJson        string         `json:"missing_work_json"`
	NextRoundGuidance      string         `json:"next_round_guidance"`
	ID                     string         `json:"id"`
	PreviousStatus         string         `json:"previous_status"`
	PreviousSessionID      sql.NullString `json:"previous_session_id"`
	PreviousClaimTokenHash sql.NullString `json:"previous_claim_token_hash"`
	PreviousLeaseUntil     sql.NullString `json:"previous_lease_until"`
}

func (q *Queries) ForceUpdateTaskRunSnapshot(ctx context.Context, arg ForceUpdateTaskRunSnapshotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, forceUpdateTaskRunSnapshot,
		arg.TaskID,
		arg.Status,
		arg.Attempt,
		arg.PreviousRunID,
		arg.FailureKind,
		arg.ClaimedByKind,
		arg.ClaimedByRef,
		arg.SessionID,
		arg.OriginKind,
		arg.OriginRef,
		arg.IdempotencyKey,
		arg.NetworkChannel,
		arg.ClaimTokenHash,
		arg.LeaseUntil,
		arg.HeartbeatAt,
		arg.CoordinationChannelID,
		arg.QueuedAt,
		arg.ClaimedAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.Error,
		arg.MetadataJson,
		arg.ResultJson,
		arg.ReviewRequired,
		arg.ReviewRequestRound,
		arg.ReviewPolicySnapshot,
		arg.ReviewRequestID,
		arg.ParentRunID,
		arg.ReviewID,
		arg.ReviewRound,
		arg.ContinuationReason,
		arg.MissingWorkJson,
		arg.NextRoundGuidance,
		arg.ID,
		arg.PreviousStatus,
		arg.PreviousSessionID,
		arg.PreviousClaimTokenHash,
		arg.PreviousLeaseUntil,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRetryChildRunID = `-- name: GetRetryChildRunID :one
SELECT id
FROM task_runs
WHERE previous_run_id = ?1
ORDER BY queued_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetRetryChildRunID(ctx context.Context, previousRunID sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getRetryChildRunID, previousRunID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listTaskRunIDsForTask = `-- name: ListTaskRunIDsForTask :many
SELECT id FROM task_runs WHERE task_id = ?1
`

func (q *Queries) ListTaskRunIDsForTask(ctx context.Context, taskID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTaskRunIDsForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskRunNeedsAttention = `-- name: MarkTaskRunNeedsAttention :execrows
UPDATE task_runs
SET status = ?1, error = ?2
WHERE id = ?3 AND status = ?4
`

type MarkTaskRunNeedsAttentionParams struct {
	NeedsAttentionStatus string         `json:"needs_attention_status"`
	Error                sql.NullString `json:"error"`
	ID                   string         `json:"id"`
	QueuedStatus         string         `json:"queued_status"`
}

func (q *Queries) MarkTaskRunNeedsAttention(ctx context.Context, arg MarkTaskRunNeedsAttentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTaskRunNeedsAttention,
		arg.NeedsAttentionStatus,
		arg.Error,
		arg.ID,
		arg.QueuedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
