// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vault_mcp.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteMCPAuthToken = `-- name: DeleteMCPAuthToken :execrows
DELETE FROM mcp_auth_tokens WHERE server_name = ?1
`

func (q *Queries) DeleteMCPAuthToken(ctx context.Context, serverName string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMCPAuthToken, serverName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVaultSecret = `-- name: DeleteVaultSecret :execrows
DELETE FROM vault_secrets WHERE ref = ?1
`

func (q *Queries) DeleteVaultSecret(ctx context.Context, ref string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVaultSecret, ref)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMCPAuthToken = `-- name: GetMCPAuthToken :one
SELECT server_name, issuer, client_id, scopes_json, access_token_ref, refresh_token_ref,
       token_type, expires_at, obtained_at, updated_at
FROM mcp_auth_tokens WHERE server_name = ?1
`

func (q *Queries) GetMCPAuthToken(ctx context.Context, serverName string) (McpAuthToken, error) {
	row := q.db.QueryRowContext(ctx, getMCPAuthToken, serverName)
	var i McpAuthToken
	err := row.Scan(
		&i.ServerName,
		&i.Issuer,
		&i.ClientID,
		&i.ScopesJson,
		&i.AccessTokenRef,
		&i.RefreshTokenRef,
		&i.TokenType,
		&i.ExpiresAt,
		&i.ObtainedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCPAuthTokenRefs = `-- name: GetMCPAuthTokenRefs :one
SELECT access_token_ref, refresh_token_ref
FROM mcp_auth_tokens WHERE server_name = ?1
`

type GetMCPAuthTokenRefsRow struct {
	AccessTokenRef  string `json:"access_token_ref"`
	RefreshTokenRef string `json:"refresh_token_ref"`
}

func (q *Queries) GetMCPAuthTokenRefs(ctx context.Context, serverName string) (GetMCPAuthTokenRefsRow, error) {
	row := q.db.QueryRowContext(ctx, getMCPAuthTokenRefs, serverName)
	var i GetMCPAuthTokenRefsRow
	err := row.Scan(&i.AccessTokenRef, &i.RefreshTokenRef)
	return i, err
}

const getVaultSecret = `-- name: GetVaultSecret :one
SELECT ref, kind, encrypted_value, created_at, updated_at
FROM vault_secrets WHERE ref = ?1
`

func (q *Queries) GetVaultSecret(ctx context.Context, ref string) (VaultSecret, error) {
	row := q.db.QueryRowContext(ctx, getVaultSecret, ref)
	var i VaultSecret
	err := row.Scan(
		&i.Ref,
		&i.Kind,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMCPAuthTokens = `-- name: ListMCPAuthTokens :many
SELECT server_name, issuer, client_id, scopes_json, access_token_ref, refresh_token_ref,
       token_type, expires_at, obtained_at, updated_at
FROM mcp_auth_tokens ORDER BY server_name ASC
`

func (q *Queries) ListMCPAuthTokens(ctx context.Context) ([]McpAuthToken, error) {
	rows, err := q.db.QueryContext(ctx, listMCPAuthTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpAuthToken{}
	for rows.Next() {
		var i McpAuthToken
		if err := rows.Scan(
			&i.ServerName,
			&i.Issuer,
			&i.ClientID,
			&i.ScopesJson,
			&i.AccessTokenRef,
			&i.RefreshTokenRef,
			&i.TokenType,
			&i.ExpiresAt,
			&i.ObtainedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMCPAuthToken = `-- name: UpsertMCPAuthToken :exec
INSERT INTO mcp_auth_tokens (
  server_name, issuer, client_id, scopes_json, access_token_ref, refresh_token_ref,
  token_type, expires_at, obtained_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10
)
ON CONFLICT(server_name) DO UPDATE SET
  issuer = excluded.issuer, client_id = excluded.client_id, scopes_json = excluded.scopes_json,
  access_token_ref = excluded.access_token_ref, refresh_token_ref = excluded.refresh_token_ref,
  token_type = excluded.token_type, expires_at = excluded.expires_at,
  obtained_at = excluded.obtained_at, updated_at = excluded.updated_at
`

type UpsertMCPAuthTokenParams struct {
	ServerName      string         `json:"server_name"`
	Issuer          string         `json:"issuer"`
	ClientID        string         `json:"client_id"`
	ScopesJson      string         `json:"scopes_json"`
	AccessTokenRef  string         `json:"access_token_ref"`
	RefreshTokenRef string         `json:"refresh_token_ref"`
	TokenType       string         `json:"token_type"`
	ExpiresAt       sql.NullString `json:"expires_at"`
	ObtainedAt      string         `json:"obtained_at"`
	UpdatedAt       string         `json:"updated_at"`
}

func (q *Queries) UpsertMCPAuthToken(ctx context.Context, arg UpsertMCPAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertMCPAuthToken,
		arg.ServerName,
		arg.Issuer,
		arg.ClientID,
		arg.ScopesJson,
		arg.AccessTokenRef,
		arg.RefreshTokenRef,
		arg.TokenType,
		arg.ExpiresAt,
		arg.ObtainedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertVaultSecret = `-- name: UpsertVaultSecret :exec
INSERT INTO vault_secrets (ref, kind, encrypted_value, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(ref) DO UPDATE SET
  kind = excluded.kind, encrypted_value = excluded.encrypted_value, updated_at = excluded.updated_at
`

type UpsertVaultSecretParams struct {
	Ref            string `json:"ref"`
	Kind           string `json:"kind"`
	EncryptedValue string `json:"encrypted_value"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

func (q *Queries) UpsertVaultSecret(ctx context.Context, arg UpsertVaultSecretParams) error {
	_, err := q.db.ExecContext(ctx, upsertVaultSecret,
		arg.Ref,
		arg.Kind,
		arg.EncryptedValue,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
