package main

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"syscall"
	"testing"
)

func TestRunWithPaths(t *testing.T) {
	t.Run("ShouldReturnUsageWhenTargetIsMissing", func(t *testing.T) {
		t.Parallel()

		err := runWithPaths(context.Background(), nil, "ignored-openapi.json", "ignored-contracts.ts")
		if err == nil {
			t.Fatal("runWithPaths() error = nil, want usage error")
		}
		if !strings.Contains(err.Error(), "usage: agh-codegen") {
			t.Fatalf("runWithPaths() error = %q, want usage guidance", err.Error())
		}
	})

	t.Run("ShouldRejectUnknownTargets", func(t *testing.T) {
		t.Parallel()

		err := runWithPaths(
			context.Background(),
			[]string{"unknown"},
			"ignored-openapi.json",
			"ignored-contracts.ts",
		)
		if err == nil {
			t.Fatal("runWithPaths() error = nil, want unknown target error")
		}
		if !strings.Contains(err.Error(), `unknown codegen target "unknown"`) {
			t.Fatalf("runWithPaths() error = %q, want unknown target guidance", err.Error())
		}
	})

	t.Run("ShouldWriteAndCheckOpenAPIAtProvidedPath", func(t *testing.T) {
		t.Parallel()

		openapiPath := filepath.Join(t.TempDir(), "generated", "agh.json")

		if err := runWithPaths(
			context.Background(),
			[]string{"openapi"},
			openapiPath,
			"ignored-contracts.ts",
		); err != nil {
			t.Fatalf("runWithPaths(openapi) error = %v", err)
		}

		content, err := os.ReadFile(openapiPath)
		if err != nil {
			t.Fatalf("os.ReadFile(%q) error = %v", openapiPath, err)
		}
		if !bytes.Contains(content, []byte(`"openapi": "3.0.3"`)) {
			t.Fatalf("generated openapi missing version header: %s", string(content))
		}

		if err := runWithPaths(
			context.Background(),
			[]string{"check"},
			openapiPath,
			filepath.Join(t.TempDir(), "missing.ts"),
		); err == nil {
			t.Fatal("runWithPaths(check) error = nil, want sdk missing output error")
		} else if !strings.Contains(
			err.Error(),
			"missing; run codegen",
		) {
			t.Fatalf("runWithPaths(check) error = %q, want missing output guidance", err.Error())
		}

		if err := checkOpenAPI(openapiPath); err != nil {
			t.Fatalf("checkOpenAPI() error = %v", err)
		}
	})

	t.Run("ShouldWriteAndCheckSDKContractsAtProvidedPath", func(t *testing.T) {
		t.Parallel()

		sdkContractsPath := filepath.Join(t.TempDir(), "sdk", "contracts.ts")

		if err := runWithPaths(
			context.Background(),
			[]string{"sdk-contracts"},
			"ignored-openapi.json",
			sdkContractsPath,
		); err != nil {
			t.Fatalf("runWithPaths(sdk-contracts) error = %v", err)
		}

		content, err := os.ReadFile(sdkContractsPath)
		if err != nil {
			t.Fatalf("os.ReadFile(%q) error = %v", sdkContractsPath, err)
		}
		if !bytes.Contains(content, []byte("Code generated by go run ./cmd/agh-codegen sdk-contracts")) {
			t.Fatalf("generated sdk contracts missing header: %s", string(content))
		}

		if err := checkSDKContracts(context.Background(), sdkContractsPath); err != nil {
			t.Fatalf("checkSDKContracts() error = %v", err)
		}
	})

	t.Run("ShouldWriteAllAndRejectStaleArtifacts", func(t *testing.T) {
		t.Parallel()

		dir := t.TempDir()
		openapiPath := filepath.Join(dir, "openapi", "agh.json")
		sdkContractsPath := filepath.Join(dir, "sdk", "typescript", "src", "generated", "contracts.ts")

		if err := runWithPaths(context.Background(), []string{"all"}, openapiPath, sdkContractsPath); err != nil {
			t.Fatalf("runWithPaths(all) error = %v", err)
		}
		if err := runWithPaths(context.Background(), []string{"check"}, openapiPath, sdkContractsPath); err != nil {
			t.Fatalf("runWithPaths(check) error = %v", err)
		}

		if err := os.WriteFile(openapiPath, []byte("{\"broken\":true}\n"), 0o644); err != nil {
			t.Fatalf("os.WriteFile(%q) error = %v", openapiPath, err)
		}
		err := runWithPaths(context.Background(), []string{"check"}, openapiPath, sdkContractsPath)
		if !errors.Is(err, ErrStaleGeneratedFile) {
			t.Fatalf("runWithPaths(check) error = %v, want ErrStaleGeneratedFile for stale openapi", err)
		}

		if err := writeOpenAPI(openapiPath); err != nil {
			t.Fatalf("writeOpenAPI(%q) error = %v", openapiPath, err)
		}
		if err := os.WriteFile(sdkContractsPath, []byte("export type Broken = true;\n"), 0o644); err != nil {
			t.Fatalf("os.WriteFile(%q) error = %v", sdkContractsPath, err)
		}
		err = runWithPaths(context.Background(), []string{"check"}, openapiPath, sdkContractsPath)
		if !errors.Is(err, ErrStaleGeneratedFile) {
			t.Fatalf("runWithPaths(check) error = %v, want ErrStaleGeneratedFile for stale sdk", err)
		}
	})
}

func TestRun(t *testing.T) {
	t.Run("ShouldReturnUsageWhenTargetIsMissing", func(t *testing.T) {
		t.Parallel()

		err := run(context.Background(), nil)
		if err == nil {
			t.Fatal("run() error = nil, want usage error")
		}
		if !strings.Contains(err.Error(), "usage: agh-codegen") {
			t.Fatalf("run() error = %q, want usage guidance", err.Error())
		}
	})

	t.Run("ShouldRejectUnknownTargets", func(t *testing.T) {
		t.Parallel()

		err := run(context.Background(), []string{"unknown"})
		if err == nil {
			t.Fatal("run() error = nil, want unknown target error")
		}
		if !strings.Contains(err.Error(), `unknown codegen target "unknown"`) {
			t.Fatalf("run() error = %q, want unknown target guidance", err.Error())
		}
	})
}

func TestCheckJSONFile(t *testing.T) {
	tests := []struct {
		name        string
		fileContent []byte
		want        []byte
		wantErr     error
	}{
		{
			name:        "ShouldIgnoreFormattingDifferences",
			fileContent: []byte("{\n  \"z\": 1,\n  \"nested\": {\"b\": 2, \"a\": [1, 2]}\n}\n"),
			want:        []byte("{\"nested\":{\"a\":[1,2],\"b\":2},\"z\":1}"),
		},
		{
			name:        "ShouldRejectContentDifferences",
			fileContent: []byte("{\"version\":1}\n"),
			want:        []byte("{\"version\":2}\n"),
			wantErr:     ErrStaleGeneratedFile,
		},
		{
			name:        "ShouldIgnoreEquivalentNumberRepresentations",
			fileContent: []byte("{\"version\":1.0}\n"),
			want:        []byte("{\"version\":1}\n"),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			path := filepath.Join(t.TempDir(), "openapi.json")
			if err := os.WriteFile(path, tt.fileContent, 0o644); err != nil {
				t.Fatalf("os.WriteFile() error = %v", err)
			}

			err := checkJSONFile(path, tt.want)
			switch {
			case tt.wantErr == nil && err != nil:
				t.Fatalf("checkJSONFile() error = %v, want nil", err)
			case tt.wantErr != nil && !errors.Is(err, tt.wantErr):
				t.Fatalf("checkJSONFile() error = %v, want %v", err, tt.wantErr)
			}
		})
	}

	t.Run("ShouldReportMissingFiles", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "missing-openapi.json")
		err := checkJSONFile(path, []byte("{}"))
		if err == nil {
			t.Fatal("checkJSONFile() error = nil, want missing file error")
		}
		if !strings.Contains(err.Error(), "missing; run codegen") {
			t.Fatalf("checkJSONFile() error = %q, want missing output guidance", err.Error())
		}
	})

	t.Run("ShouldRejectInvalidCheckedInJSON", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "openapi.json")
		if err := os.WriteFile(path, []byte("{broken"), 0o644); err != nil {
			t.Fatalf("os.WriteFile() error = %v", err)
		}

		err := checkJSONFile(path, []byte("{}"))
		if err == nil {
			t.Fatal("checkJSONFile() error = nil, want decode error")
		}
		if !strings.Contains(err.Error(), "decode") {
			t.Fatalf("checkJSONFile() error = %q, want decode context", err.Error())
		}
	})

	t.Run("ShouldRejectInvalidGeneratedJSON", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "openapi.json")
		if err := os.WriteFile(path, []byte("{}"), 0o644); err != nil {
			t.Fatalf("os.WriteFile() error = %v", err)
		}

		err := checkJSONFile(path, []byte("{broken"))
		if err == nil {
			t.Fatal("checkJSONFile() error = nil, want decode error")
		}
		if !strings.Contains(err.Error(), "decode generated json") {
			t.Fatalf("checkJSONFile() error = %q, want generated decode context", err.Error())
		}
	})
}

func TestCheckFile(t *testing.T) {
	t.Run("ShouldAcceptMatchingContent", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "generated.ts")
		want := []byte("export type Value = \"ready\";\n")
		if err := os.WriteFile(path, want, 0o644); err != nil {
			t.Fatalf("os.WriteFile() error = %v", err)
		}

		if err := checkFile(path, want); err != nil {
			t.Fatalf("checkFile() error = %v", err)
		}
	})

	t.Run("ShouldRejectStaleContent", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "generated.ts")
		if err := os.WriteFile(path, []byte("export type Value = \"stale\";\n"), 0o644); err != nil {
			t.Fatalf("os.WriteFile() error = %v", err)
		}

		err := checkFile(path, []byte("export type Value = \"fresh\";\n"))
		if !errors.Is(err, ErrStaleGeneratedFile) {
			t.Fatalf("checkFile() error = %v, want ErrStaleGeneratedFile", err)
		}
	})

	t.Run("ShouldReportMissingContent", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "missing.ts")
		err := checkFile(path, []byte("export type Value = \"fresh\";\n"))
		if err == nil {
			t.Fatal("checkFile() error = nil, want missing file error")
		}
		if !strings.Contains(err.Error(), "missing; run codegen") {
			t.Fatalf("checkFile() error = %q, want missing output guidance", err.Error())
		}
	})
}

func TestCanonicalJSON(t *testing.T) {
	t.Run("ShouldNormalizeValidJSON", func(t *testing.T) {
		t.Parallel()

		got, err := canonicalJSON([]byte("{\"z\":1,\"nested\":{\"b\":2,\"a\":1}}"))
		if err != nil {
			t.Fatalf("canonicalJSON() error = %v", err)
		}
		if string(got) != "{\"nested\":{\"a\":1,\"b\":2},\"z\":1}" {
			t.Fatalf("canonicalJSON() = %q, want canonical ordering", string(got))
		}
	})

	t.Run("ShouldRejectInvalidJSON", func(t *testing.T) {
		t.Parallel()

		if _, err := canonicalJSON([]byte("{broken")); err == nil {
			t.Fatal("canonicalJSON() error = nil, want invalid json error")
		}
	})
}

func TestWriteOpenAPI(t *testing.T) {
	t.Run("ShouldWriteTheGeneratedDocument", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "openapi", "agh.json")
		if err := writeOpenAPI(path); err != nil {
			t.Fatalf("writeOpenAPI() error = %v", err)
		}

		content, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("os.ReadFile(%q) error = %v", path, err)
		}
		if !bytes.Contains(content, []byte(`"openapi": "3.0.3"`)) {
			t.Fatalf("writeOpenAPI() missing version header: %s", string(content))
		}
	})

	t.Run("ShouldPropagateWriteErrors", func(t *testing.T) {
		t.Parallel()

		err := writeOpenAPI(t.TempDir())
		if err == nil {
			t.Fatal("writeOpenAPI() error = nil, want non-nil")
		}
		if !strings.Contains(err.Error(), "write openapi") {
			t.Fatalf("writeOpenAPI() error = %q, want wrapped write context", err.Error())
		}
	})
}

func TestWriteSDKContracts(t *testing.T) {
	t.Run("ShouldWriteFormattedContracts", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "sdk", "contracts.ts")
		if err := writeSDKContracts(context.Background(), path); err != nil {
			t.Fatalf("writeSDKContracts() error = %v", err)
		}

		content, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("os.ReadFile(%q) error = %v", path, err)
		}
		if !bytes.Contains(content, []byte("Code generated by go run ./cmd/agh-codegen sdk-contracts")) {
			t.Fatalf("writeSDKContracts() missing generated header: %s", string(content))
		}
	})

	t.Run("ShouldPropagateWriteErrors", func(t *testing.T) {
		t.Parallel()

		if runtime.GOOS == "windows" {
			t.Skip("directory permission semantics differ on windows")
		}

		dir := filepath.Join(t.TempDir(), "locked")
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatalf("os.MkdirAll(%q) error = %v", dir, err)
		}
		if err := os.Chmod(dir, 0o500); err != nil {
			t.Fatalf("os.Chmod(%q) error = %v", dir, err)
		}
		t.Cleanup(func() {
			if err := os.Chmod(dir, 0o700); err != nil {
				t.Fatalf("restore directory permissions: %v", err)
			}
		})

		err := writeSDKContracts(context.Background(), filepath.Join(dir, "contracts.ts"))
		if err == nil {
			t.Fatal("writeSDKContracts() error = nil, want non-nil")
		}
		if !strings.Contains(err.Error(), "write sdk contracts") {
			t.Fatalf("writeSDKContracts() error = %q, want wrapped write context", err.Error())
		}
	})
}

func TestShutdownSignals(t *testing.T) {
	t.Parallel()

	signals := shutdownSignals()
	if !slices.ContainsFunc(signals, func(signal os.Signal) bool {
		return signal == os.Interrupt
	}) {
		t.Fatalf("shutdownSignals() = %#v, want os.Interrupt", signals)
	}
	if !slices.ContainsFunc(signals, func(signal os.Signal) bool {
		return signal == syscall.SIGTERM
	}) {
		t.Fatalf("shutdownSignals() = %#v, want syscall.SIGTERM", signals)
	}
}

func TestFormatTypeScript(t *testing.T) {
	t.Run("ShouldMatchRepositoryFormatter", func(t *testing.T) {
		t.Parallel()

		formatted, err := formatTypeScript(
			context.Background(),
			"sdk/typescript/src/generated/contracts.ts",
			[]byte("export type Value =\n  | \"a\"\n  | \"b\";\n"),
		)
		if err != nil {
			t.Fatalf("formatTypeScript() error = %v", err)
		}
		if got, want := string(formatted), "export type Value = \"a\" | \"b\";\n"; got != want {
			t.Fatalf("formatTypeScript() = %q, want %q", got, want)
		}
	})

	t.Run("ShouldReturnContextErrorWhenCanceled", func(t *testing.T) {
		t.Parallel()

		ctx, cancel := context.WithCancel(context.Background())
		cancel()

		_, err := formatTypeScript(
			ctx,
			"sdk/typescript/src/generated/contracts.ts",
			[]byte("export type Value = \"a\";\n"),
		)
		if !errors.Is(err, context.Canceled) {
			t.Fatalf("formatTypeScript() error = %v, want context.Canceled", err)
		}
	})
}

func TestMarshalOpenAPI(t *testing.T) {
	t.Parallel()

	content, err := marshalOpenAPI()
	if err != nil {
		t.Fatalf("marshalOpenAPI() error = %v", err)
	}
	if !bytes.Contains(content, []byte(`"openapi": "3.0.3"`)) {
		t.Fatalf("marshalOpenAPI() missing version header: %s", string(content))
	}
	if !bytes.Contains(content, []byte(`"/api/daemon/status"`)) {
		t.Fatalf("marshalOpenAPI() missing daemon status route: %s", string(content))
	}
}

func TestGenerateFormattedSDKContracts(t *testing.T) {
	t.Run("ShouldFormatGeneratedContracts", func(t *testing.T) {
		t.Parallel()

		content, err := generateFormattedSDKContracts(
			context.Background(),
			filepath.Join(t.TempDir(), "sdk", "contracts.ts"),
		)
		if err != nil {
			t.Fatalf("generateFormattedSDKContracts() error = %v", err)
		}
		if !bytes.Contains(content, []byte("Code generated by go run ./cmd/agh-codegen sdk-contracts")) {
			t.Fatalf("generateFormattedSDKContracts() missing generated header: %s", string(content))
		}
	})

	t.Run("ShouldReturnContextErrorsFromFormatting", func(t *testing.T) {
		t.Parallel()

		ctx, cancel := context.WithCancel(context.Background())
		cancel()

		_, err := generateFormattedSDKContracts(
			ctx,
			filepath.Join(t.TempDir(), "sdk", "contracts.ts"),
		)
		if !errors.Is(err, context.Canceled) {
			t.Fatalf("generateFormattedSDKContracts() error = %v, want context.Canceled", err)
		}
	})
}

func TestRemoveTemporaryFile(t *testing.T) {
	t.Run("ShouldIgnoreMissingFile", func(t *testing.T) {
		t.Parallel()

		path := filepath.Join(t.TempDir(), "missing-openapi.json")
		if err := removeTemporaryFile(path); err != nil {
			t.Fatalf("removeTemporaryFile() error = %v, want nil", err)
		}
	})

	t.Run("ShouldReturnErrorWhenDirectoryDoesNotPermitDeletion", func(t *testing.T) {
		t.Parallel()

		if runtime.GOOS == "windows" {
			t.Skip("directory permission semantics differ on windows")
		}

		dir := filepath.Join(t.TempDir(), "locked")
		if err := os.Mkdir(dir, 0o755); err != nil {
			t.Fatalf("os.Mkdir() error = %v", err)
		}

		path := filepath.Join(dir, "openapi.json")
		if err := os.WriteFile(path, []byte("{}"), 0o644); err != nil {
			t.Fatalf("os.WriteFile() error = %v", err)
		}

		if err := os.Chmod(dir, 0o500); err != nil {
			t.Fatalf("os.Chmod(%q) error = %v", dir, err)
		}
		t.Cleanup(func() {
			if err := os.Chmod(dir, 0o700); err != nil {
				t.Fatalf("restore directory permissions: %v", err)
			}
		})

		err := removeTemporaryFile(path)
		if err == nil {
			t.Fatal("removeTemporaryFile() error = nil, want non-nil")
		}
		if !strings.Contains(err.Error(), path) {
			t.Fatalf("removeTemporaryFile() error = %q, want path %q in message", err.Error(), path)
		}
	})
}
