/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppNetworkRouteImport } from './routes/_app/network'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppBridgesRouteImport } from './routes/_app/bridges'
import { Route as AppAutomationRouteImport } from './routes/_app/automation'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsObservabilityRouteImport } from './routes/_app/settings/observability'
import { Route as AppSettingsMemoryRouteImport } from './routes/_app/settings/memory'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general'
import { Route as AppSessionIdRouteImport } from './routes/_app/session.$id'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppBridgesRoute = AppBridgesRouteImport.update({
  id: '/bridges',
  path: '/bridges',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsObservabilityRoute =
  AppSettingsObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsMemoryRoute = AppSettingsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSessionIdRoute = AppSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/design-system': typeof DesignSystemRoute
  '/automation': typeof AppAutomationRoute
  '/bridges': typeof AppBridgesRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/network': typeof AppNetworkRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/skills': typeof AppSkillsRoute
  '/session/$id': typeof AppSessionIdRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/memory': typeof AppSettingsMemoryRoute
  '/settings/observability': typeof AppSettingsObservabilityRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof DesignSystemRoute
  '/automation': typeof AppAutomationRoute
  '/bridges': typeof AppBridgesRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/network': typeof AppNetworkRoute
  '/skills': typeof AppSkillsRoute
  '/': typeof AppIndexRoute
  '/session/$id': typeof AppSessionIdRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/memory': typeof AppSettingsMemoryRoute
  '/settings/observability': typeof AppSettingsObservabilityRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/_app/automation': typeof AppAutomationRoute
  '/_app/bridges': typeof AppBridgesRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/skills': typeof AppSkillsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/session/$id': typeof AppSessionIdRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/settings/memory': typeof AppSettingsMemoryRoute
  '/_app/settings/observability': typeof AppSettingsObservabilityRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/automation'
    | '/bridges'
    | '/knowledge'
    | '/network'
    | '/settings'
    | '/skills'
    | '/session/$id'
    | '/settings/general'
    | '/settings/memory'
    | '/settings/observability'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design-system'
    | '/automation'
    | '/bridges'
    | '/knowledge'
    | '/network'
    | '/skills'
    | '/'
    | '/session/$id'
    | '/settings/general'
    | '/settings/memory'
    | '/settings/observability'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/design-system'
    | '/_app/automation'
    | '/_app/bridges'
    | '/_app/knowledge'
    | '/_app/network'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/'
    | '/_app/session/$id'
    | '/_app/settings/general'
    | '/_app/settings/memory'
    | '/_app/settings/observability'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bridges': {
      id: '/_app/bridges'
      path: '/bridges'
      fullPath: '/bridges'
      preLoaderRoute: typeof AppBridgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation': {
      id: '/_app/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/observability': {
      id: '/_app/settings/observability'
      path: '/observability'
      fullPath: '/settings/observability'
      preLoaderRoute: typeof AppSettingsObservabilityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/memory': {
      id: '/_app/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof AppSettingsMemoryRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/session/$id': {
      id: '/_app/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof AppSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsMemoryRoute: typeof AppSettingsMemoryRoute
  AppSettingsObservabilityRoute: typeof AppSettingsObservabilityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsMemoryRoute: AppSettingsMemoryRoute,
  AppSettingsObservabilityRoute: AppSettingsObservabilityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAutomationRoute: typeof AppAutomationRoute
  AppBridgesRoute: typeof AppBridgesRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSkillsRoute: typeof AppSkillsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSessionIdRoute: typeof AppSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationRoute: AppAutomationRoute,
  AppBridgesRoute: AppBridgesRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSkillsRoute: AppSkillsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSessionIdRoute: AppSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
