package globaldb

import "github.com/compozy/agh/internal/store"

var globalSchemaMigrations = append([]store.Migration{
	{
		Version:    1,
		Name:       "create_global_schema",
		Statements: globalSchemaStatements,
		Checksum:   "70e2c16c9d32e692891ab71d075ca823782626e7c9f6ffbbc88c5d662704e089",
	},
	{
		Version:  2,
		Name:     "add_session_failure_diagnostics",
		Up:       migrateSessionFailureColumns,
		Checksum: "2026-04-24-add-session-failure-diagnostics",
	},
	{
		Version:  3,
		Name:     "add_automation_scheduler_state",
		Up:       migrateAutomationSchedulerState,
		Checksum: "2026-04-24-add-automation-scheduler-state",
	},
	{
		Version:  4,
		Name:     "add_mcp_auth_tokens",
		Up:       migrateMCPAuthTokens,
		Checksum: "2026-04-25-add-mcp-auth-tokens",
	},
	{
		Version:  5,
		Name:     "add_tool_process_records",
		Up:       migrateToolProcessRecords,
		Checksum: "2026-04-24-add-tool-process-records",
	},
	{
		Version:  6,
		Name:     "add_memory_operation_scope",
		Up:       migrateMemoryOperationScopeColumns,
		Checksum: "2026-04-25-add-memory-operation-scope",
	},
	{
		Version:  7,
		Name:     "add_task_run_claim_lease_schema",
		Up:       migrateTaskRunClaimLeaseSchema,
		Checksum: "2026-04-26-add-task-run-claim-lease-schema",
	},
	{
		Version:  8,
		Name:     "add_session_lineage_metadata",
		Up:       migrateSessionLineageColumns,
		Checksum: "2026-04-26-add-session-lineage-metadata",
	},
	{
		Version:  9,
		Name:     "rename_environment_columns_to_sandbox",
		Up:       migrateSandboxColumnNames,
		Checksum: "2026-04-28-rename-environment-columns-to-sandbox",
	},
	{
		Version:  10,
		Name:     "add_vault_secrets",
		Up:       migrateVaultSecrets,
		Checksum: "2026-05-01-add-vault-secrets",
	},
	{
		Version:  11,
		Name:     "unify_secret_refs",
		Up:       migrateUnifiedSecretRefs,
		Checksum: "2026-05-01-unify-secret-refs",
	},
	{
		Version:  12,
		Name:     globalDBAddAgentSoulSnapshotsKey,
		Up:       migrateAgentSoulSnapshots,
		Checksum: "2026-05-02-add-agent-soul-snapshots",
	},
	{
		Version:  13,
		Name:     globalDBAddAgentHeartbeatStorageKey,
		Up:       migrateAgentHeartbeatStorage,
		Checksum: "2026-05-02-add-agent-heartbeat-storage",
	},
	{
		Version:  14,
		Name:     "add_event_summary_lineage",
		Up:       migrateEventSummaryLineageColumns,
		Checksum: "2026-05-04-add-event-summary-lineage",
	},
	{
		Version:  15,
		Name:     "rebuild_event_summaries_for_global_payloads",
		Up:       migrateEventSummaryGlobalPayloads,
		Checksum: "2026-05-04-rebuild-event-summaries-for-global-payloads",
	},
	{
		Version:  16,
		Name:     "rename_actor_ref_columns_to_actor_id",
		Up:       migrateActorIDColumns,
		Checksum: "2026-05-04-rename-actor-ref-columns-to-actor-id",
	},
	{
		Version:  17,
		Name:     "add_task_orchestration_profile_schema",
		Up:       migrateTaskOrchestrationProfileSchema,
		Checksum: "2026-05-05-add-task-orchestration-profile-schema",
	},
	{
		Version:  18,
		Name:     "add_task_review_gate_schema",
		Up:       migrateTaskReviewGateSchema,
		Checksum: "2026-05-05-add-task-review-gate-schema",
	},
	{
		Version:  19,
		Name:     "add_notification_cursors",
		Up:       migrateNotificationCursors,
		Checksum: "2026-05-05-add-notification-cursors",
	},
	{
		Version:  20,
		Name:     "add_bridge_task_subscriptions",
		Up:       migrateBridgeTaskSubscriptions,
		Checksum: "2026-05-05-add-bridge-task-subscriptions",
	},
	{
		Version:  21,
		Name:     "rebuild_network_conversation_containers",
		Up:       migrateNetworkConversationContainers,
		Checksum: "2026-05-05-rebuild-network-conversation-containers",
	},
	{
		Version:  22,
		Name:     "memv2_memory_events",
		Up:       migrateMemoryV2Events,
		Checksum: "2026-05-05-memv2-memory-events",
	},
	{
		Version:  23,
		Name:     "add_model_catalog_persistence",
		Up:       migrateModelCatalogPersistence,
		Checksum: "2026-05-07-add-model-catalog-persistence",
	},
	{
		Version:  24,
		Name:     globalDBRebuildModelCatalogSourceConstraintsKey,
		Up:       migrateModelCatalogSourceConstraints,
		Checksum: modelCatalogSourceConstraintChecksum,
	},
	{
		Version:  25,
		Name:     "workspace_qualified_network_identity",
		Up:       migrateWorkspaceQualifiedNetworkIdentity,
		Checksum: "2026-05-12-workspace-qualified-network-identity",
	},
	{
		Version:  26,
		Name:     "add_network_timeline_extensions",
		Up:       migrateNetworkTimelineExtensions,
		Checksum: "2026-05-16-add-network-timeline-extensions",
	},
	{
		Version:  27,
		Name:     "add_config_apply_records",
		Up:       migrateConfigApplyRecords,
		Checksum: "2026-05-20-add-config-apply-records",
	},
	{
		Version:  28,
		Name:     "add_event_summary_projections",
		Up:       migrateEventSummaryProjections,
		Checksum: "2026-05-20-add-event-summary-projections",
	},
	{
		Version:  29,
		Name:     "add_scheduler_pause_state",
		Up:       migrateSchedulerPauseState,
		Checksum: "2026-05-20-add-scheduler-pause-state",
	},
	{
		Version:  30,
		Name:     "add_session_attach_lock",
		Up:       migrateSessionAttachLock,
		Checksum: "2026-05-20-add-session-attach-lock",
	},
	{
		Version:  31,
		Name:     "add_session_input_queue",
		Up:       migrateSessionInputQueue,
		Checksum: "2026-05-21-add-session-input-queue",
	},
	{
		Version:  32,
		Name:     "add_task_run_force_ops",
		Up:       migrateTaskRunForceOps,
		Checksum: "2026-05-21-add-task-run-force-ops",
	},
	{
		Version:  33,
		Name:     "add_task_pause_state",
		Up:       migratePauseState,
		Checksum: "2026-05-21-add-task-pause-state",
	},
	{
		Version:  34,
		Name:     "add_extension_provenance",
		Up:       migrateExtensionProvenance,
		Checksum: "2026-05-21-add-extension-provenance",
	},
	{
		Version:  35,
		Name:     "add_bridge_target_directory",
		Up:       migrateBridgeTargetDirectory,
		Checksum: "2026-05-21-add-bridge-target-directory",
	},
	{
		Version:  36,
		Name:     "add_notification_presets",
		Up:       migrateNotificationPresets,
		Checksum: "2026-05-21-add-notification-presets",
	},
	{
		Version:  37,
		Name:     "add_app_metadata",
		Up:       migrateAppMetadata,
		Checksum: "2026-05-25-add-app-metadata",
	},
	{
		Version:  38,
		Name:     migrationNameHealSchedulerPause,
		Up:       migrateHealSchedulerPauseUpdatedAt,
		Checksum: "2026-05-28-heal-scheduler-pause-updated-at",
	},
	{
		Version:  39,
		Name:     "drop_task_run_status_check",
		UpConn:   migrateDropTaskRunStatusCheck,
		Checksum: "2026-05-28-drop-task-run-status-check",
	},
	{
		Version:  40,
		Name:     "add_task_run_starvation_tracking",
		Up:       migrateTaskRunStarvation,
		Checksum: "2026-05-28-add-task-run-starvation-tracking",
	},
	{
		Version:  41,
		Name:     "add_task_auto_enqueue",
		Up:       migrateTaskAutoEnqueueSchema,
		Checksum: "2026-05-29-add-task-auto-enqueue",
	},
	{
		Version:  42,
		Name:     "add_task_execution_profile_runtime_mode",
		Up:       migrateTaskExecutionProfileRuntimeMode,
		Checksum: "2026-05-31-add-task-execution-profile-runtime-mode",
	},
	{
		Version:  43,
		Name:     "add_network_thread_peer_token_stats",
		Up:       migrateNetworkThreadPeerTokenStats,
		Checksum: "2026-07-01-add-network-thread-peer-token-stats",
	},
	{
		Version:  44,
		Name:     "add_network_activation_policy_mentions",
		Up:       migrateNetworkActivationPolicyMentions,
		Checksum: "2026-07-01-add-network-activation-policy-mentions",
	},
	{
		Version:  45,
		Name:     "add_network_subscriptions_guidance_state",
		Up:       migrateNetworkSubscriptionsGuidanceState,
		Checksum: "2026-07-01-add-network-subscriptions-guidance-state",
	},
	{
		Version:  46,
		Name:     "add_network_task_thread_origins",
		Up:       migrateNetworkTaskThreadOrigins,
		Checksum: "2026-07-01-add-network-task-thread-origins",
	},
	{
		Version:  47,
		Name:     "add_task_run_designations",
		Up:       migrateTaskRunDesignations,
		Checksum: "2026-07-01-add-task-run-designations",
	},
	{
		Version:  48,
		Name:     "rebuild_tasks_for_task_blocks",
		UpConn:   migrateTaskBlockingFoundation,
		Checksum: "2026-07-02-rebuild-tasks-for-task-blocks",
	},
	{
		Version:  49,
		Name:     "add_task_block_tables",
		UpConn:   migrateTaskBlockTables,
		Checksum: "2026-07-02-add-task-block-tables",
	},
	{
		Version:  50,
		Name:     "add_loop_run_state_schema",
		UpConn:   migrateLoopRunStateSchema,
		Checksum: "2026-07-04-add-loop-run-state-schema",
	},
	{
		Version:  51,
		Name:     "add_loop_run_queue_ordering",
		Up:       migrateLoopRunQueueOrdering,
		Checksum: "2026-07-04-add-loop-run-queue-ordering",
	},
	{
		Version:  52,
		Name:     "add_loop_output_blobs",
		Up:       migrateLoopOutputBlobs,
		Checksum: "2026-07-04-add-loop-output-blobs",
	},
	{
		Version:  53,
		Name:     "add_loop_run_iteration_cap",
		Up:       migrateLoopRunIterationCap,
		Checksum: "2026-07-04-add-loop-run-iteration-cap",
	},
	{
		Version:  54,
		Name:     "add_loop_generation_outputs_output_ref_index",
		Up:       migrateLoopGenerationOutputsOutputRefIndex,
		Checksum: "2026-07-04-add-loop-generation-outputs-output-ref-index",
	},
	{
		Version:  55,
		Name:     "add_automation_loop_targets",
		Up:       migrateAutomationLoopTargets,
		Checksum: "2026-07-05-add-automation-loop-targets",
	},
	{
		Version:  56,
		Name:     "add_loop_run_start_actor",
		Up:       migrateLoopRunStartActor,
		Checksum: "2026-07-05-add-loop-run-start-actor",
	},
	{
		Version:  57,
		Name:     "add_loop_run_pinning",
		Up:       migrateLoopRunPinning,
		Checksum: "2026-07-07-add-loop-run-pinning",
	},
	{
		Version:  58,
		Name:     "add_loop_config_model_defaults",
		Up:       migrateLoopConfigModelDefaults,
		Checksum: "2026-07-07-add-loop-config-model-defaults",
	},
	{
		Version:  59,
		Name:     "update_automation_catch_up_contract",
		UpConn:   migrateAutomationCatchUpContract,
		Checksum: "2026-07-07-update-automation-catch-up-contract",
	},
	{
		Version:  60,
		Name:     "add_session_transcript_epoch",
		Up:       migrateSessionTranscriptEpoch,
		Checksum: "2026-07-07-add-session-transcript-epoch",
	},
	{
		Version:  61,
		Name:     "add_sessions_workspace_state_index",
		Up:       migrateSessionsWorkspaceStateIndex,
		Checksum: "2026-07-07-add-sessions-workspace-state-index",
	},
	taskEventsTypeSeqMigration,
	watchEventReplayProjectionsMigration,
}, globalSchemaTailMigrations...)
