#!/usr/bin/env python3
"""Deep-review manifest builder (bootstrap helper).

Reads the repo (and gh for --pr), writes only under --out. Produces
manifest.json accounting for EVERY changed file as selected / ignored / skipped
/ carried, applying the funnel: path filters -> binary -> generated ->
pure-rename -> whitespace-only -> incremental delta scoping. Also resolves the
repo review profile (.deep-review.yaml, else .coderabbit.yaml) into the manifest.
Exit codes: 0 ok, 1 usage/environment error, 2 git/gh failure.
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

DEFAULT_FILTERS = [
    "!**/*.lock", "!**/*.sum", "!**/package-lock.json", "!**/bun.lock", "!**/yarn.lock",
    "!**/pnpm-lock.yaml", "!**/*.min.js", "!**/*.min.css", "!**/*.map",
    "!**/vendor/**", "!**/node_modules/**", "!**/dist/**", "!**/build/**",
    "!**/generated/**", "!**/*.gen.*", "!**/*_pb2.py", "!**/*.pb.go", "!**/*_string.go",
    "!**/*.d.ts", "!**/testdata/**", "!**/fixtures/**", "!**/__snapshots__/**",
    "!**/*.snap", "!**/*.log", "!.git/**",
]
GENERATED_MARKERS = (b"Code generated by", b"@generated", b"DO NOT EDIT",
                     b"Autogenerated by", b"automatically generated")
CONFIG_NAMES = (".deep-review.yaml", ".deep-review.yml", ".coderabbit.yaml", ".coderabbit.yml")


def run(cmd, cwd, check=True):
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if check and proc.returncode != 0:
        sys.stderr.write(f"command failed ({proc.returncode}): {' '.join(cmd)}\n{proc.stderr}\n")
        sys.exit(2)
    return proc


def glob_to_regex(pat: str) -> re.Pattern:
    out, i = [], 0
    while i < len(pat):
        c = pat[i]
        if c == "*":
            if pat[i:i + 3] == "**/":
                out.append("(?:.*/)?"); i += 3
            elif pat[i:i + 2] == "**":
                out.append(".*"); i += 2
            else:
                out.append("[^/]*"); i += 1
        elif c == "?":
            out.append("[^/]"); i += 1
        else:
            out.append(re.escape(c)); i += 1
    return re.compile("^" + "".join(out) + "$")


def parse_path_filters(config_path: Path):
    """YAML-lite: extract list items under a 'path_filters:' key."""
    if not config_path.is_file():
        return None
    lines = config_path.read_text(encoding="utf-8", errors="replace").splitlines()
    filters, capturing, key_indent = [], False, 0
    for line in lines:
        stripped = line.strip()
        if re.match(r"^path_filters\s*:", stripped):
            capturing, key_indent = True, len(line) - len(line.lstrip())
            continue
        if capturing:
            if stripped and not stripped.startswith("#"):
                indent = len(line) - len(line.lstrip())
                m = re.match(r"^-\s*[\"']?([^\"']+?)[\"']?\s*$", stripped)
                if m and indent > key_indent:
                    filters.append(m.group(1))
                elif indent <= key_indent:
                    capturing = False
    return filters or None


def load_filters(repo_root: Path):
    for name in CONFIG_NAMES:
        parsed = parse_path_filters(repo_root / name)
        if parsed is not None:
            return parsed + DEFAULT_FILTERS, name
    return list(DEFAULT_FILTERS), "built-ins"


def parse_profile(config_path: Path):
    """YAML-lite: `profile:` scalar at indent <= 2 (skips text embedded in literal blocks)."""
    if not config_path.is_file():
        return None
    for line in config_path.read_text(encoding="utf-8", errors="replace").splitlines():
        if len(line) - len(line.lstrip()) > 2:
            continue
        m = re.match(r"^profile\s*:\s*[\"']?(chill|assertive)[\"']?\s*$", line.strip())
        if m:
            return m.group(1)
    return None


def resolve_profile(repo_root: Path):
    for name in CONFIG_NAMES:
        profile = parse_profile(repo_root / name)
        if profile:
            return profile, name
    return None, None


def resolve_default_base(repo_root: Path) -> str:
    head_ref = run(["git", "symbolic-ref", "--quiet", "refs/remotes/origin/HEAD"], repo_root, check=False)
    if head_ref.returncode == 0 and head_ref.stdout.strip():
        return head_ref.stdout.strip().replace("refs/remotes/", "")
    for cand in ("origin/main", "origin/master", "main", "master"):
        if run(["git", "rev-parse", "--verify", "--quiet", cand], repo_root, check=False).returncode == 0:
            return cand
    sys.stderr.write("cannot resolve a default base branch; pass --base explicitly\n")
    sys.exit(1)


def resolve_pr(repo_root: Path, pr: int):
    probe = run(["gh", "auth", "status"], repo_root, check=False)
    if probe.returncode != 0:
        sys.stderr.write("gh is not authenticated; run: gh auth login\n")
        sys.exit(1)
    view = run(["gh", "pr", "view", str(pr), "--json", "baseRefOid,headRefOid,title,url"], repo_root)
    data = json.loads(view.stdout)
    head = data["headRefOid"]
    if run(["git", "cat-file", "-e", f"{head}^{{commit}}"], repo_root, check=False).returncode != 0:
        sys.stderr.write(
            f"PR head {head} is not local. Fetch it first:\n  git fetch origin pull/{pr}/head\n")
        sys.exit(1)
    return data["baseRefOid"], head, data


def diff_name_status(repo_root: Path, base, head, staged=False):
    cmd = ["git", "diff", "--name-status", "-M50"]
    cmd += ["--staged"] if staged else [f"{base}..{head}"]
    entries = []
    for line in run(cmd, repo_root).stdout.splitlines():
        parts = line.split("\t")
        status = parts[0]
        if status.startswith("R") and len(parts) == 3:
            entries.append({"path": parts[2], "status": status, "old_path": parts[1]})
        elif len(parts) >= 2:
            entries.append({"path": parts[1], "status": status, "old_path": None})
    return entries


def numstat(repo_root: Path, base, head, staged=False, extra=()):
    cmd = ["git", "diff", "--numstat", "-M50", *extra]
    cmd += ["--staged"] if staged else [f"{base}..{head}"]
    stats = {}
    for line in run(cmd, repo_root).stdout.splitlines():
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        adds, dels, path = parts[0], parts[1], parts[-1]
        if "=>" in path and "{" in path:  # rename syntax a/{b => c}/d
            prefix, rest = path.split("{", 1)
            inner, suffix = rest.split("}", 1)
            path = prefix + inner.split(" => ")[1] + suffix
        elif " => " in path:
            path = path.split(" => ")[1]
        stats[path] = (None if adds == "-" else int(adds), None if dels == "-" else int(dels))
    return stats


def looks_generated(repo_root: Path, path: str) -> bool:
    f = repo_root / path
    if not f.is_file():
        return False
    try:
        with f.open("rb") as fh:
            head_bytes = fh.read(2048)
    except OSError as err:
        sys.stderr.write(f"warn: cannot probe {path}: {err}\n")
        return False
    return any(marker in head_bytes for marker in GENERATED_MARKERS)


def collect_hunks(repo_root: Path, base, head, staged=False):
    """New-side line ranges per file (the PR-diff view; also the publish anchors)."""
    cmd = ["git", "diff", "-U0", "-M50"]
    cmd += ["--staged"] if staged else [f"{base}..{head}"]
    hunks, current = {}, None
    for line in run(cmd, repo_root).stdout.splitlines():
        if line.startswith("+++ "):
            path = line[4:].strip()
            current = None if path == "/dev/null" else (path[2:] if path.startswith("b/") else path)
        elif line.startswith("@@") and current:
            m = re.match(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@", line)
            if m:
                start = int(m.group(1))
                n = int(m.group(2)) if m.group(2) is not None else 1
                hunks.setdefault(current, []).append({"start": start, "lines": n})
    return hunks


def prior_head(state_path: Path):
    if not state_path.is_file():
        return None, 0
    try:
        state = json.loads(state_path.read_text(encoding="utf-8"))
        rounds = state.get("rounds", [])
        return (rounds[-1]["head"], rounds[-1]["n"]) if rounds else (None, 0)
    except (ValueError, KeyError) as err:
        sys.stderr.write(f"warn: unreadable state {state_path} ({err}); running full\n")
        return None, 0


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", required=True)
    ap.add_argument("--pr", type=int)
    ap.add_argument("--base")
    ap.add_argument("--head", default="HEAD")
    ap.add_argument("--staged", action="store_true")
    ap.add_argument("--files", help="comma-separated subset")
    ap.add_argument("--full", action="store_true")
    args = ap.parse_args()
    if args.pr and (args.base or args.staged):
        ap.error("--pr conflicts with --base/--staged")

    top = run(["git", "rev-parse", "--show-toplevel"], Path.cwd())
    repo_root = Path(top.stdout.strip())
    out_dir = Path(args.out); out_dir.mkdir(parents=True, exist_ok=True)

    pr_meta = None
    if args.pr:
        base, head, pr_meta = resolve_pr(repo_root, args.pr)
        target = f"pr:{args.pr}"
    elif args.staged:
        base, head, target = "HEAD", "STAGED", "staged"
    else:
        base_ref = args.base or resolve_default_base(repo_root)
        base = run(["git", "merge-base", base_ref, args.head], repo_root).stdout.strip()
        head = run(["git", "rev-parse", args.head], repo_root).stdout.strip()
        target = f"diff:{base_ref}"

    filters, filter_source = load_filters(repo_root)
    profile, profile_source = resolve_profile(repo_root)
    excludes = [(p, glob_to_regex(p[1:])) for p in filters if p.startswith("!")]
    includes = [(p, glob_to_regex(p)) for p in filters if not p.startswith("!")]

    mode, effective_base, round_n = "full", base, 1
    if not args.full and not args.staged:
        last_head, last_n = prior_head(out_dir / "state.json")
        if last_head and run(["git", "merge-base", "--is-ancestor", last_head, head],
                             repo_root, check=False).returncode == 0 and last_head != head:
            mode, effective_base, round_n = "incremental", last_head, last_n + 1

    entries = diff_name_status(repo_root, base, head, args.staged)
    stats = numstat(repo_root, base, head, args.staged)
    ws_stats = numstat(repo_root, base, head, args.staged, extra=("-w", "--ignore-blank-lines"))
    hunk_map = collect_hunks(repo_root, base, head, args.staged)
    delta_paths = None
    if mode == "incremental":
        delta_paths = {e["path"] for e in diff_name_status(repo_root, effective_base, head)}

    subset = {p.strip() for p in args.files.split(",")} if args.files else None
    files, counts = [], {"selected": 0, "ignored": 0, "skipped": 0, "carried": 0}
    for e in sorted(entries, key=lambda x: x["path"]):
        path, status = e["path"], e["status"]
        adds, dels = stats.get(path, (0, 0))
        rec = {"path": path, "status": status, "adds": adds, "dels": dels}
        if e["old_path"]:
            rec["old_path"] = e["old_path"]

        disposition, reason = "selected", None
        if subset is not None and path not in subset:
            disposition, reason = "ignored", "outside --files subset"
        else:
            exc = next((p for p, rx in excludes if rx.match(path)), None)
            inc = next((p for p, rx in includes if rx.match(path)), None)
            if includes and not inc:
                disposition, reason = "ignored", "matches no include pattern"
            elif exc and not inc:
                disposition, reason = "ignored", f"excluded by `{exc}`"
            elif adds is None or dels is None:
                disposition, reason = "skipped", "binary"
            elif status.startswith("R") and adds == 0 and dels == 0:
                disposition, reason = "skipped", f"pure rename from `{e['old_path']}`"
            elif (adds or dels) and ws_stats.get(path, (0, 0)) == (0, 0):
                disposition, reason = "skipped", "whitespace-only change"
            elif status != "D" and looks_generated(repo_root, path):
                disposition, reason = "skipped", "generated-file marker in content"
            elif delta_paths is not None and path not in delta_paths:
                disposition, reason = "carried", f"unchanged since round {round_n - 1} head"

        rec["disposition"] = disposition
        if reason:
            rec["reason"] = reason
        if disposition == "selected":
            rec["hunks"] = hunk_map.get(path, [])
        counts[disposition] += 1
        files.append(rec)

    manifest = {
        "target": target, "mode": "staged" if args.staged else mode, "round": round_n,
        "base": base, "effective_base": effective_base, "head": head,
        "filter_source": filter_source, "profile": profile, "counts": counts, "files": files,
    }
    if pr_meta:
        manifest["pr"] = {"number": args.pr, "title": pr_meta["title"], "url": pr_meta["url"]}
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    total = len(files)
    print(f"manifest: {out_dir / 'manifest.json'}")
    print(f"target={target} mode={manifest['mode']} round={round_n}")
    print(f"base={base[:12]} effective_base={effective_base[:12] if effective_base != base else '(same)'} head={head[:12]}")
    print(f"files: {total} changed -> {counts['selected']} selected, {counts['ignored']} ignored, "
          f"{counts['skipped']} skipped, {counts['carried']} carried (filters: {filter_source})")
    print(f"profile: {profile} (from {profile_source})" if profile
          else "profile: unset (skill defaults to chill)")
    if counts["selected"] == 0:
        print("nothing selected — review has no reviewable surface")


if __name__ == "__main__":
    main()
